chain/chain

- Readme.md
Fixes phrasing in the readme.
(This is also a test of the CLA Assistant.)
> readme: fix wording

- installer/windows/README.md
Per a suggestion from @danrobinson, point folks to our downloads page.
> installer/windows: link to downloads page

- docs/protocol/papers/protocol-roadmap.md
Edited language in Protocol Roadmap paper.
> protocol/docs: revised protocol roadmap

- docs/protocol/papers/federated-consensus.md
Edited language in Federated Consensus Paper.
> docs/protocol: revise consensus paper

- cmd/sha3/doc.go
- cmd/sha3/sha3.go
As described in https://gist.github.com/kr/2977d492d6afc428e31f49dee13dc3a7
> cmd/sha3: sha3 cmd

- cmd/cored/main.go
- core/account/builder_test.go
- core/api_test.go
- core/asset/annotate_test.go
- core/asset/asset.go
- core/asset/asset_test.go
- core/asset/block_test.go
- core/core.go
- core/hsm_test.go
- core/query/query_test.go
- core/recovery_test.go
- core/transact_test.go
- core/txbuilder/finalize_test.go
- protocol/block_test.go
- protocol/protocol.go
- protocol/prottest/block.go
- protocol/recover_test.go
Resurrects some code from https://github.com/chain/chain/pull/26. Related to https://github.com/chain/chainprv/issues/2404.
> protocol: add initial block hash field to the Chain object

- cmd/ed25519/doc.go
- cmd/ed25519/ed25519.go
As described in https://gist.github.com/kr/2977d492d6afc428e31f49dee13dc3a7
> cmd/ed25519: ed25519 cmd

- cmd/testbot/main.go
> cmd/testbot: unmarshal pull request number as int

- protocol/bc/transaction_test.go
- protocol/bc/txinput.go
- protocol/block.go
- protocol/validation/bench_test.go
- protocol/validation/block.go
- protocol/validation/block_test.go
- protocol/validation/tx.go
- protocol/validation/tx_test.go
Fixes https://github.com/chain/chainprv/issues/2404
Supersedes https://github.com/chain/chain/pull/58
Back roughly where we started in https://github.com/chain/chain/pull/26
> protocol/validation: add blockchain ID checking to issuance validation

- core/account/utxodb/reserve.go
We don't define any PL/pgSQL `cancel_reservations` function, there's
only `cancel_reservation`. Also, rolling back is already covered by the
deferred SQL transaction rollback, so this call is redundant.
> core/account/utxodb: fix Reserve defer func

- core/account/accounts.go
- core/account/utxodb/db.go
Rename to DBReserver to reflect that reservation happens within the DB.
Also, move the periodic logic of ExpireReservations out of utxodb and
into the account package.
This is preparation for adding an in-memory reserver that can be used
when a Core has a single process.
> core/account/utxodb: rename to DBReserver

- core/errors.go
The CH706 error encapsulates multiple errors. It should be marked as
temporary if all of its contained errors are also temporary. This is
relevant because CH761 can be returned by actions and is temporary.
> core: set errorInfo 'temporary' field for CH706

- core/api-spec.md
- core/core.go
> core: expose Core ID in /info

- cmd/benchcore/main.go
Not all AMIs can be used on all instances, so this change adds a lookup table. Some instance types also require us to specify an EBS volume to get more than a few GB of storage.
> cmd/benchcore: fix multiple instance types

- cmd/testnet-reset/main.go
This commit updates the BLOCKCHAIN_ID config var
in the chain-testnet-info app after the network is reset.
> cmd/testnet-reset: update testnet info after reset

- cmd/benchcore/main.go
Set MAXDBCONNS to 100. Also, fix the m3.xlarge ami to support EBS.
> cmd/benchcore: set MAXDBCONNS, fix m3.xlarge ami

- docs/tools/checklinks.rb
Lets say you have file `alice.md` with a cross-file link `[link](bob.md#bad-anchor)`. 
Previous version of this tool was reporting:
Broken link in bob.md: [link (from alice.md)](#bad-anchor)
Since usually it's the link that is broken, not the title, checklinks.rb now reports:
Broken link in alice.md: [link](bob.md#bad-anchor)
Which is much more useful: we know that we have to go to `alice.md` and fix the link there.
> docs/tools/checklinks.rb: fix reports for broken cross-file references

- cmd/benchcore/main.go
We hit the open file limit if we try to do > 1000 txs/sec. Raise the limit on the cored machine.
> cmd/benchcore: raise open file limit

- core/coreunsafe/reset.go
Rather than having a maintained list of tables that are truncated, it is
more simple to maintain a list of tables which should not be reset. This
change makes it so that all tables are truncated unless they are
contained in the persistBlockchainReset or neverReset lists.
> core/coreunsafe: remove explicit truncate list

- cmd/testnet-reset/main.go
The chain-core-ccte Heroku app adds a light load to the 
testnet. This app needs to be shut down before resetting
the network. Once the network is reset, the app's config
vars should be updated and it should be restarted.
> cmd/testnet-reset: turn off bot before resetting

- docs/core/examples/java/Assets.java
Edits:
- misspelled definition field was causing query to fail
- second list-asset example was not printing
- tx queries were looking for input.action field; should be input.type
> docs: fix Assets.java example

- core/txbuilder/export_test.go
- core/txbuilder/finalize.go
- core/txbuilder/finalize_test.go
Fixes https://github.com/chain/chain/issues/160
> core/txbuilder: check issuance inputs as well as spends for tx finality

- core/migrate/data.go
- core/schema.sql
> core/migrate: remove not null constraint from txfeeds client_token

- core/account/accounts.go
- core/asset/asset.go
Filtering aliases is the source of > 50% of all SQL queries in one of my
benchmarks.
> core: cache account and asset aliases

- dashboard/src/assets/styles/_body.scss
- dashboard/src/assets/styles/_bootstrap-overrides.scss
- dashboard/src/assets/styles/resources.scss
- dashboard/src/features/app/components/Config/Config.scss
- dashboard/src/features/app/components/Navigation/Navigation.scss
- dashboard/src/features/app/components/SecondaryNavigation/SecondaryNavigation.scss
- dashboard/src/features/configuration/components/Index/Index.scss
- dashboard/src/features/shared/components/BaseList/EmptyList.scss
- dashboard/src/features/shared/components/FieldLabel/FieldLabel.scss
- dashboard/src/features/shared/components/FormSection/FormSection.scss
- dashboard/src/features/shared/components/KeyValueTable/KeyValueTable.scss
- dashboard/src/features/shared/components/PageTitle/PageTitle.scss
- dashboard/src/features/shared/components/Pagination/Pagination.scss
- dashboard/src/features/shared/components/SearchBar/SearchBar.scss
- dashboard/src/features/shared/components/Section/Section.scss
- dashboard/src/features/shared/components/TableList/TableList.scss
- dashboard/src/features/transactions/components/ListItem/ListItem.scss
- dashboard/src/features/transactions/components/New/FormActionItem.scss
- dashboard/src/features/transactions/components/Summary/Summary.jsx
- dashboard/src/features/transactions/components/Summary/Summary.scss
We are a focused team with a product roadmap, so we can't guarantee that a pull request will receive the attention it might deserve.
However, if you've found a way to help out the Chain Core community by submitting a bugfix, we'll do our best to work with you to get your code merged. Please use the following process to contribute:
1. Open a new issue describing the bug or feature
2. Receive feedback from Chain staff
3. Collaborate with Chain staff around the design of the code
4. Write the patch adhering to Chain's Code Style Guide: https://github.com/chain/chain/blob/main/docs/internal/styleguide.md
5. Complete legal requirements for Chain's Contributor License
If you have questions about how to contribute, please visit the Chain developer support center: https://support.chain.com
> dashboard: make color, font and line-height adjustments for visual consistency

- sdk/ruby/LICENSE
- sdk/ruby/README.md
- sdk/ruby/chain-sdk.gemspec
- sdk/ruby/lib/chain/version.rb
This commit finalizes changes for Ruby SDK 1.0.0:
- set VERSION constant
- add license document
- update readme with Rubygems instructions
> sdk/ruby: version 1.0.0

- core/account/utxodb/reserve.go
Refactor the findMatchingUTXOs call into sourceReserver.reserve so
that the sourceReserver can cache UTXOs that it knows are available.
> core/account/utxodb: refactor findMatchingUTXOs call

- perf/UtxoReservation.java
- sdk/java/pom.xml
- sdk/java/src/main/java/com/chain/api/Account.java
- sdk/java/src/main/java/com/chain/api/Asset.java
- sdk/java/src/main/java/com/chain/api/ControlProgram.java
- sdk/java/src/main/java/com/chain/api/PagedItems.java
- sdk/java/src/main/java/com/chain/api/Transaction.java
- sdk/java/src/main/java/com/chain/exception/BuildException.java
- sdk/java/src/main/java/com/chain/http/BatchResponse.java
- sdk/java/src/main/java/com/chain/http/Client.java
- sdk/java/src/main/java/com/chain/signing/HsmSigner.java
- sdk/java/src/test/java/com/chain/integration/NotificationTest.java
> sdk/java: make sdk Java 1.7 compliant

- core/query/outputs.go
This change both resolves a TODO and makes the code amenable to static analysis
for SQLi vulnerabilities by gas.
Though safe in its previous form, it was written in a way in which gas was
unable to assert its safety.
> core/query: Use bytes.Buffer to construct outputs query

- core/txfeed/txfeed.go
Using bytes.Buffer instead of string concatenation makes the code amenable to
static analysis by gas.
> core/txfeed: Use bytes.Buffer to construct txfeed queries

- cmd/benchcore/main.go
This makes the "-p" flag also capture trace profiles, which can be
examined with the pprof trace tool.
> cmd/benchcore: capture trace profiles

- cmd/gobundle/main.go
- cmd/md2html/main.go
- wercker.yml
gas is a static analyzer for security issues:
https://github.com/GoASTScanner/gas
> wercker.yml: Add Go AST Scanner (gas)

- CHANGELOG.md
- cmd/cored/CHANGELOG.md
- installer/mac/CHANGELOG.md
- installer/windows/CHANGELOG.md
- sdk/ruby/CHANGELOG.md
Minor tweaks to the changelogs:
- Use root changelog as index document
- Move cored changelog to cmd/cored
- Add h1-level title headings to each changelog
> all: update changelog formats

- cmd/benchcore/main.go
Tune Postgres according to the instance type. These values are guesswork
and could use some refining, but they dramatically increase
performance.
> cmd/benchcore: tune Postgres

- core/account/accounts.go
- core/account/builder.go
Insert all of a transactions control programs at once.
> core/account: batch control program inserts

- sdk/java/src/main/java/com/chain/api/Account.java
- sdk/java/src/main/java/com/chain/api/Asset.java
- sdk/java/src/main/java/com/chain/api/ControlProgram.java
- sdk/java/src/main/java/com/chain/api/Transaction.java
This commit updates the Javadoc with required method
calls for the following API objects:
- Account
- Asset
- Transaction.Template
- ControlProgram
> sdk/java: update Javadoc

- core/api_test.go
- core/transact.go
Setup the submit timeout once in the batch endpoint.
> core: refactor submitSingle handler

- cmd/capturestats/main.go
Queries a database's db stats and formats them to stdout.
> cmd/capturestats: captures database query stats

- bin/build-docker-de
- installer/mac/ChainCore/Base.lproj/Main.storyboard
- installer/mac/ChainCore/ChainCore.swift
- installer/mac/tools/build_chain.sh
Embedded cored binary is now built directly from a tag. Removes unused
`Preferences` menu item.
> installer/mac: use build-cored-release to bundle cored

- core/control_programs.go
Other batch endpoints besides create-control-program use the
`batchRecover` function to format error responses and to recover
from panics. The `create-control-program` handler slipped through
the cracks.
> core: use batchRecover in create-control-program

- protocol/validation/tx.go
- protocol/validation/tx_test.go
- protocol/vm/control.go
- protocol/vm/introspection.go
- protocol/vm/introspection_test.go
- protocol/vm/vm.go
- protocol/vm/vm_test.go
Also keep track of the outermost program during CHECKPREDICATE calls, so it can be returned by OP_PROGRAM.
> protocol/vm, protocol/validation: improve error handling and tests

- core/txdb/txdb_test.go
Refactor TestInsertBlock to use GetBlock instead of using its own
helper function to retrieve the block by its hash.
> core/txdb: refactor TestInsertBlock

- protocol/bc/block.go
- protocol/bc/transaction.go
- protocol/bc/transaction_test.go
- protocol/bc/txoutput.go
> protocol/bc: better error messages when de/serializing transactions

- protocol/bc/sighasher.go
- protocol/bc/transaction.go
> protocol/bc: move SigHasher into its own file

- protocol/bc/asset.go
- protocol/bc/transaction.go
> protocol/bc: move AssetAmount into asset.go

- core/asset/block_test.go
- core/txbuilder/txbuilder_test.go
- protocol/bc/issuance.go
- protocol/bc/issuancewitness.go
- protocol/validation/tx_test.go
- protocol/vm/vm_test.go
Part of #349. Moving things around.
> protocol/bc: new type IssuanceWitness

- core/asset/asset.go
- core/asset/asset_test.go
- core/asset/block.go
- core/asset/block_test.go
- core/asset/builder.go
- core/assets.go
- core/migrate/data.go
- core/schema.sql
This addresses https://github.com/chain/chain/issues/382
We also store VMVersion of the issuance program explicitly in the database.
> core/asset: store raw asset definition to ensure stability of AssetID

- protocol/bc/block.go
- protocol/bc/hash.go
- protocol/bc/transaction.go
- protocol/bc/txinput.go
- protocol/bc/txoutput.go
Part of #349. Wraps up some todos.
> protocol/bc: return errors when writing transactions

- protocol/bc/transaction.go
Part of #349. Preparing for transactions with non-empty common witness
> protocol/bc: refactor common witness serialization

- core/query.go
Simple cut and paste change to make navigating the file a little easier.
> core: alphabetize query.go

- core/blocksigner/blocksigner.go
Replace the direct dependency on the core/mockhsm package with a
`Signer` interface. In production, we can pass in a Signer
implementation that talks to signerd instead.
> core/blocksigner: remove mockhsm dependency

- protocol/bc/block.go
This enables sending and receiving block headers in RPC requests.
> protocol/bc: add marshaling function to BlockHeader

- core/config/config.go
- core/migrate/data.go
- core/schema.sql
This allows the core to configure the remote HSM to be used for block
signing.
> core/config: add block hsm settings

- docs/protocol/specifications/txgraph-draft.md
- protocol/tx/map.go
- protocol/tx/tx_test.go
Per discussion with @danrobinson.
> protocol/tx: set valueSource position to 0 when the source is not a mux entry

- cmd/vet/testdata/logparity_rename.go
- core/account/receivers.go
- core/core.go
- core/query/annotated.go
- core/txbuilder/finalize.go
- docs/internal/software-versioning.md
- protocol/protocol.go
- protocol/tx/value.go
- sdk/java/src/main/java/com/chain/http/Client.java
- sdk/node/src/api/transactions.js
- sdk/ruby/lib/chain/transaction.rb
Fix linting errors: dead code, misspellings, etc.
> all: fix linting errors

- sdk/node/src/api/accounts.js
- sdk/node/src/api/transactions.js
- sdk/node/testSrc/callbacks.js
- sdk/node/testSrc/promises.js
- Add createReceiver and createReceiverBatch
- Deprecate createControlProgram
- Add controlWithReceiver txbuilder action
- Deprecate controlWithProgram txbuilder action
> sdk/node: add receivers interface

- cmd/corectl/prod.go
Fixes https://github.com/chain/chain/issues/513
> cmd/corectl: import the right sql package for the prod build

- cmd/cored/dev.go
- cmd/cored/main.go
- cmd/cored/prod.go
- core/api.go
- core/api_test.go
- core/errors.go
- core/hsm.go
- core/hsm_test.go
When the prod build tag is used, mockhsm should not be included in the
final binary.
> cmd/cored: remove mockhsm dependency in prod

- cmd/corectl/main.go
- cmd/cored/main.go
This also adds version information to corectl.
> cmd/cored: tag for release 1.1rc5

- docs/protocol/papers/blockchain-programs.md
This PR adds type annotations to the examples in the Ivy paper, which makes the paper more readable and brings it closer to our current design for the language.
> docs/protocol/papers: add types to examples in blockchain programs paper

- core/query/sql.go
> core/query: change filter.Bool to filter.String

- docs/core/examples/java/Accounts.java
- docs/core/examples/java/Assets.java
- docs/core/examples/java/UnspentOutputs.java
- docs/core/examples/node/accounts.js
- docs/core/examples/node/assets.js
- docs/core/examples/node/unspentOutputs.js
- docs/core/examples/ruby/accounts.rb
- docs/core/examples/ruby/assets.rb
- docs/core/examples/ruby/unspent_outputs.rb
We want to encourage folks to think of outputs as things with scalar unique IDs.
> docs/core/examples: use output ID instead of txid/position tuple

- cmd/cored/main.go
- core/fetch/fetch.go
Download and store the bootstrapping snapshot before creating block
processor pins. This ensures block processors will start processing at
the right height.
Maybe at some point the package-level `core/fetch` state and
goroutines should be encapsulated in a new type.
Fixes #643.
> core/fetch: bootstrap before creating pins

- docs/core/examples/java/RealTimeTransactionProcessing.java
- perf/IouSettlement.java
- perf/UtxoReservation.java
This commit is in preparation for migrating the
existing CI docker images to CentOS. The image
will have Java 7 installed.
> all: make non-sdk java code java 7 compliant

- cmd/cored/main.go
By default, package crypto/tls uses the operating
system's set of global root CAs. This is unsuitable for
a typical production deployment, where the opeator will
run its own CA and provision its own certs.
This change provides a new environment variable:
ROOT_CA_CERTS=certs.pem
This variable holds a filename of a file containing a list
of PEM-encoded root X.509 certificates.
> cmd/cored: configure root CA pool

- sdk/java/src/main/java/com/chain/http/Client.java
- sdk/java/src/main/java/com/chain/http/LoggingInterceptor.java
Enable logging interceptor that can capture requests.
> sdk/java: add LoggingInterceptor

- docs/core/get-started/sdk.md
- sdk/java/CHANGELOG.md
- sdk/java/pom.xml
- sdk/java/src/main/java/com/chain/http/Client.java
- sdk/java/src/main/java/com/chain/http/LoggingInterceptor.java
Cherry-pick of #688, #690, and #689 (in that order)
> sdk/java: backport Java SDK 1.1.1 to 1.1-stable

- wercker.yml
Depends on https://github.com/chain/chain/pull/698
> wercker.yml: update base image

- core/txdb/snapshot_test.go
Add a unit test ensuring that writing a snapshot with issuance memory and
reading that snapshot back out preserves the issuance memory. There are
already analagous tests for the state tree.
> core/txdb: test reading/writing snapshot issuances

- core/query/accounts_test.go
- core/query/assets_test.go
Add tests for querying accounts and assets with a filter.
> core/query: test querying accounts, assets

- testutil/deepequal.go
This is a carved-off piece of the `entries-validation` branch, landing in anticipation of that because txentries data structures are not acyclic.
> testutil: add cycle detection to DeepEqual

- core/txdb/txdb_test.go
Add tests for:
* ListenBlocks
* Store.FinalizeBlock
* Store.GetRawBlock
* Store.GetSnapshot
* Store.LatestSnapshot
* Store.LatestSnapshotInfo
> core/txdb: improve test coverage

- cmd/cored/main.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
This is a prereq for using raft.
> cmd/cored: set up mux and add handlers later

- bin/generate-docs
- docs/core/build-applications/accounts.md
- docs/core/build-applications/assets.md
- docs/core/build-applications/balances.md
- docs/core/build-applications/batch-operations.md
- docs/core/build-applications/control-programs.md
- docs/core/build-applications/keys.md
- docs/core/build-applications/multiparty-trades.md
- docs/core/build-applications/queries.md
- docs/core/build-applications/real-time-transaction-processing.md
- docs/core/build-applications/transaction-basics.md
- docs/core/build-applications/unspent-outputs.md
- docs/core/examples/node/accounts.js
- docs/core/examples/node/assets.js
- docs/core/examples/node/batchOperations.js
- docs/core/examples/node/controlPrograms.js
- docs/core/examples/node/fiveMinuteGuide.js
- docs/core/examples/node/globalVsLocalData.js
- docs/core/examples/node/keys.js
- docs/core/examples/node/multipartyTrades.js
- docs/core/examples/node/queries.js
- docs/core/examples/node/realTimeTransactionProcessing.js
- docs/core/examples/node/transactionBasics.js
- docs/core/examples/node/unspentOutputs.js
- docs/core/get-started/five-minute-guide.md
- docs/core/get-started/sdk.md
- docs/core/learn-more/global-vs-local-data.md
- docs/layout.html
- generated/rev/revid.go
This commit includes changes to the `bin` directory from tag sdk-node-1.0.3, which allow generation of Node SDK documentation.
> bin/generate-docs: allow 1.0-stable to build node docs

- generated/rev/revid.go
- sdk/java/CHANGELOG.md
- sdk/java/pom.xml
- sdk/java/src/main/java/com/chain/http/Client.java
This commit ports the Java SDK from tag sdk-java-1.0.2 to the
> sdk/java: update 1.0-stable with most recent 1.0.x Java SDK

- generated/rev/RevId.java
- generated/rev/revid.go
- installer/mac/ChainCore/DashboardViewController.swift
> installers/mac: fixes OS version check to use a compatible WebView class

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- protocol/block.go
- protocol/validation/block_test.go
These are not comprehensive, but it's a start.
> protocol/validation: add ValidateBlock unit tests

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/java/src/main/java/com/chain/http/Client.java
This adds high availability to the java sdk client for 1.0.x.
> sdk/java: add high availability client

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/java/pom.xml
This is a backport for supporting maven deploys in the 1.0-stable release stream.
> sdk/java: update pom.xml for Maven deploys

- docs/enterprise/thales-install-guide.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> enterprise/docs: update hsm setup instructions

- core/access_tokens.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Missed this when landing #965.
> core: add TODO for atomicity around access tokens and grants

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/java/src/test/java/com/chain/integration/TransactionRejectionTest.java
Add integration tests testing various transaction rejection conditions
and their error codes.
> sdk/java: add tx rejection integration tests

- cmd/corectl/main.go
- core/authz.go
- docker/ci/bin/setup-core
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
All corectl functionality is authorized through our ACLs.
> cmd/corectl: remove database dependency

- docs/core/learn-more/configure-block-signers.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> docs: update block signer guide with latest corectl instructions

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- protocol/bc/legacy/txinput.go
Unindent logic gated on a known asset version.
https://github.com/chain/chain/pull/1001#discussion_r112590874
> protocol/bc/legacy: unindent asset version checks

- app.json
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> app.json: point to latest stable branch with correct logo

- Readme.md
- app.json
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> app.json: use correct logo and template

- cmd/corectl/main.go
- docs/core/reference/corectl.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
This makes the implementation match the instructions.
> cmd/corectl: grant policy along with creating token

- core/authz.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
/docs is no longer a valid route served by cored.
> core: remove docs from authz table

- core/grants.go
- core/grants_test.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> core: add misc validation of create-grant input

- core/authz.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
This is so corectl can use these RPCs.
> core: add authz to internal policy

- docker/ci/bin/setup-core
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/java/src/main/java/com/chain/api/CoreConfig.java
- sdk/java/src/main/java/com/chain/http/Client.java
- sdk/java/src/test/java/com/chain/integration/CoreConfigTest.java
The CoreConfig class finally gives the Java SDK access to
the config package's RPC calls, including:
- /configure
- /reset
- /info
> sdk/java: add CoreConfig class

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- protocol/state/snapshot_test.go
Increase test coverage to 83.9% of statements.
> protocol/state: add unit tests

- core/api.go
- core/authz.go
- core/authz_test.go
- core/core.go
- core/metrics.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- net/http/authn/authn.go
"Cross-core API" has replaced "Network API" in our lexicon. This commit
is a purely server-side, backward-compatible update. Updates to the SDK
and dashboard will follow.
> core: s/networkRPC/crosscoreRPC

- core/core.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> core: fix crosscore RPC version attribute

- dashboard/src/features/core/components/CoreIndex/CoreIndex.jsx
- dashboard/src/features/core/reducers.js
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/java/src/main/java/com/chain/api/CoreConfig.java
- sdk/node/src/api/config.js
- sdk/ruby/lib/chain/config.rb
Also, expose the flag in the dashboard.
> sdk: expose plain_http feature flag in SDKs

- core/access_tokens.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Printkv expects an even number of arguments.
> core: provide even # of arguments to Printkv

- core/authz.go
- core/authz_test.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> core: add /info to internal policy

- docker/de/Readme.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- Fix Markdown formatting for Github display
- Add detail for persisting the data directory
> docker/de: update Readme for formatting and accuracy

- dashboard/src/features/core/components/CoreIndex/CoreIndex.jsx
- dashboard/src/features/core/reducers.js
- database/raft/Makefile
- desktop/windows/README.md
- docs/core/reference/cored.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/java/src/main/java/com/chain/api/CoreConfig.java
- sdk/ruby/lib/chain/config.rb
The previous commit missed some places.
> cmd/cored: rename plain_http to http_ok (fixup)

- Readme.md
- bin/build-centos-rpm
- bin/build-cored-release
- bin/run-tests
- cmd/benchcore/main.go
- cmd/cored/reset.go
- cmd/deploy/main.go
- core/config/config.go
- database/raft/Makefile
- desktop/windows/README.md
- docker/ci/bin/setup-core
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
The build tag is now "no_reset" to turn it off.
> cmd/cored: turn reset on by default

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- vendor/github.com/lib/pq/.travis.yml
- vendor/github.com/lib/pq/README.md
- vendor/github.com/lib/pq/array.go
- vendor/github.com/lib/pq/array_test.go
- vendor/github.com/lib/pq/conn.go
- vendor/github.com/lib/pq/conn_go18.go
- vendor/github.com/lib/pq/conn_test.go
- vendor/github.com/lib/pq/copy.go
- vendor/github.com/lib/pq/doc.go
- vendor/github.com/lib/pq/encode.go
- vendor/github.com/lib/pq/encode_test.go
- vendor/github.com/lib/pq/go18_test.go
- vendor/github.com/lib/pq/issues_test.go
- vendor/github.com/lib/pq/listen_example/doc.go
- vendor/github.com/lib/pq/notify_test.go
- vendor/github.com/lib/pq/oid/types.go
- vendor/github.com/lib/pq/ssl.go
- vendor/github.com/lib/pq/ssl_go1.7.go
- vendor/github.com/lib/pq/ssl_permissions.go
- vendor/github.com/lib/pq/ssl_renegotiation.go
- vendor/github.com/lib/pq/ssl_test.go
- vendor/github.com/lib/pq/ssl_windows.go
- vendor/github.com/lib/pq/uuid.go
- vendor/github.com/lib/pq/uuid_test.go
Updates lib/pq to `2704adc878c21e1329f46f6e56a1c387d788ff94`
> vendor/github.com/lib/pq: update

- core/coreunsafe/reset.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Refactor ResetBlockchain and ResetEverything to delete sinkdb's
data atomically.
> core/coreunsafe: reset sinkdb atomically

- core/membership.go
- database/sinkdb/op.go
- database/sinkdb/sinkdb.go
- database/sinkdb/state_test.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
This lets it be combined with other Ops in a single
atomic batch.
> database/sinkdb: turn AddAllowedMember into an Op constructor

- cmd/benchcore/main.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Fix benchcore to work with main.
> cmd/benchcore: fix for 1.2

- core/txbuilder/finalize.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- protocol/block.go
- protocol/protocol.go
Also try to detect an expired transaction during `/submit-transaction`.
> protocol: add missing check for txheader min/maxtime vs. block timestamp

- docs/core/reference/versioning.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> docs: clarify backward compatibility rules for SDKs

- core/grants.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- net/http/authz/store.go
This adds a Delete method to Store, and uses it in core.
> net/http/authz: make Store delete grants

- dashboard/src/features/tutorial/reducers.js
- dashboard/test/specs/accounts.js
- dashboard/test/specs/assets.js
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- Ensure that tutorial does not show up when the dashboard is run using
NODE_ENV=test
- Asset/account creation should select xpub auto-generate option
> dashboard: fix integration tests

- database/sinkdb/op.go
- database/sinkdb/version.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- net/http/authz/store.go
This lets clients do safe conditional writes.
Also update net/http/authz to use the new feature.
> database/sinkdb: introduce IfMatch condition

- database/sinkdb/state.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Include versions in the raft snapshots.
> database/sinkdb: include versions in snapshot

- docker/ci/Dockerfile
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
#1246 fixed the Java install, but failed to properly update environment
variables related to Java. This commit resolves this problem.
> docker/ci: fix java envvars

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/node/test/mockHsmKeys.js
> sdk/node: add MockHSM specific test

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- sdk/node/test/transactionFeeds.js
- sdk/node/testHelpers/util.js
This commit generalizes a test utility function for use in other test
files.
> sdk/node/test: add buildSignSubmit helper to utils

- cmd/blockcache/main.go
- core/core_test.go
- core/tls.go
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- net/tls.go
Backport of #1298, #1311 from main.
> all: set TLS 1.2 as the minimum required version

- docker/ci/bin/java-tests
- docs/core/examples/java/RealTimeTransactionProcessing.java
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- perf/IouSettlement.java
- perf/UtxoReservation.java
- wercker.yml
Upcoming changes to this branch require Go 1.8, included in our 
more recent wercker images. A small cascade of changes to the 
Java test suite were required for compatibility with that image.
> wercker: support latest CI image from main

- bin/build-cored-release
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
> bin/build-cored-release: fix rev-parse bug

- Makefile
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- reset was changed to no_reset
- init_cluster is new post-1.2
> Makefile: fix build tags

- dashboard/src/features/configuration/components/Index/Index.jsx
- dashboard/src/features/configuration/components/Index/Index.scss
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Centers configuration form in an element that can contain the 
maximum expanded form height, improving layout on very tall
displays.
> dashboard: increase vertical spcaing on configuration screen

- docker/ci/install/install-rust
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- wercker.yml
This is needed for doing CI builds of the HSM module for the Thales CodeSafe SEE
environment.
> docker/ci: Install Rust cross-compiler for powerpc-unknown-linux-gnu

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- net/raft/dev/run-additional-node.sh
- net/raft/dev/run-bootstrapped-node.sh
Had some merge commit mess in #1367 - this makes the same change
> net/raft: set -e and -o pipefail in run script

- docs/future/core/reference/corectl.md
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Document the new configuration corectl commands.
> docs/future/core/reference: document new commands

- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
- protocol/block.go
The ErrStaleState error is never referenced.
> protocol: remove unused ErrStaleState

- dashboard/src/features/transactions/actions.js
- dashboard/src/utility/environment.js
- dashboard/test/helpers.js
- dashboard/test/specs/accounts.js
- dashboard/test/specs/assets.js
- dashboard/test/specs/keys.js
- dashboard/test/specs/transactions.js
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
The HSM signer object has been moved underneath
the main Chain client object.
> dashboard: use updated signer interface

- analytics/README.md
- analytics/pom.xml
- analytics/src/main/java/com/chain/analytics/Application.java
- analytics/src/main/java/com/chain/analytics/Config.java
- analytics/src/main/java/com/chain/analytics/Importer.java
- analytics/src/main/java/com/chain/analytics/JsonPath.java
- analytics/src/main/java/com/chain/analytics/OracleTypes.java
- analytics/src/main/java/com/chain/analytics/Schema.java
- analytics/src/main/java/com/chain/analytics/Target.java
- analytics/src/main/resources/example-config.json
- analytics/src/test/java/com/chain/analytics/ConfigTest.java
- analytics/src/test/java/com/chain/analytics/JsonPathTest.java
- analytics/src/test/java/com/chain/analytics/OracleTypesTest.java
- analytics/src/test/java/com/chain/analytics/SchemaTest.java
- generated/rev/RevId.java
- generated/rev/revid.go
- generated/rev/revid.js
- generated/rev/revid.rb
Support custom reference data columns.
> analytics: support custom columns
