chain/chain

docs/protocol/specifications/validation.md

docs/protocol/specifications: fix typo

---

Readme.md

Adds a download link similar to the one suggested in #22, but in the top-level readme, which right now only describes how to build the project from source.

readme: add download link

---

core/account/accounts.go
core/asset/asset.go
core/signers/signers.go
core/signers/signers_test.go

Instead of pulling the db handle out of the context.Context, take an
explicit pg.DB as a parameter.
If we want, we could go farther and have the signers package keep its
own db handle, but the signers abstraction is a little leaky in a few
places. Both the account and asset packages do JOINs on the signers SQL
table.

core/signers: take explicit db handle

---

installer/windows/ChainMgr/ChainMgr.go
installer/windows/ChainPackage/ChainCoreInstaller.wxs
installer/windows/README.md

`cored` gets compiled as `cored.exe`. Let's let `cored`s be `cored`s. (Honestly it's just annoying to rename it every time.) 
This PR also fixes some wonky whitespace in the README.

installer/windows: rename chain-core.exe to cored.exe

---

cmd/corectl/main.go
cmd/cored/main.go
core/access_tokens.go
core/accesstoken/accesstoken.go
core/accesstoken/accesstoken_test.go
core/api.go
core/authn.go

Remove the dependency on the Context's database in the
`core/accesstoken` package.

core/accesstoken: encapsulate storage

---

docs/core/get-started/introduction.md

The previous docs did not include a summary or description of Chain Core. This commit adds a paragraph taken from the website [FAQ](https://chain.com/faq/) to the Introduction section.

docs/core/introduction: add introductory paragraph on Chain Core

---

core/account/utxodb/reserve.go
core/b32enc_test.go
core/mockhsm/mockhsm.go
core/transact.go
core/transact_test.go
core/txbuilder/finalize_test.go
core/txdb/txdb_test.go
core/txfeed/txfeed.go
core/txfeed/txfeed_test.go
database/pg/context.go
database/pg/pgtest/pgtest.go

Delete `pg.Query`, `pg.QueryRow` and `pg.Exec` and update all call sites to either use an explicit db handle in scope or use `pg.FromContext(ctx)`.

database/pg: remove context convenience funcs

---

cmd/cored/main.go

Populate the core.Handler with an accesstoken.CredentialStore when
launching an unconfigured Core. Unconfigured routes still need access
token authentication.
Bug was introduced in #48.

cmd/cored: fix auth on unconfigured core

---

core/api.go

We provide errors in the /info response, which is
authenticated. But /health is not authenticated, and we
don't need to serve the errors in both places. Our
alerting on these errors should provide credentials.

core: remove errors from /health response

---

bin/upload-docs

We strip file extensions when rendering static files in order to
provide for pretty, extension-free URLs. Unfortunately, this
removes S3's ability to deduce the MIME type from the extension.
This commit adds a post-sync step that iterates over every
extensionless file in the generated docs, and updates the content
type to text/html. For now, we're not concerned about false
positives.
One other option we explored was having md2html render non-index
leaf pages as BASENAME/index.html, but this caused relative URLs
in the content to be off by one level of depth. Changing relative
URLs to root-prefixed URLs (/foo/bar) was a deep change, and broke
the ability to browse the Markdown links from GitHub.

bin/upload-docs: set content type on extensionless files

---

cmd/cored/main.go
core/account/accounts.go
core/account/accounts_test.go
core/account/annotate_test.go
core/account/builder.go
core/account/indexer_test.go
core/account/utxodb/reserve.go
core/txbuilder/finalize_test.go

Unfortunately, this means a few tests need to use pgtest.NewDB
instead of pgtest.NewTx to satisfy the account.NewManager signature.

core/account/utxodb: encapsulate storage

---

errors/errors.go
errors/errors_test.go

We plan to use this to report more error detail to RPC clients in a structured format. The Detail functions provide only unstructured text.

errors: add a field for arbitrary data

---

core/account/accounts.go
core/account/accounts_test.go
core/asset/asset.go
core/errors.go
core/txfeed/txfeed.go
core/txfeed/txfeed_test.go

Use a specific Chain error code for errors that try to create an object
with an alias that already exists. Previously, this error was bundled
under the generic bad request error code. It's useful to distinguish so
that clients can write get-or-create functions.
I'm not sure what the appropriate error namespace for this is.

core: use specific error code for non-unique alias

---

cmd/testbot/main.go

This fixes a bug that didn't allow testbot to run
against pull requests from forked repos.

cmd/testbot: fetch pull request instead of branch ref

---

cmd/benchcore/main.go

Add a -with flag so that we can upload test data on the client EC2
instance for the java program to consume.

cmd/benchcore: add -with flag

---

core/errors.go
core/transact.go
core/txbuilder/txbuilder.go

It will be useful for clients to see all available error messages at once, so they can fix them all without having to make multiple requests.

core/txbuilder: return error info for all actions

---

sdk/java/src/main/java/com/chain/api/Account.java
sdk/java/src/main/java/com/chain/api/Asset.java
sdk/java/src/main/java/com/chain/api/ControlProgram.java
sdk/java/src/main/java/com/chain/api/Transaction.java
sdk/java/src/main/java/com/chain/exception/BuildException.java
sdk/java/src/main/java/com/chain/http/BatchResponse.java
sdk/java/src/main/java/com/chain/http/Client.java
sdk/java/src/main/java/com/chain/signing/HsmSigner.java

Unmarshal build errors into BuildException instead of APIException.
Clients will need to use instanceof and cast build errors to
BuildException if using the batch endpoint.

sdk/java: add BuildException for build errors

---

core/account/builder.go
core/account/utxodb/reserve.go
core/txbuilder/txbuilder.go
core/txbuilder/types.go

If one action succeeds with some side effects (most
notably, reserving some UTXOs) and another action fails,
we should roll back the side effects if possible so that
the overall operation has no effect.
Note that this is not a guaranteed operation, so any
side effects need to be designed to be safe not to roll
back. Reservations are: they will eventually expire on
their own. Meanwhile, it helps performance to eagerly
cancel them upon failure rather than waiting for the
deadline to pass.

core/txbuilder: roll back builder side-effects

---

core/account/builder.go
core/account/utxodb/reserve.go

Change the Reserve signature to take a single utxodb.Source instead
of a slice of utxodb.Sources. We only ever provide a single element
slice to the sources parameter.

core/account/utxodb: take single Source in Reserve

---

cmd/benchcore/main.go

Add -instance flag for configuring EC2 instance sizes.

cmd/benchcore: add -instance flag

---

cmd/slashland/main.go
cmd/slashland/slack.go
cmd/slashland/util.go

This package runs an http server to listen connect to slack to be able
to receive and respond to /land commands. This will land pull requests
on the chain and chainprv github repositories.

cmd/slashland: add slack /land command

---

encoding/json/duration.go
encoding/json/duration_test.go

When deserializing API request objects, it's useful to treat null
the same as undefined. This is especially convenient for
high-level languages, where it is common to assign values to
key-value objects that may or may not be null.

encoding/json: treat null as zero-value duration

---

core/account/accounts.go
core/account/indexer.go
core/account/utxodb/db.go

We were writing to the `account_utxos` table during indexing without locking it, but that table requires locking. It probably led to deadlock in a recent test run.

core/account: always lock the account_utxos table

---

cmd/benchcore/main.go

Apparently EBS volumes come "blank" with no filesystem.

cmd/benchcore: make a filesystem

---

sdk/java/src/main/java/com/chain/http/Client.java

By default, OkHttp sets 10-second timeouts:
https://github.com/square/okhttp/blob/okhttp_25/okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java#L190

sdk/java: set default timeouts to 30 seconds

---

core/blocksigner/blocksigner.go
core/generator/generator_test.go
core/query/transactions.go
core/rpc.go
core/transact.go
core/txbuilder/finalize.go
protocol/block_test.go
protocol/protocol.go

This allows callers to select over the call without needing to introduce
a helper function.

protocol: WaitForBlock funcs return chans

---

core/api.go

If UTXOs are fragmented, sign transaction requests (and maybe submit requests too) can exceed the current 100kb request body limit.

core: up max request size to 1mb

---

core/errors.go
core/transact.go
core/txbuilder/txbuilder.go
errors/errors.go
errors/errors_test.go
sdk/java/src/main/java/com/chain/exception/BuildException.java

This lets us accumulate data in an error rather than
entirely replacing what was there before.
This is the first step in an alternate approach to #115.

errors: make WithData merge maps

---

core/query/index.go
core/query/index_test.go
core/query/query_test.go
core/query_test.go

Previously, if the transaction index processor completed before the
asset processor, the transaction index would be missing data. This
change introduces a wait that blocks until the asset processor has
finished the given block.
Closes #76

core/query: fix block processor race

---

cmd/corectl/main.go
cmd/cored/main.go
core/api.go
core/api_test.go
core/config/config.go
core/core.go
core/errors.go

Move `core.Config` and related functions into a new package, `core/config`.
This allows corectl to not import `chain/core` and by extension the
dashboard & documentation.
The `corectl` binary size is reduced from 52M to 15M.

core/config: new package

---

core/pin/pin_test.go

There is no way to guarantee that this test will pass, since notify may
be called before Listen is ready.

core/pin: remove racy Listen test

---

core/coreunsafe/reset.go

This prevents block processors from ignoring blocks after a reset.

core/coreunsafe: truncate block_processors on reset

---

core/account/builder.go
core/asset/builder.go
core/errors.go
core/txbuilder/txbuilder.go

This adds a new txbuilder error ErrMissingFields, and
updates account and asset builders to return that error
along with a list of missing field names.
Depends on #125.

core/txbuilder: report missing field names

---

metrics/metrics.go

We care about the difference between 54ms and 55ms or
230ms and 240ms, but not really between 54ms and 54.1ms
or 230ms and 231ms. Storing only two significant figures
instead of three uses less space. In our case, it uses
about 15% as much space (860kB instead of 5.8MB). This
matters more for efficiency of sampling and storing
metrics than for the performance of cored itself.

metrics: save space with fewer significant figures

---

core/accounts.go
core/assets.go
core/http.go
core/transact.go

Previously, panics in batch endpoints were never recovered and would crash the process. This adds a `batchRecover` function that for recovering panics and converting errors into errorInfo structs.

core: handle panics in batch endpoints

---

core/account/builder.go
core/account/builder_test.go
core/api_test.go
core/hsm_test.go
core/recovery_test.go
core/transact_test.go
core/txbuilder/finalize_test.go

Remove the transaction hash and index parameters from the account spend
action. Now that we have the SpendUTXOAction, we no longer need to be
able to filter account UTXOs by transaction hash.

core/account: remove utxo from SpendAction

---

cmd/testnet-reset/main.go

The cmd is set up on a Heroku cron job with a max
interval of one day. This commit restricts execution
to when the cmd is initiated manually (SCHEDULED=false)
or the execution time is within an hour of Sunday at
midnight.

cmd/testnet-reset: restrict execution time

---

core/pin/pin.go
core/transact.go
sdk/java/src/main/java/com/chain/api/Transaction.java

After introducing block processors, the submit call would return before
the block that contained the transaction had been processed by all
processors. Since this was a change of behavior and since it could cause
confusion when other requests are made before processing, it has been
changed to wait for processing by default. Since finer grain control is
possible, an additional field "WaitFor" has been introduced that will
determine when the submit call returns.

core: wait until transaction block is processed

---

cmd/sha3/sha3.go

Package flag prints the default value on the end of the
line, so we don't need to say it again. This also makes
the other wording a bit more consise.

cmd/sha3: remove redundant info in help output

---

cmd/testbot/main.go

This will add an indicator to github that there is a pending check until
it either passes or fails.

cmd/testbot: report pending status to github

---

bin/build-centos-rpm
docker/centos-rpm/.gitignore
docker/centos-rpm/Dockerfile
docker/centos-rpm/Readme.md
docker/centos-rpm/after-install
docker/centos-rpm/after-remove
docker/centos-rpm/before-install
docker/centos-rpm/init
docker/centos-rpm/startup.sh

build-centos-rpm utilizes a docker container to build
an rpm compatible with centos 5.11 and 6.8. It takes
an optional version number as an argument and uploads
the resulting rpm to the chain-core s3 bucket. 
The upload takes place from the caller's filesystem so
the aws-cli tool is required.

bin/build-centos-rpm: new command

---

bin/generate-docs
sdk/ruby/.gitignore
sdk/ruby/chain-sdk.gemspec
sdk/ruby/lib/chain/access_token.rb
sdk/ruby/lib/chain/transaction.rb
sdk/ruby/lib/chain/version.rb

Adds generation of Ruby docs to generate-docs command, and bundles
the results into the cored executable.
Also:
- fixes some YARD annotation bugs that was breaking generate-docs
- re-bundles the documentation
This does not add a link to the Ruby YARD documentation, which
will happen when we officially release the Ruby SDK. For now, you
can navigate to http://localhost:1999/docs/ruby/doc/index.html .

docs: add Ruby documentation to bundled docs

---

sdk/java/src/main/java/com/chain/http/Client.java

The default OkHttp connection pool is capped at five idle connections.
The OkHttp documenation describes the default connection pool as
"appropriate for a single-user application."
Before setting this, I was frequently seeing "Cannot assign requested
address" errors while running benchmarking tests.

sdk/java: use larger connection pool

---

perf/IouSettlement.java
perf/UtxoReservation.java

In perf tests, only wait until the tx is confirmed. Also, make
UtxoReservation.java a little more ambitious. I also reduced
its duration to make it a little easier to iterate quickly.

perf: only wait for confirmation

---

core/account/builder_test.go
core/api_test.go
core/blocksigner/blocksigner.go
core/generator/generator_test.go
core/hsm_test.go
core/pin/pin.go
core/pin/pin_test.go
core/query/index.go
core/query/query_test.go
core/query/transactions.go
core/rpc.go
core/transact.go
core/txbuilder/finalize.go
core/txbuilder/finalize_test.go
protocol/block_test.go
protocol/protocol.go
protocol/tx.go

The functions `WaitForBlock`, `WaitForBlockSoon`, `WaitForPin`, and `WaitForAll` did not do any actual waiting, so rename them to indicate that waiting can be done with the values they return.

protocol, core/pin: WaitForX -> XWaiter

---

dashboard/src/features/configuration/components/Index/Index.jsx
dashboard/src/features/core/components/Index/Index.jsx
docs/core/get-started/configure.md

Instead of presenting the user with the phrase "Generator Access
Token", we'll use "Network Access Token", which is the object that
is actually created and shared to network participants.

dashboard: change confusing token language

---

dashboard/src/features/shared/components/SearchBar/SearchBar.jsx
dashboard/src/features/shared/components/SearchBar/SearchBar.scss

Safari will not allow a form to be submitted with the enter key unless
there is a submit button on the page that is not hidden. This is in contrast
to Chrome, which worked fine with a hidden submit button.

dashboard: allow Safari to submit balances form with sum_by parameter

---

cmd/cored/main.go

If max conns and max idle conns are not equal, cored will create many db
connections when build & submit requests are coming in, but close them
soon after while waiting for the block to land. Our DB conn needs are very
periodic.

cmd/cored: set MaxIdleConns to MAXDBCONNS too

---

cmd/benchcore/main.go

The newline at the end of the tokens caused auth errors when capturing
profiles.

cmd/benchcore: trim space from tokens

---

sync/idempotency/group.go

The only use case for this right now is in utxo reservation. Errors such
as ErrReserved can be retried, and will continue to only result in
ErrReserved, even if there is an underlying change.

sync/idempotency: make errors non-idempotent

---

core/account/utxodb/reserve.go

Cache confirmed UTXOs on the sourceReserver. Since they're confirmed,
we're guaranteed that they will stay valid. Also, since the reserver is only
run on one leader process, no one else can have spent the UTXOs unless
they circumvented reservation.

core/account/utxodb: cache confirmed UTXOs

---

core/account/utxodb/reserve.go

This reverts commit 1248d643afdb425e35dd934dd933f44fd31726eb. We can double reserve
in some situations.

core/account/utxodb: revert cache confirmed UTXO

---

protocol/mempool/mempool.go
protocol/mempool/sort.go

Sort transactions topologically when dumping the contents of the
pool, if they're not already in topological order. The old txdb pool
used this, but I forgot to port when we moved to the mempool.
Also, don't add a tx to the pool if it's already there.
If we're already topo sorting, should we just use an unordered
`map[bc.Hash]*bc.Tx`?

protocol/mempool: topologically sort

---

core/account/accounts.go
core/account/builder.go
core/account/reserve.go
core/account/reserve_test.go
core/errors.go

The utxodb package was only called by the account package, so it can be
moved in unexported.

core/account: move utxodb reserver here

---

cmd/md2html/main.go
docs/core/build-applications/accounts.md
docs/core/build-applications/assets.md
docs/core/build-applications/balances.md
docs/core/build-applications/batch-operations.md
docs/core/build-applications/control-programs.md
docs/core/build-applications/keys.md
docs/core/build-applications/multiparty-trades.md
docs/core/build-applications/queries.md
docs/core/build-applications/real-time-transaction-processing.md
docs/core/build-applications/transaction-basics.md
docs/core/build-applications/unspent-outputs.md
docs/core/examples/ruby/global_vs_local_data.rb
docs/core/get-started/five-minute-guide.md
docs/core/learn-more/global-vs-local-data.md
docs/css/style.css
docs/js/codeSelector.js
docs/layout.html

This commit adds multi-language snippet support to md2html. Documents should provide snippet directives with the following structure:
$code <snippet-name> <file1> <file2> ...
Example:
$code create-client ../examples/java/FiveMinuteGuide.java ../examples/ruby/five_minute_guide.rb
A snippet block will be generated for every named file. The file must contain the specified snippet, or a block of error text will be generated instead.
In the browser, snippets for different languages will be displayed based on the currently-selected language.

cmd/md2html: multi-language code snippets

---

docs/core/get-started/install.partial.html

Due to performance issues, docker for mac is being removed as an
offering.

docs: remove docker for mac option

---

core/account/builder.go
core/account/reserve.go

It looks like we missed this one when renaming scripts to control programs.

core/account: rename Script to ControlProgram

---

docs/core/reference/versioning.md
docs/layout.html

This document introduces the Chain versioning schemes: core versioning, network versioning, and signer versioning.

docs/reference: introduce versioning schemes

---

cmd/benchcore/main.go

When an instance switches to being RUNNING, I don't think it guarantees
that the public IP address has been assigned. I've seen this a couple of
times:
```
benchcore: 2016/11/17 11:49:00.780579 starting EC2 instances
benchcore: 2016/11/17 11:49:00.780740 building cored
benchcore: 2016/11/17 11:49:18.761466 cored executable: 55291846 bytes
benchcore: 2016/11/17 11:49:18.761487 building corectl
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xaa80]
goroutine 8 [running]:
panic(0x31d400, 0xc4200120f0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.makeEC2.func3(0x1dcd6500, 0xc420013980)
/Users/jackson/src/chain/cmd/benchcore/main.go:510 +0x320
main.retry(0xc4201fdf00) …
```

cmd/benchcore: fix race

---

docs/enterprise/thales-install-guide.md

docs/enterprise: fix list formatting in the Thales install guide

---

core/migrate/data.go
core/schema.sql

The control program ID column was unused. In stats from benchmarks, inserting a control program was the most expensive query in terms of total execution time. The second most expensive query was the subquery retrieving the next value in the ID sequence.

core/account: drop control program id column

---

docs/internal/api-spec.swagger.yml

This document is intended to provide comprehensive documentation
of Client API. Some of our partners have requested this style of
documentation. Since it is a superset of the information provided
in core/api-spec.md, it should eventually replace that document.
Unlike other Swagger API descriptions, this one is not intended to
be used for auto-generation of client libraries.
The current doc is incomplete; future PRs will fill out the rest of the content.

docs/internal: add Swagger version of API spec

---

core/account/builder.go
core/account/builder_test.go
core/asset/builder.go
core/txbuilder/actions.go
core/txbuilder/builder.go
core/txbuilder/txbuilder.go
core/txbuilder/txbuilder_test.go
core/txbuilder/types.go

Refactor txbuilder.Build and txbuilder.Action so that actions modify a shared txbuilder.TemplateBuilder instead of returning txbuilder.BuildResult. Some tests depend on actions orderings matching their corresponding inputs and outputs, so this removes the parallelism from building, at least for now.
This change has one API implication: ErrBadRefData will now correctly be returned as a part of the ErrAction multierror.

core/txbuilder: refactor Build

---

installer/windows/ChainMgr/ChainMgr.go
log/rotation/file.go
metrics/metrics.go
net/http/gzip/gzip.go
net/http/gzip/gzip_test.go
protocol/bc/hash.go
protocol/validation/tx.go
wercker.yml

Includes minor fixes for gas compliance, or #nosec for innocuous cases
The vendor directory is omitted as there are numerous false positives for issues in third-party libraries, and adding #nosec to vendored code is probably not maintainable long-term.

all: extend gas coverage to all directories except vendor

---

sdk/ruby/lib/chain/query.rb
sdk/ruby/lib/chain/transaction_feed.rb
sdk/ruby/spec/integration/integration_spec.rb

Including:
- querying/listing transaction feeds
- deleting transaction feeds

sdk/ruby: add missing transaction feed API calls

---

docs/internal/api-spec.swagger.yml

This also fixes a bug where `Chain-Request-ID` was not reported as a header in error responses.

docs/internal: use YAML node anchors to reduce repetition

---

core/account/indexer.go
core/account/reserve_test.go
core/migrate/data.go
core/schema.sql
core/transact.go
core/transact_test.go

Only index confirmed account UTXOs. Indexing and spending unconfirmed
UTXOs allows for cascading failures if a single transaction fails.
Previously, we indexed unconfirmed outputs only if we had reasonable
certainty that the transaction would be accepted by the network (all of
the associated keys are local to the Chain Core). Transactions can still
fail due to latency issues and the transaction's MaxTime elapsing.
If other transactions had spent the failed tx's pool outputs, the entire
tree of transactions would fail. These cascading failures are difficult
to recover from. If we can avoid indexing/spending pool outputs, we'll
have a simpler system.
Long-term the removal of pool output spending can simplify tx rejection
detection because a Core can validate the transaction against its …

core/account: don't index unconfirmed outputs

---

log/log.go

This prevents some log jitter and creates more uniform lines.

log: use fixed-width time format

---

core/pin/pin.go
core/pin/pin_test.go

Each block processor is independent and idempotent, and so they can be
run in parallel. This particularly helps out the transaction indexer,
which can fall behind due to the long time it takes to process blocks.

core/pin: process blocks in parallel

---

sdk/java/src/main/java/com/chain/http/Client.java

This introduces a builder for client objects. Certain parameters should be set at the start and never again, e.g. connection pool details. This allows those to be set in a clean manner.

sdk/java: add Client.Builder

---

core/transact.go

Deserialize into `[]txbuilder.Template` instead of `[]*txbuilder.Template`
This prevents the need for an explicit check for a nil template if
`null` is provided instead of a transaction template JSON object.
Instead, txbuilder.ErrMissingRawTx will be returned:
https://github.com/chain/chain/blob/main/core/errors.go#L125
Fixes #128.

core: guard against nil templates

---

core/account/accounts.go
core/account/reserve.go
core/account/reserve_test.go
protocol/patricia/patricia.go
protocol/state/outputs.go

Cache account UTXOs in the reserver. This allows some reservation
requests to avoid hitting the database if there are enough cached
UTXOs to cover the reservation amount.

core/account: cache UTXOs in reserver

---

cmd/cored/dev.go
cmd/cored/main.go
cmd/cored/prod.go
core/core.go
core/coreunsafe/reset.go

When determining whether cored is in "production" mode, there is
some confusion between the build tags "prod" and "buildTag". This
commit uses "prod" to determine production status, which frees
"buildTag" to convey version information for official releases.

cmd/cored: use 'prod' tag to determine production mode

---

core/account/reserve.go

Since the findMatchingUTXOs function only returns new UTXOs, any UTXOs
identified in the cache should be retried in a reservation attempt.

core/account: fix paged reservation

---

core/account/accounts.go
core/account/reserve.go
core/account/reserve_test.go
core/pin/pin.go

This maintains the ability to grab only new UTXOs while introducing the ability to skip a database query altogether by seeing if any additional work has been done.

core/account: use pin for paging utxos

---

docker/ci/Dockerfile
docker/ci/bin/java-tests
docker/ci/bin/ruby-tests
docker/ci/bin/setup-core
wercker.yml

This commit adds a third, concurrent pipeline to
the wercker testing environment. The ruby tests
are run in a separate container with a fresh core.

wercker.yml: add ruby integration tests

---

sdk/java/src/main/java/com/chain/api/Transaction.java

4e503a6dffd53dc2f2d5a735d892507323f5f9fa moved the TTL param
from actions to the tx level. While the SDK was updated to expose this
param to the user, the action level setters were never removed. Each
setter is effectively a noop and can be removed.

sdk/java: remove action level ttl setters

---

protocol/bc/transaction.go
protocol/bc/transaction_test.go

The AssetAmount and Outpoint WriteTo functions were previously declared
on raw structs. Each call to these functions would cause an allocation.
In a recent run of benchcore these two function calls collectively
allocated 4.5% of all objects.
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkAssetAmountWriteTo-8     65.5          38.8          -40.76%
BenchmarkOutpointWriteTo-8        69.0          37.4          -45.80%
benchmark                         old allocs     new allocs     delta
BenchmarkAssetAmountWriteTo-8     1              0              -100.00%
BenchmarkOutpointWriteTo-8        1              0              -100.00%
benchmark                         old bytes     new bytes     delta
BenchmarkAssetAmountWriteTo-8     48            0 …
```

protocol/bc: use pointers for func receivers

---

cmd/benchcore/main.go

Provide different EC2 instance types and update the current
Postgres configuration to use I/O-optimized EC2 instances.
This also allows us to get rid of the EBS-mounted volume because the
storage-optimized instances come with adequate storage already.
Instead of using `-instance m4.16xlarge`, you use `-config max`.

cmd/benchcore: use different instance types

---

database/pg/query.go

Rather than allocating new slices for each row in the results, the slices
can be emptied and reused.

database/pg: reuse slices in ForQueryRows

---

core/account/indexer.go
core/account/reserve_test.go
core/migrate/data.go
core/schema.sql

Delete unused columns of the account_utxos table.
Delete the old account_utxos indexes and replace with one tailored
specifically for the reservation query. There are only three non-INSERT
queries we perform against the table:
```
DELETE FROM account_utxos
WHERE (tx_hash, index) IN (SELECT unnest($1::text[]), unnest($2::integer[]))
```
```
SELECT tx_hash, index, amount, control_program_index, control_program
FROM account_utxos
WHERE account_id = $1 AND asset_id = $2 AND confirmed_in > $3
```
```
SELECT account_id, asset_id, amount, control_program_index, control_program
FROM account_utxos
WHERE tx_hash = $1 AND index = $2
```
The exact UTXO lookups are already covered by the table's primary key.
We only need one additional index for the 2nd query. This change brings
the 2nd query's query …

core/migrate: audit account_utxos indexes

---

core/migrate/data.go
core/schema.sql

The `annotated_txs.data` index was using a regular jsonb GIN index. We
should use the smaller and faster `jsonb_path_ops` specific to the
`@>` contains operator. The other jsonb indexes are already correctly
using `jsonb_path_ops`.
This provides a modest improvement to the `annotated_txs` insert query
too because there's less data to write for this index:
Total Minutes: 3.791963
Average MS: 360.567044
vs
Total Minutes: 4.384654
Average MS: 414.951517

core/migrate: use jsonb_path_ops

---

protocol/validation/tx.go

The state.OutputKey function should be preferred over
state.OutputTreeItem where the value hash isn't needed. It avoids
unnecessarily serializing the output commitment.

protocol/validation: use state.OutputKey for deleting

---

protocol/patricia/patricia.go
protocol/patricia/patricia_test.go

Previously, to avoid bugs, nodes in the tree computed their hash on
insert and delete. With a large number of inserts and deletes, this
duplicates a large amount of work.
```
benchmark              old ns/op     new ns/op     delta
BenchmarkInserts-4     142224708     36920148      -74.04%
benchmark              old allocs     new allocs     delta
BenchmarkInserts-4     283501         283499         -0.00%
benchmark              old bytes     new bytes     delta
BenchmarkInserts-4     17648974      15540852      -11.94%
```

protocol/patricia: only hash nodes on demand

---

bin/build-cored-release

build-cored-release compiles or cross-compiles cored and corectl
at the specified ref. Its main use case is within automated build
scripts that generate installer packages.
Usage is as follows:
```
build-cored-release <releaseRef> <outputPath>
```
- releaseRef must be a valid git ref in the locally-cloned repo.
- outputPath must be a valid absolute or relative directory.
The buildTag build variable is set to releaseRef.
Optional parameters are specified via environment variables:
- GOOS
- GOARCH
- DATE: a value for the buildDate build variable. By default, the current time
is used.

cmd/build-cored-release: new command

---

cmd/benchcore/main.go
core/account/accounts.go
core/asset/asset.go

Use singleflight for asset lookups and bump the size of the asset
and account caches. In one 500,000 transaction benchmark, there were
~600,000 asset lookups. This reduces it to ~50,000 asset lookups.
Also, now we have less contention for DB connections and can reduce our
max connections.

core/asset: use singleflight for lookups

---

bin/build-cored-release

The ERR signal is specific to bash. This script
fails to run on systems without bash installed.

bin/build-cored-release: use bash interpreter

---

core/migrate/data.go
core/schema.sql
core/transact.go
core/transact_test.go

* Split the submitted_txs insert/select into two separate queries. In the vast
majority of calls, only the insert should be needed.
* Rename tx_id to tx_hash to match other tables (ex, annotated_txs,
annotated_outputs, account_utxos).
* Convert tx_hash from text to bytea.

core: tweak submitted_txs

---

protocol/bc/hash.go
protocol/bc/transaction.go
protocol/bc/txinput.go
protocol/bc/txoutput.go
protocol/state/outputs.go
protocol/validation/tx.go

This allows for more finely controlled allocations, and serves as
preparation for future updates where byte buffers can be reused.

protocol/bc: take a writer instead of returning bytes

---

encoding/bufpool/bufpool.go
protocol/bc/block.go
protocol/bc/txinput.go
protocol/bc/txoutput.go

Many of the allocations in the protocol package come from creating byte
buffers. These buffers can use sync.Pool to reduce allocations.
In a recent run of benchcore, TxInput.writeTo and
OutputCommitment.writeTo in particular had many allocations from
initializing byte buffers.

encoding/bufpool: add bytes.Buffer pool

---

protocol/prottest/tx.go
protocol/prottest/tx_test.go

Add a new prottest function to create valid, signed issuance
transactions. This can be useful in tests that require valid
transactions but don't need to control the contents of the
transactions.

protocol/prottest: add NewIssuanceTx

---

protocol/patricia/patricia.go

Passing the raw hash allocates a new hash on every call to insert, which
is itself a recursive call. In a recent run of benchcore, insert
accounted for ~3% of all allocations, about half of which were from
passing the raw hash.
```
benchmark              old ns/op     new ns/op     delta
BenchmarkInserts-8     29747152      26422206      -11.18%
benchmark              old allocs     new allocs     delta
BenchmarkInserts-8     283503         161759         -42.94%
benchmark              old bytes     new bytes     delta
BenchmarkInserts-8     15546252      11647064      -25.08%
```

protocol/patricia: use pointer instead of raw hash

---

protocol/bc/txinput.go
protocol/bc/txoutput.go

Sometimes function calls can cause allocations when they are on raw
structs instead of pointers. All functions in the bc package have been
changed to use a pointer unless they need to be on raw structs.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkTxWriteToTrue200-8         260925        217921        -16.48%
BenchmarkTxWriteToFalse200-8        271812        231314        -14.90%
BenchmarkTxInputWriteToTrue-8       822           659           -19.83%
BenchmarkTxInputWriteToFalse-8      901           763           -15.32%
BenchmarkTxOutputWriteToTrue-8      549           486           -11.48%
BenchmarkTxOutputWriteToFalse-8     551           447           -18.87%
benchmark                           old allocs     new allocs   delta …
```

protocol/bc: use pointer receivers

---

protocol/bc/transaction.go
protocol/validation/merkle.go

Avoid unneccessary allocs in CalcMerkleRoot by using a pool of sha3
hashers and writing directly to the hasher instead of an intermediary
byte slice.
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkValidateBlock-4      212996        206962        -2.83%
BenchmarkCalcMerkleRoot-4     53375679      46489514      -12.90%
benchmark                     old allocs     new allocs     delta
BenchmarkValidateBlock-4      115            113            -1.74%
BenchmarkCalcMerkleRoot-4     115036         90009          -21.76%
benchmark                     old bytes     new bytes     delta
BenchmarkValidateBlock-4      8183          7064          -13.67%
BenchmarkCalcMerkleRoot-4     13860092      3212794       -76.82%
```

protocol/validation: optimize CalcMerkleRoot

---

protocol/patricia/patricia.go
protocol/patricia/patricia_test.go

Use pointers to child node's hashes instead of copying the hash when
computing a parent's hash.
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkInserts-4             31313382      30315774      -3.19%
BenchmarkInsertsRootHash-4     46718420      39971009      -14.44%
benchmark                      old allocs     new allocs     delta
BenchmarkInserts-4             161755         161755         +0.00%
BenchmarkInsertsRootHash-4     201784         171776         -14.87%
benchmark                      old bytes     new bytes     delta
BenchmarkInserts-4             11642779      11642829      +0.00%
BenchmarkInsertsRootHash-4     12932730      11970821      -7.44%
```

protocol/patricia: avoid allocs in node.Hash

---

protocol/bc/transaction.go
protocol/bc/txinput.go
protocol/bc/txoutput.go
protocol/validation/merkle_test.go

Rather than declaring WitnessHash on TxData, which needs to compute its
hash, declare it on Tx, which has a precomputed hash already available.
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkCalcMerkleRoot-8     38432421      22408414      -41.69%
benchmark                     old allocs     new allocs     delta
BenchmarkCalcMerkleRoot-8     85011          45001          -47.06%
benchmark                     old bytes     new bytes     delta
BenchmarkCalcMerkleRoot-8     2814474       1441447       -48.78%
```

protocol/bc: use precomputed hash in WitnessHash

---

cmd/benchcore/main.go

When we got rid of some noise from the Postgres logs of one of our
benchmarks, I noticed these log statements:
```
2016-11-30 01:58:50.302 UTC,,,6515,,583e2dcb.1973,21,,2016-11-30
01:39:23 UTC,,0,LOG,00000,"checkpoints are occurring too frequently (19
seconds apart)",,"Consider increasing the configuration parameter
""max_wal_size"".",,,,,,,""
2016-11-30 01:59:10.443 UTC,,,6515,,583e2dcb.1973,22,,2016-11-30
01:39:23 UTC,,0,LOG,00000,"checkpoints are occurring too frequently (20
seconds apart)",,"Consider increasing the configuration parameter
""max_wal_size"".",,,,,,,""
2016-11-30 01:59:28.654 UTC,,,6515,,583e2dcb.1973,23,,2016-11-30
01:39:23 UTC,,0,LOG,00000,"checkpoints are occurring too frequently (18
seconds apart)",,"Consider increasing the configuration parameter …
```

cmd/benchcore: bump max_wal_size

---

core/account/builder.go
core/txbuilder/actions.go

Previously, some actions validated the presence of required fields while
others did not. This adds consistent validation of required fields
across all actions.

core: validate field presence on all actions

---

cmd/cored/main.go
core/core.go
docs/internal/api-spec.swagger.yml

This commit exposes the most recent release version of `cored` via the /info endpoint.
The version string reported by the API takes on slightly differing formats depending on the build tag:
- `MAJOR.MINOR.BUILD`: if the build tag begins with `cmd.cored-`. This prefix denotes an official release.
- `MAJOR.MINOR.BUILD-<build tag>`: if any other non-blank build tag was provided
- `MAJOR.MINOR.BUILD-dev`: if the build tag is empty
This commit also moves the canonical `cored` version from Git tags to a value in the source itself. While this denormalizes the version across Git tags and the source code (worth nothing: this condition is shared by all other releasable packages, such as SDKs and installers), it means that `cored` version updates can be tracked reliably using Git history. Moreover, …

cmd/cored: use fixed version string for cored and expose via API

---

dashboard/src/features/core/components/Index/Index.jsx
dashboard/src/features/core/reducers.js

This commit replaces the build commit display with a version display, which is much more friendly to the user.

dashboard: expose version in core status page

---

encoding/bufpool/bufpool.go

It was not clear before that byte slices from pooled buffers could not
escape the caller, so the comment has been updated to emphasize that.
Additionally, a convenience function has been added that returns an
escape-safe byte slice.

encoding/bufpool: add CopyBytes

---

protocol/validation/bench_test.go

On my machine:
```
BenchmarkValidateTx-8   	   10000	    141048 ns/op
```

protocol/validation: benchmark CheckTxWellFormed

---

core/api.go

If the Core is unconfigured, Submitter will be nil. Instead, wrap the
Submit call in a closure so that if the Core is unconfigured, we won't
try to access the Submitter's Submit method until we're processing a
request (and we shouldn't then either because requests will
be caught by the needConfig middleware).
The bug was introduced in #316.

core: fix Handler.init when unconfigured

---

protocol/bc/txinput.go

I noticed we aren't calling these functions anywhere any more

remove dead code

---

core/account/builder_test.go
core/api_test.go
core/coretest/fixtures.go
core/txbuilder/txbuilder_test.go
core/txdb/txdb_test.go
protocol/block_test.go

Replace uses of:
```
t.Log(errors.Stack(err))
t.Fatal(err)
```
with:
```
testutil.FatalErr(t, err)
```

all: use testutil.FatalErr

---

core/txbuilder/finalize_test.go

Two of the benchmarks in txbuilder hadn't been updated in a long time (one of them hadn't been touched in a year). This brings them up to date so that they can actually run again!

core/txbuilder: fix benchmarks

---

core/account/builder.go
core/account/builder_test.go
core/asset/builder.go
core/txbuilder/actions.go
core/txbuilder/builder.go
core/txbuilder/txbuilder.go
core/txbuilder/txbuilder_test.go
core/txbuilder/types.go

Remove the maxTime parameter from the Build method on the Action
interface. Instead, provide a `MaxTime` method on the `TemplateBuilder`.
Also, changes `RestrictMinTimeMS` to `RestrictMinTime` so that both
min and max times operate on time structs.

core/txbuilder: remove maxTime Build parameter

---

cmd/cored/main.go
core/generator/block.go
core/generator/generator.go
core/generator/generator_test.go
protocol/block.go
protocol/mempool/mempool.go
protocol/sort.go

Collect pending transactions on the generator struct instead of a
separate type. Since Generator now implements the `txbuilder.Submitter`,
we can incrementally build blocks as new transactions are submitted.
The protocol/mempool type still exists for tests.
Future work:
* use generator.Generator in core/ tests where possible
* move protocol/mempool type into protocol/prottest
* incrementally build blocks as transactions are submitted

core/generator: collect pool txs on Generator

---

core/account/accounts.go
core/account/accounts_test.go
core/accounts.go
core/api_test.go
core/asset/annotate_test.go
core/asset/asset.go
core/asset/asset_test.go
core/asset/block_test.go
core/assets.go
core/coretest/fixtures.go
core/hsm_test.go
core/query/query_test.go
core/signers/signers.go
core/signers/signers_test.go
core/transact_test.go
core/txbuilder/finalize_test.go
core/txfeed/txfeed.go
core/txfeed/txfeed_test.go
core/txfeeds.go

This is in preparation for moving to GRPC--there are no pointers (only strings) in protobufs.

core: use strings instead of string pointers for client tokens

---

cmd/cored/main.go
core/config/config.go
core/core.go

`/info` no longer returns JSON for `version`, `buildDate` and `buildCommit` (another pre-req for GRPC).

core: store info vars on config

---

wercker.yml

For reasons not yet fully understood, Wercker only intermittently
fails on lint errors on the dashboard source. The issue appears
connected to using a cached node_modules folder (this feature is
enabled by the inz/step-npm-install Wercker plugin). If this
cache is disabled, linter errors will appear consistently.
Caching node_modules is necessary for a smooth workflow, so we'll
disable automated linting for now, since it currently only serves
to intermittently fail other folks' PRs with irrelevent liting
errors.
As a fallback, we will make sure the team is diligent about self-linting
as they work. We're also planning to add a call to eslint from
bin/bundle-dashboard, so there is at least some form of
automated sanity-check.

wercker.yml: disable flaky dashboard linting in CI

---

cmd/multitool/multitool.go
core/asset/asset.go
core/asset/block.go
core/asset/block_test.go
core/asset/builder.go
core/txbuilder/txbuilder_test.go
docs/protocol/specifications/data.md
encoding/blockchain/blockchain_test.go
protocol/bc/asset.go
protocol/bc/asset_test.go
protocol/bc/hash.go
protocol/bc/transaction.go
protocol/bc/transaction_test.go
protocol/bc/txinput.go
protocol/bc/txoutput.go
protocol/block_test.go
protocol/prottest/tx.go
protocol/tx_test.go
protocol/validation/merkle_test.go
protocol/validation/tx_test.go
protocol/vm/introspection_test.go
protocol/vm/vm_test.go

This change does two things:
1. **Removes asset version from Asset ID** to allow compatibility of the AssetIDs with future output types in the future protocol versions. Security of non-upgraded clients should not be affected as they already verify balancing rule, therefore, preventing unaccounted transfer of assets from the old entries to the new ones.
2. **Moves asset definition from the issuance program into its own field in the issuance input**. So we no longer have clumsy `<data> DROP <actual code>` issuance programs, have an explicit asset definition field in the issuance input and, as a result, support serialization flags for asset definition just like for the rest of the reference data.
This is a part of a package of breaking changes in P1: https://github.com/chain/chain/issues/239

protocol: streamline asset ID definition

---

core/account/builder_test.go
core/txbuilder/builder.go
core/txbuilder/txbuilder.go

More prep for gRPC--we used to pass the txdata struct around inside of the txtemplate because we could rely on the marshal function of txdata.

core/txbuilder: build returns tx data along with template

---

cmd/corectl/main.go
cmd/cored/main.go
core/config/config.go
core/core.go

When MaxIssuanceWindow was a time.Duration it was difficult to configure through an API call; now it accepts values like "12h." 
This will change when we switch to gRPC, but for now, this is nice.

core/config: make MaxIssuanceWindow a json.Duration

---

docs/core/get-started/sdk.md
sdk/ruby/README.md
sdk/ruby/chain-sdk.gemspec

The Ruby SDK makes use of language features only available in
Ruby 2.1, so the documentation should reflect this.
Resolves #358.

all: revise Ruby requirement from 2 to 2.1

---

core/txbuilder/builder.go
core/txbuilder/finalize.go
core/txbuilder/txbuilder.go
core/txbuilder/types.go
core/txbuilder/witness.go
protocol/bc/transaction.go
protocol/bc/transaction_test.go
protocol/tx_test.go
protocol/validation/tx.go
protocol/vm/vm.go

gRPC requires that we specify the int type; on the signing path we chose uint32s.

core/txbuilder: turn ints into uint32s on signing path

---

core/coretest/fixtures.go
core/hsm.go
core/hsm_test.go
core/txbuilder/txbuilder.go
core/txbuilder/txbuilder_test.go
core/txbuilder/witness.go
core/txbuilder/witness_test.go

Rather than working with strings, these functions can work with the keys
themselves, and leave conversion to the request layer.

core/txbuilder: replace string keys with XPubs

---

core/account/accounts.go
core/account/accounts_test.go
core/accounts.go
core/asset/annotate_test.go
core/asset/asset.go
core/asset/asset_test.go
core/asset/block_test.go
core/assets.go
core/coretest/fixtures.go
core/hsm_test.go
core/migrate/data.go
core/schema.sql
core/signers/signers.go
core/signers/signers_test.go

Rather than dealing with string types and converting back and forth
between hex, the raw bytes can be used directly.

core/signers: change xpubs column type to bytea

---

core/account/indexer.go
core/account/reserve_test.go
core/asset/annotate.go
core/asset/annotate_test.go
core/asset/asset.go
core/asset/asset_test.go
core/asset/block.go
core/migrate/data.go
core/query/index.go
core/schema.sql
core/txdb/txdb_test.go
protocol/bc/hash.go

Replaces all the hash columns in the database that use text with ones
that use bytea.

core: use bytea for hash columns

---

encoding/blockchain/blockchain.go
encoding/blockchain/blockchain_test.go
protocol/bc/block.go
protocol/bc/transaction.go
protocol/bc/txinput.go
protocol/bc/txoutput.go

Use the new functions throughout `protocol/bc`.

encoding/blockchain: Encapsulate "varstrlist" and "extensible string" patterns

---

core/assets.go

Current implementation uses default base64 encoding that's inconsistent with use elsewhere (e.g. https://github.com/chain/chain/blob/27e2c5af0195d71aba8837e7e04fadf2ffbd2069/core/asset/block.go#L36). This change ensures hex-encoding for the issuance program in the "createAsset" response.

core/assets: createAsset response encodes IssuanceProgram in hex

---

net/http/limit/limit.go

Rather than having the limit functionality contained in handler, it is
moved to a separate struct. This is helpful for allowing other protocols
to use limiters.

net/http/limit: extract limit functionality

---

protocol/bc/outputcommitment.go
protocol/bc/txoutput.go

Part of #349. 
Note that this simply splits out `OutputCommitment` without making some of the other changes to the output commitment that are included in 349.

protocol/bc: move OutputCommitment into its own file

---

protocol/bc/transaction.go
protocol/bc/transaction_test.go
protocol/bc/txinput.go
protocol/block.go
protocol/recover_test.go
protocol/validation/block.go
protocol/validation/merkle.go
protocol/validation/merkle_test.go

This trickles down to `CalcMerkleRoot` as well. Part of #349.

protocol/bc: return errors from WitnessHash functions

---

protocol/bc/issuance.go
protocol/bc/spend.go
protocol/bc/txinput.go

Part of #349. In 349, there are other changes to both `IssuanceInput` and `SpendInput`, but I don't make those changes here.

protocol/bc: new files for TypedInputs

---

Readme.md
bin/lbc
bin/run-tests
docker/ci/Dockerfile
docker/ci/bin/core-tests
docker/ci/bin/setup-core
docker/testbot/startup.sh
docker/testbot/tests.sh

Starting in Go 1.8, it is possible to install and use Go
without setting GOPATH. Several of our shell scripts and
instructions assume that GOPATH is set (almost always to
determine the location of installed executables), but
this assumption will become invalid soon. (And I think
it's unreasonable to impose setting GOPATH as an extra
requirement just for our environment.) We can fix this
by calling 'go env GOPATH', which prints the computed
value of GOPATH (either the string the user set, or the
default, which happens to be $HOME/go in Go 1.8).

all: don't require GOPATH to be set

---

core/accounts.go
core/assets.go
core/query.go
core/query/accounts.go
core/query/assets.go
core/query/outputs.go
core/query/outputs_test.go
core/query/transactions.go

Rather than unmarshaling from the database into a struct or map
and then doing conversion at the request layer before sending a
response to the client, just leave the unmarshaling to the request
layer, where it can guarantee ordering.

core/query: leave unmarshaling to request layer

---

core/pin/pin.go

If a block processor's callback fails to process a block, include the
corresponding pin's name in the error log.

core/pin: log errors with corresponding pin

---

core/transact.go
sdk/java/src/test/java/com/chain/integration/FailureTest.java

Previously, we correctly checked for a null `raw_transaction` on a
template, and returned a descriptive error. But higher in the call
stack we'd try to wrap the error with the transaction hash. Trying
to call Hash() on the nil transaction would panic.
Fixes #405.

core: handle null raw_transactions

---

docker/ci/Dockerfile

Unfortunately, it turns out that docker's ENV instruction cannot run
commands. As such, in this one area it is better to use simple variables
rather than `go env GOPATH`.

docker/ci: fix CHAIN env variable

---

sdk/java/src/main/java/com/chain/api/BaseQueryBuilder.java
sdk/java/src/main/java/com/chain/api/Query.java
sdk/java/src/test/java/com/chain/integration/QueryTest.java

Some filter parameters cannot be represented as strings.

sdk/java: use list of objects for filter params

---

docker/ci/Dockerfile
wercker.yml

Protobuf 3.1 is not added until alpine 3.5, so that repository has to
be added to the list to get it. Additionally, protobuf was compiled
using glibc, but alpine by default only has musl. A third party
maintains an alpine package providing glibc.
A patch that allows protobuf to be compiled with musl has already been
merged, and should be available at the next release of protobuf. At that
time, glibc should be removed from this build.

docker/ci: add protobuf to ci build

---

core/migrate/data.go
core/schema.sql

Drop the `mutable_definition` column from the assets table. We don't
allow mutable asset definitions. This column is never read and is always
set to the default.

core/asset: drop 'mutable_definition' column

---

core/txbuilder/witness.go

Working on improving TransferWithBlocks, and this is a tiny fix. 
Before
```
BenchmarkTransferWithBlocks-4   	     200	  31896144 ns/op	   61624 B/op	     919 allocs/op
```
After
```
BenchmarkTransferWithBlocks-4   	     300	  25861102 ns/op	   67099 B/op	     913 allocs/op
```

core/txbuilder: improve signature witness signing perf

---

core/txdb/txdb_test.go
encoding/blockchain/blockchain.go
encoding/blockchain/blockchain_test.go
protocol/bc/block.go
protocol/bc/block_commitment.go
protocol/bc/block_witness.go
protocol/bc/output_commitment.go
protocol/bc/sighasher.go
protocol/bc/spend.go
protocol/bc/transaction.go
protocol/bc/txinput.go
protocol/bc/txoutput.go
protocol/block.go
protocol/block_test.go
protocol/recover_test.go
protocol/validation/block_test.go
protocol/vm/introspection_test.go
protocol/vm/vm_test.go

Remove the `all` parameter from `ReadExtensibleString`, which now always returns the unconsumed suffix. `WriteExtensibleString` now takes a suffix to always append.
Types with fields parsed from an extensible string now also store the unrecognized suffix to add back when writing.
Block commitment and witness types are moved to their own files, for improved clarity.
Closes https://github.com/chain/chain/issues/366 - unrecognized extensible string suffixes were being dropped

encoding/blockchain: save and restore unconsumed extensible-string suffixes

---

core/query/filter/scanner_test.go

Add unit tests for the filter scanner. Increase test coverage before
we add unicode support.

core/query/filter: unit test the scanner

---

core/account/accounts.go
core/account/accounts_test.go
core/account/builder.go
core/account/builder_test.go
core/account/indexer.go
core/account/receivers.go
core/account/receivers_test.go
core/api.go
core/control_programs.go
core/coretest/fixtures.go
core/migrate/data.go
core/receivers.go
core/schema.sql
core/txbuilder/builder.go

Add a create-account-receiver endpoint to create expiring control
programs. By default, a receiver expires in 30 days. Control programs
created through the create-control-program rpc do not expire.
Control programs created automatically during transaction building
are created with the transaction's max time as an expiration.
The expiration is only considered to be elapsed once the Core ingests a
block with a timestamp greater than the control program's expiration.
This allows us to use a transaction's max time as the control program's
expiry without worrying about clock skew. Once the expiration has
elapsed, the control programs are deleted and forgotten.
If any assets are sent to an expired control program, the Core will not
index them (so they will not be spendable) or annotate them as …

core/account: introduce receivers

---

core/query/filter/parser_test.go
core/query/filter/scanner.go
core/query/filter/scanner_test.go
core/query/query_test.go

Support UTF-8 characters in strings and identifiers. This does _not_ add
escaping for strings or identifiers so `'` and `\` are still illegal
characters in strings. Any non-alphanumeric characters are still
illegal in identifiers.
Token positions are reported using the byte offset of the beginning of
the token. To retrieve the code point offset, the consumer of the package
can use `utf8.RuneCount(src[:offset])`.

core/query/filter: add unicode support

---

core/query/annotated.go
core/query/index.go
docs/internal/api-spec.swagger.yml
sdk/java/src/main/java/com/chain/api/Transaction.java
sdk/java/src/test/java/com/chain/integration/TransactionTest.java
sdk/ruby/lib/chain/transaction.rb

This addresses https://github.com/chain/chain/issues/439
1. TxInputs have `spent_output{transaction_id,position}` struct side by side with `spent_output_id`.
2. Support for this struct is returned to Java and Ruby SDKs. NodeSDK is unchanged because it was implicitly forwarding JSON results as is to the user.
3. Annotation done by batch collection of a mapping `outputid -> outpoint` for all transactions in a block.
4. OutputID is not queried from DB, but instead computed from Outpoint. This adds extra hashing overhead per input, but reduces DB traffic by ≈50% (33 bytes vs 65 bytes per input). **Not sure if it's the right call, so please advise!**
PTAL @kr @jeffomatic @jbowens

core/query: restore outpoint annotation in txinputs

---

bin/upload-docs
docs/README.md

We're noticing that the `main` branch is not always the appropriate source for our online documentation, because it often contains updates to the source docs that reflect changes that haven't been released yet. Therefore, this commit proposes a new `docs-release` branch that is prepared ad hoc before documentation is uploaded to our public website.

docs: update deploy instructions

---

docs/core/reference/versioning.md

This commit updates the official versioning language in two
significant ways:
- Core and signer versioning are no longer separate. Since core
components interact directly with signer components, their
interfaces should fall under the same versioning umbrella.
- Pre-existing language around version "tolerance" has been
simplified to the guarantee that server packages are backward
compatible with clients that are at most one minor version
behind. This provides for a reasonable upgrade flow between
the Chain Core server and client apps.
There are also minor language tweaks, mostly for brevity and
clarity.

docs/core/reference: clarify versioning language

---

protocol/bc/block_commitment.go
protocol/bc/transaction.go
protocol/bc/transaction_test.go
protocol/bc/txinput.go
protocol/bc/txoutput.go
protocol/block_test.go
protocol/validation/merkle.go
protocol/validation/merkle_test.go

The merkle tree is now computed from transaction hashes. This is preparatory to landing the code in https://github.com/chain/chain/tree/txgraph

protocol/bc: do away with witness hashes

---

cmd/cored/dev.go
cmd/cored/main.go
cmd/cored/prod.go
core/api.go
core/config/config.go
core/core.go
core/errors.go
core/hsm.go
core/hsm_test.go

Disable the reset and mock HSM endpoints in production. The reset code
won't even be included in the binary in production, but the API endpoint
should also be disabled.

core: disable some endpoints in production

---

core/migrate/data.go
core/schema.sql
core/txdb/snapshot.go

After saving a new snapshot, delete older snapshots.
We could change the snapshots table to be a singleton table, but the
/get-snapshot RPC uses content-addressable snapshots. There would be
a race condition between when a client looks up the height of the
most recent snapshot and when they retrieve that snapshot.
There might be other motivations for keeping more snapshots
than just the most recent snapshot?

core/txdb: delete older snapshots

---

core/account/indexer.go
core/accounts.go
core/asset/annotate.go
core/asset/annotate_test.go
core/asset/asset.go
core/asset/block.go
core/asset/block_test.go
core/assets.go
core/query.go
core/query/accounts.go
core/query/annotated.go
core/query/assets.go
core/query/index.go
core/query/query_test.go

Add typed structs for annotated accounts and annotated assets instead of
using a freeform `map[string]interface{}`. This will be helpful when
replacing the jsonb `data` columns with a structured schema.
Finishing up the work from #407.

core/query: define annotated accounts & assets

---

core/migrate/data.go
core/schema.sql

The PostgreSQL index on `annotated_outputs.(tx_hash, outpoint_index)` existed for a single query that marked consumed outputs as spent. Ever since #421, we've used a query against the output ID for that. There's already an index on output ID.

core/query: drop outpoint index

---

core/generator/generator_test.go
protocol/validation/block.go
protocol/validation/tx.go
protocol/vm/control.go
protocol/vm/crypto_test.go
protocol/vm/introspection_test.go
protocol/vm/numeric_test.go
protocol/vm/vm.go
protocol/vm/vm_test.go

Instead of returning an `ok` bool and an error, fold the `!ok` case into the error by returning the new value `ErrFalseVMResult`.

protocol/vm: simplify vm interface

---

sdk/java/pom.xml

This commit adds all necessary tags for releasing the Java SDK
to Maven.
To deploy to Maven, ensure your $HOME/.m2/settings.xml contains
the tags described here:
https://gist.github.com/jeffomatic/e6b3c23799e9586698ca466e2765916b
Then run:
```
cd sdk/java
mvn clean deploy -DskipTests=true
```

sdk/java: update pom.xml for Maven deploys

---

protocol/tx/entry.go

```
benchmark                     old ns/op     new ns/op     delta
BenchmarkHashEmptyTx-8        13705         5998          -56.23%
BenchmarkHashNonemptyTx-8     56714         28370         -49.98%
```

protocol/tx: replace a call to io.CopyN with a fixed-length read and write

---

docs/core/get-started/sdk.md

- Add Java Gradle instructions
- Move version compatibility language to the top of the doc
- Add table of contents
- Simplify verbiage

docs/core/get-started: clean up language on SDK page

---

docs/core/get-started/sdk.md

While Maven Central Repository is technically maintained by Sonatype, this detail is strictly TMI and adds nothing to the SDK download page.

docs/core/get-started: remove superfluous mention of Sonatype

---

bin/generate-docs

Since the Java SDK is now hosted on Maven, there is no need to
include the release in Chain Core itself. This is a nice reduction
in the size of the Chain Core binary.

bin: remove Java SDK jar from bundle-docs flow

---

core/api.go

Increase the max request size from 1MB to 10MB. It's pretty common for
people to run into this. Requests can grow unexpectedly large from:
* using batching to submit multiple transactions at once
* spend actions being satisfied using many small outputs
* large reference data objects or large asset definitions
* our JSON wire format with hex-encoded raw transactions
When testing locally, I hit the 1MB limit signing a single transaction
with ~750 issuances, ~750 outputs and a small amount of json metadata
on each issuance (in the asset definition).

core: up max request size to 10MB

---

sdk/java/src/main/java/com/chain/http/Client.java

Allow the Java SDK Client to be configured with multiple cored or
signerd URLs for high availability in the absence of a load balancer.

sdk/java: accept multiple URLs in Client

---

core/api.go
core/transact.go

Fix build-transaction leader-forwarding to use an `interface{}` instead
of a `map[string]interface{}` (fixing #487). Also, remove an unnecessary
extra pointer indirection in `forwardToLeader`.

core: fix leader forwarding

---

protocol/tx/data.go
protocol/tx/spend.go

protocol/tx: return more specific types from newData and newSpend

---

core/account/receivers.go
core/api.go
core/txbuilder/actions.go
core/txbuilder/builder.go
core/txbuilder/types.go

Add a transaction-building action to control assets with a Receiver.

core/txbuilder: add `control_receiver` action

---

core/http.go
errors/stack.go

When recovering a panic in a batch endpoint, wrap the panic with the
stack trace. Otherwise, the reported panic doesn't include a stack trace
and can be difficult to debug. Also, bump the number of frames that we
collect.

core: wrap batch panics with stack trace

---

core/query.go
core/query/accounts.go
core/query/assets.go
core/query/balances.go
core/query/balances_test.go
core/query/filter/parser.go
core/query/filter/sql.go
core/query/filter/sql_test.go
core/query/filter/typecheck.go
core/query/filter/typecheck_test.go
core/query/outputs.go
core/query/outputs_test.go
core/query/query_test.go
core/query/transactions.go
core/query/transactions_test.go
core/txfeed/txfeed.go

Use the SQL table definitions to typecheck filter predicates more
exhaustively. Also, when possible, infer the type of arbitrary
json values so that we can cast them to the correct PostgreSQL
value.
For example, if you run the filter:
```
asset_definition.priority = 10
```
The type checker will infer that `asset_definition.priority` is an integer
and the resulting SQL will be:
```sql
(tbl."asset_definition"->>"priority")::bigint = 10::bigint
```
This also allows for queries to access boolean values in reference data.
For example, this is now a valid query:
```
asset_definition.is_dollar
```
Booleans that are exposed in the JSON as "yes"/"no" still need to be
compared as strings until we have a backwards compatible way of
supporting both syntaxes for those fields.

core/query: use SQL table to typecheck thoroughly

---

core/blocksigner/blocksigner.go
core/config/config.go
core/query/outputs.go
core/query/transactions.go
core/txbuilder/finalize.go
errors/errors.go
errors/errors_test.go
errors/example_test.go
protocol/block.go
protocol/validation/block.go
protocol/validation/tx.go

Sub takes an existing error, which might have an associated stack trace or other metadata, and substitutes a new root error, which is sometimes necessary to return a certain error code to the client.
This change also updates all call sites I could find to use the new function.

errors: add new function Sub

---

core/coreunsafe/reset.go

Use `config.Production` instead of the more fragile expvar to protect
against a production environment.

core/coreunsafe: use config.Production

---

errors/errors.go

Using these parameter names for Sub seems to make its
behavior clearer.

errors: clarify documentation

---

sdk/ruby/chain-sdk.gemspec
sdk/ruby/lib/chain/connection.rb
sdk/ruby/spec/unit/connection_spec.rb

The Connection class does not appropriately join URL path components
when both trailing and leading slashes occur in adjacent components.
This can occur when connecting to a real HSM server and attempting to
sign.
I chose a more brute-force approach for this fix, despite the existence
of something like URI::join. The latter has issues when adjacent paths
are both relative. The fix in this commit deals with this case
correctly.

sdk/ruby: fix path joining

---

cmd/cored/main.go
core/fetch/fetch.go
core/generator/generator.go
core/generator/generator_test.go
core/leader/leader.go

This refactors the `core/leader` package and how it's used by `cmd/cored`:
* the `lead` closure is run synchronously within the `leader.Run` loop
* the global `IsLeading` value isn't updated until the `lead` closure completes
* the`cmd/cored`'s `lead` closure calls `Recover` instead of pushing the responsibility to the `core/fetch` and `core/generator` packages
* the `leader.Run` loop responsible for invoking `lead` is separated from the loop responsible for detecting leadership changes
This ensures that all leadership-only routines and code paths are guaranteed to have a recovered, current blockchain state. It also ensures that if blockchain recovery takes longer than 10 seconds, a new leader won't be demoted prematurely.
In a followup PR, we'll be able to remove …

core/leader: run lead func synchronously

---

docs/enterprise/thales-install-guide.md

@erykwalder and @kr discovered a setup command that will install the machine image in such a way that it doesn't need to be reloaded in the event of an HSM reboot.
Related: chain/chainprv#2453

docs/enterprise/thales: update machine image loading

---

cmd/cored/main.go
protocol/protocol.go
protocol/recover.go

With the changes from #497, we can now move the block processor pin
creation into the `leader.Run` closure after the blockchain is
recovered.

protocol: remove Chain.Ready

---

docs/internal/api-spec.swagger.yml

This commit attempts to update the Swagger API spec to reflect deprecations and additions to the API due to the upcoming 1.1 release. It covers the following changes:
- Addition of receivers, and deprecation of control programs as a top-level API object
- Addition of output IDs, and deprecation of txid/position pairs

docs/internal: get API spec up to date for 1.1 release

---

core/asset/asset.go
core/asset/block_test.go

Chain Core won't allow assets to be created with non-JSON asset
definitions, but a buggy Chain Core or other clients on a network
may allow it. Instead of crashing the block processor, the error
should be ignored.

core/asset: ignore non-JSON asset definitions

---

sdk/ruby/lib/chain/access_token.rb
sdk/ruby/lib/chain/account.rb
sdk/ruby/lib/chain/config.rb
sdk/ruby/lib/chain/receiver.rb
sdk/ruby/lib/chain/response_object.rb
sdk/ruby/lib/chain/transaction.rb
sdk/ruby/spec/integration/integration_spec.rb
sdk/ruby/spec/unit/response_object_spec.rb

- Refactor ResponseObject attribs to allow for safe translation and
detranslation between RFC3339 strings and Time.
- Add Receiver class
- Add create_receiver and create_receiver_batch
- Deprecate create_control_program
- Add control_with_receiver action
- Deprecate control_with_program action
- Fix deprecations on spent_output and outpoint params for
spend_account_unspent_output action

sdk/ruby: add receiver interface

---

Readme.md

Using 'go list' here does the right thing when GOPATH
has more than one directory in it. (There are still one
or two other places in this document that won't work
correctly in that scenario, but they are harder to fix.)

Readme: better support for multi-entry GOPATH

---

core/txbuilder/finalize.go
core/txbuilder/txbuilder_test.go

Should resolve #169 for real this time.

core/txbuilder: check txsighash for issuance-only txs, too

---

core/api.go
core/api_test.go
core/transact.go

Rather than having a map that is initialized at the first request,
action decoders should be available on the API at all times. This
changes the map into a function.

core: make action decoders a lookup function

---

cmd/cored/main.go
core/api.go
core/api_test.go

Rather than initializing the http handler on the first request, this
makes the creation of the handler an explicit step.

core: initialize handler before first request

---

cmd/corectl/main.go

Satisfies an old todo about checking key lengths. The mockhsm can now
generate bare ed25519 keys, so the length should be enforced.

cmd/corectl: check key length in generator config

---

cmd/corectl/dev.go
cmd/corectl/main.go
cmd/corectl/prod.go

This disables the create-block-keypair command when the prod build tag
is used. Additionally, mockhsm is not compiled into the binary when the
prod build tag is used.

cmd/corectl: disable key generation in prod

---

core/txfeed/txfeed.go

When retrieving a transaction feed by alias, an empty response
should return a CH002 error, rather than a CH000. This is resolved
by substituting sql.ErrNoRows with pg.ErrUserInputNotFound.

core/txfeed: fix not-found status code for Find()

---

protocol/bc/transaction.go
protocol/bc/txhashes.go
protocol/tx/transaction.go

All outputs should have an output id assigned, whether they are standard
outputs or retirement outputs. Since the header.body.Results field
contains only outputs, there should be no need for further filtering.

protocol/tx: assign output id for all types

---

core/query/index.go

Since the annotated_outputs table is also used for lookups on the
annotated_txs table, retired outputs should be indexed.

core/query: index retired outputs

---

docs/protocol/papers/whitepaper.md
docs/protocol/specifications/consensus.md
docs/protocol/specifications/data.md
docs/protocol/specifications/vm1.md

This makes block hash (aka "block ID") not subject to block witness malleability. 
Rationale: turns out, when the block is agreed upon in a fully decentralized manner (e.g. any BFT consensus protocol), not via a assumed-to-be-alive generator, then nodes would require another round of agreement on _which_ combination of public signatures to commit to. What's worse, alternative combinations may be propagated quicker to other nodes that must be then ready to re-assign witnesses when later blocks arrive to keep on the same blockchain. 
Removing signatures from the chain of hashes eliminates this problem. Note that other nodes consuming the chain of headers or full blocks are still required to also receive and process witness data to authenticate the chain. Each block's witness still …

docs/protocol: remove block witness from under the block ID

---

core/account/builder_test.go
core/account/indexer.go
core/account/indexer_test.go
core/coretest/fixtures.go
core/recovery_test.go
protocol/state/outputs.go
protocol/validation/tx.go
protocol/validation/tx_test.go

Turns out we no longer need to carry around the `TxOutput`.
The indexer was using the `TxOutput` in a `state.Output`, but it can get that same info elsewhere, and now does.

protocol/state: replace state.Output with bc.OutputID

---

docs/protocol/specifications/consensus.md
docs/protocol/specifications/data.md

This removes the transaction witness hash—which is no longer committed to the blockchain and no longer needs to be computed—from the spec.

docs/protocol: remove transaction witness hash

---

core/query/annotated.go
core/query/outputs.go

AnnotatedOutput'd TransactionID field is a bc.Hash, which does not have
a zero-value that will trigger the omitempty directive when serialized
to JSON. We use pointers instead to get the desired behavior.
This commit is a stopgap measure to prevent some weird behavior in the
Node SDK; namely, transaction output objects are currently returned as
strings of zeros. In the future, we can re-evaluate the API spec and decide
whether we should allow the transaction ID field to be empty in any context.

core/query: make annotated output's txid truly omittable

---

core/migrate/data.go
core/query/index.go
core/query/sql.go
core/schema.sql

These columns were forgotten in the query rewrite.
Fix #523

core/query: add spent_output, spent_output_id

---

protocol/patricia/patricia.go
protocol/patricia/patricia_test.go

There's no need for insert, delete, and lookup to be
methods on Tree. The *Tree is completely unused in the
body of those three functions (other than in the
recursive calls).

protocol/patricia: remove unused parameter

---

core/query/index.go

Fixes typo in the insert annotated outputs query.

core/query: fix typo

---

core/txdb/snapshot_test.go
protocol/patricia/patricia.go
protocol/patricia/patricia_test.go
protocol/validation/tx.go

Delete used to return ErrPrefix in one case: when the
requested key exactly matches an interior node. There
were three problems with this:
First, it didn't cover all cases where the requested key
is a prefix of an existing item. Consider the following
tree of three items (001, 010, and 011):
0             (interior node)
+-- 001       (leaf node)
+-- 01        (interior node)
+--  010  (leaf node)
+--  011  (leaf node)
Attempting to delete 01 produced ErrPrefix, but
attempting to delete 00 was a no-op, returning a nil
error. Both of those keys are prefixes of other keys in
the set.
Second, there was a bug in the recursive call. It
returned a nil node on error. This returned all the way
up the stack and caused the root node to be replaced
with nil. Thus, attempting to delete a nonexistent …

protocol/patricia: remove error case in Delete

---

sdk/ruby/lib/chain/transaction.rb

Neither of control_program and input_witness should be a property
of Transaction::Input.

sdk/ruby: deprecate superfluous tx input fields

---

protocol/patricia/patricia.go

No other package uses the value of ErrPrefix, so we can
reduce the surface area of this package by not exporting it.

protocol/patricia: un-export ErrPrefix

---

protocol/patricia/patricia.go
protocol/state/snapshot.go

The Copy function merely made a copy of the Tree
structure. Many Go structures, such as http.Request and
bytes.Buffer, are safe to copy, and patricia.Tree is
too. (In fact, one can typically assume that a Go struct
is okay to copy unless its documentation says otherwise.
See sync.Mutex for an example.) We don't need a function
just to perform this basic operation.

protocol/patricia: remove func Copy

---

docs/protocol/specifications/data.md

The Merkle Patricia Tree is only valid for a prefix-free
set. It is up to the environment applying this function
to ensure that property. The state commitment does so by
making all input elements of equal length (32 bytes).

docs/protocol/specifications: require MPTH input to be prefix-free

---

bin/jrun

This commit adds a compile flag so use of deprecated APIs
will trigger console warnings. Since jrun is used primarily to test
documentation examples, this is a really good thing!

bin/jrun: display deprecation errors

---

docs/core/examples/node/.gitignore
docs/core/examples/node/package.json

To test example files using the Node SDK, it's necessary to supply a
local package.json file. The associated node_modules folder should
be ignored.

docs/core/examples/node: add gitignore

---

docs/core/build-applications/accounts.md
docs/core/build-applications/assets.md
docs/core/build-applications/balances.md
docs/core/build-applications/batch-operations.md
docs/core/build-applications/control-programs.md
docs/core/build-applications/queries.md
docs/core/build-applications/real-time-transaction-processing.md
docs/core/build-applications/transaction-basics.md
docs/core/examples/java/Accounts.java
docs/core/examples/java/Assets.java
docs/core/examples/java/ControlPrograms.java
docs/core/examples/java/TransactionBasics.java
docs/core/examples/node/accounts.js
docs/core/examples/node/assets.js
docs/core/examples/node/controlPrograms.js
docs/core/examples/node/transactionBasics.js
docs/core/examples/ruby/accounts.rb
docs/core/examples/ruby/assets.rb
docs/core/examples/ruby/control_programs.rb
docs/core/examples/ruby/transaction_basics.rb

This commit updates the documentation so it uses receivers the first-class cross-core payment object; control programs are thusly deprecated. Both prose and code samples have been updated to educate users about receivers.

docs/core: introduce receivers

---

cmd/cored/main.go

Adds the following output on launch:
```
$ cored
Chain Core starting
* Version VERSION
* [Development|Production] mode
...
```

cmd/cored: print version string on startup

---

docs/core/get-started/install.partial.html

We'd like to use the "_Latest" suffix convention for our installer
downloads.

docs/core/get-started: rename Mac app installer

---

core/query/annotated.go

core/query: hide control program from annotated input

---

docs/protocol/specifications/data.md

Commit a7bc90d2cb47fdebed2afd734c45d4285e8406bd
mistakenly edited the Merkle Binary Tree section when it
should have edited the Merkle Patricia Tree section. The
prefix-free requirement applies to the patricia tree
construction; the traditional (binary) Merkle tree has
no such requirement.
The description from the previous commit:
The Merkle Patricia Tree is only valid for a prefix-free
set. It is up to the environment applying this function
to ensure that property. The state commitment does so by
making all input elements of equal length (32 bytes).

docs/protocol/specifications: require MPTH input to be prefix-free (redo)

---

core/account/reserve_test.go
core/txdb/snapshot.go
core/txdb/snapshot_test.go
protocol/patricia/patricia.go
protocol/patricia/patricia_test.go
protocol/validation/tx.go
protocol/validation/tx_test.go

With this change, Insert takes a single argument, the
data item to insert into the set; it no longer takes a
separate key and value. This brings the interface and
behavior up to date with the specification. We update
the package documentation and various parameter names
accordingly.

protocol/patricia: adopt set semantics (not dict)

---

cmd/testnet-reset/main.go

Currently testnet-reset assumes the host's location.
The location should be set explicitly so it is only
allowed to run at midnight PST. Currently the filter
cancels the job during valid execution times.

cmd/testnet-reset: specify host location

---

protocol/block.go
protocol/validation/block.go
protocol/validation/tx.go
protocol/validation/tx_test.go

This keeps us from having to pass an incompletely constructed block to ConfirmTx from Chain.GenerateBlock.

protocol/validation: pass only the pieces of state needed to ConfirmTx, not a whole block

---

protocol/bc/block.go
protocol/bc/txhashes.go
protocol/tx/entry.go
protocol/tx/map.go
protocol/tx/transaction.go

Also, recover from the panic inside `mapTx` and turn it back into an error.

protocol/tx: allow entryID to panic rather than return an error

---

core/account/reserve.go

Reserving UTXOs used to fetch the outpoint along with the output ID. The
outpoint is no longer used for anything.

core/account: stop loading outpoints in reserve

---

dashboard/src/utility/environment.js

The react-router basename cannot end with a slash to correctly route the root path.

dashboard: fix logo link in development

---

docs/protocol/specifications/chainkd.md
docs/protocol/specifications/data.md
docs/protocol/specifications/vm1.md

RFC 8032 has finally been published by the IETF, so we can stop citing the draft.

docs/protocol/specifications: Replace draft-irtf-cfrg-eddsa references with RFC 8032

---

docker/ci/Dockerfile

Installs Rust nightly (locked to 2017-02-25 snapshot) via Rustup:
https://www.rustup.rs/
Also installs the following development tools:
- rustfmt: Lint syntax to ensure it follows standard style (ala gofmt)
- clippy: Lint for non-idiomatic Rust or other minor mistakes
- cargo-audit: Audit Cargo.lock for crates containing security vulnerabilities

docker/ci: Add Rust tools to Dockerfile

---

errors/errors.go

Previously, nil errors were detected later in the internal wrap
function. However, most of the callers would also perform unnecessary
work before calling wrap. This changes the callers to return early if
the error is nil.

errors: immediately return on nil error

---

protocol/tx/entry_test.go

Adds benchmarks for entryID across several types of entries.

protocol/tx: add benchmarks for entryID

---

docs/internal/package-tags-branches.md

For the future, it's easiest to use hyphens for word separators
in tag names, as opposed to a mix of hyphens and periods.

docs/internal: use hyphens for all tags/branches

---

cmd/cored/main.go

In the [spirit of reducing responsibility of leader processes](https://github.com/chain/chain/issues/519#issuecomment-280741917), always
run  the goroutine to expire reservations regardless of whether
the process is leader. It's harmless to run on non-leader
processes. There won't be any reservations to expire.

cmd/cored: always run expire reservations loop

---

docker/ci/Dockerfile

This reverts commit 58c1cd0ee36aa0ee70d3bcfadff9a74ec9dccd71.
Since Alpine uses musl and Rust doesn't easily work with
musl out of the box, it'll take some more work to get
this up and running. See also #636 for some discussion.
So let's back this out for now and we can try again.

docker/ci: Revert "Add Rust tools to Dockerfile"

---

bin/build-docker-de
cmd/cored/main.go
docs/README.md
installer/mac/tools/build_chain.sh

#640 introduced a new namescheme for release tags. This change should be
reflected in build scripts and documentation.

all: update tag references to reflect new namescheme

---

Godeps/Godeps.json
Readme.md
docker/ci/Dockerfile
docker/testbot/Dockerfile
wercker.yml

We can begin taking advantage of Go 1.8 features and bug-fixes in follow-up commits. See the PR discussion for some examples.

all: update to Go 1.8

---

core/api.go

Use expvar.Handler instead of duplicating the code in expvar. The
expvar.Handler function is new in Go 1.8.

core: use expvar.Handler

---

installer/mac/tools/build_chain.sh

This is a backport of #650 for the Chain Core 1.1 Mac release.

installer/mac/tools: update build script for new tagging namescheme

---

bin/build-docker-de

This is a backport of #650 for the Chain Core 1.1 Docker release.

bin/build-docker-de: update build tag for new namescheme

---

cmd/cored/main.go

This is a backport of #650 for the Chain Core 1.1 server release.

cmd/cored: update build tag logic for new tagging namescheme

---

sdk/ruby/README.md
sdk/ruby/chain-sdk.gemspec

Due to customer requests, we are relaxing the Ruby 2.1 requirement in the Ruby SDK. A warning about Ruby 2.0 end-of-life has been added to the README.

sdk/ruby: support Ruby 2.0

---

cmd/cored/main.go
core/fetch/fetch.go

Download and store the bootstrapping snapshot before creating block
processor pins. This ensures block processors will start processing at
the right height.
This is the 1.1.x equivalent of #644. If you have any suggestions to
whittle its surface area down farther, let me know.
Fix #643.

core/fetch: bootstrap before creating pins

---

sdk/ruby/README.md
sdk/ruby/chain-sdk.gemspec

Due to customer requests, we are relaxing the Ruby 2.1 requirement in the
Ruby SDK. A warning about Ruby 2.0 end-of-life has been added to the
README.
This is a backport of #658 for the 1.0 branch of the Ruby SDK.

sdk/ruby: support Ruby 2.0 in 1.0 SDK

---

sdk/ruby/README.md
sdk/ruby/chain-sdk.gemspec

Due to customer requests, we are relaxing the Ruby 2.1 requirement in the
Ruby SDK. A warning about Ruby 2.0 end-of-life has been added to the
README.
This is a backport of #658 for the 1.1 branch of the Ruby SDK.

sdk/ruby: support Ruby 2.0 in 1.1 SDK

---

sdk/ruby/CHANGELOG.md
sdk/ruby/README.md
sdk/ruby/lib/chain/version.rb

This updates our bleeding edge, but should be backported to the `sdk-ruby-1.1.x` release branch.

sdk/ruby: tick version to 1.1.1

---

core/account/reserve_test.go
protocol/prottest/block.go

Fix the data race in TestCancelReservation caused by manipulating
the Chain's active state tree. Instead, add the output ID to the state
tree before creating the Chain.
Fixes #516.

core/account: fix race in TestCancelReservation

---

cmd/cored/main.go
core/api.go
core/config/config.go

Use https for interprocess RPCs if the current cored process was
configured with a TLS cert. This is a short-term fix for the 1.1.1
release only.
Fixes #674.

cmd/cored: support https for intra-Core RPCs

---

cmd/cored/main.go

Func init runs too early for this var to be initialized
(tlsCrt gets written during env.Parse), so config.TLS
was always getting set false.

cmd/cored: initialize TLS flag after parsing env

---

core/account/builder.go
core/account/builder_test.go
core/account/indexer.go
core/account/indexer_test.go
core/account/reserve.go
core/account/reserve_test.go
core/coretest/fixtures.go
core/migrate/data.go
core/query/annotated.go
core/query/index.go
core/schema.sql
core/txbuilder/txbuilder_test.go
core/txbuilder/witness.go
core/txbuilder/witness_test.go
protocol/bc/spend.go
protocol/bc/transaction.go
protocol/bc/transaction_test.go
protocol/bc/txhashes.go
protocol/bc/txinput.go
protocol/tx/map.go
protocol/tx/transaction.go
protocol/tx/tx_test.go
protocol/validation/tx.go
protocol/validation/tx_test.go
protocol/vm/crypto_test.go
protocol/vm/introspection_test.go
protocol/vm/vm_test.go

Spend TxInputs need to contain all of the data necessary to reconstruct
output ids in order to spend them. Performing the hashing during
validation gives us cryptographic integrity that the spent output data
is correct.
In order to preserve this data, the mapping process was updated to
return additional information which is stored in the account_utxos
table. This data is then populated in a SpendCommitment type on the
TxInput structs.
1.1-stable version of #665

protocol/bc: add SpendCommitment type

---

cmd/cored/main.go
core/account/indexer.go

This runs the expiration of account control programs as a separate
process. This fixes the expiration to wait until the transaction
processor has completed before deleting any data that may be needed.
1.1-stable version of #612

core/account: add expiration block processor

---

core/account/indexer.go
core/account/indexer_test.go

Do not delete account control programs that are expired but still hold
assets.
This is a minimal, short-term fix for #668 within the 1.1.x release branch.
In the future, we should use `account_utxos` to annotate inputs &
outputs instead.

core/account: do not delete expired, in-use acps

---

sdk/java/src/main/java/com/chain/http/Client.java

This is an interface revision of #687. It should be backported to the `1.1-stable` branch.

sdk/java: allow customizable CA certs

---

cmd/cored/main.go
core/account/indexer.go
core/account/indexer_test.go
core/query/index.go
core/query/query_test.go
core/query_test.go

Delete spent account outputs in a separate block processor from the
indexing block processor. This is a prerequisite to removing the `query`
processor's dependency on the `account_control_programs` table.
For #668.
The new ordering of block processor dependencies:
(account, asset) <- query <- (expire ACPs, delete spent outputs)

core/account: delete spents in separate processor

---

docs/core/get-started/sdk.md
sdk/node/README.md
sdk/ruby/README.md

The Node SDK installation instructions used to yield a package.json that will allow updates to the minor version, which is bad.

sdk/node: ensure correct version semantics for Node SDK

---

core/account/builder.go
core/api_test.go
core/asset/builder.go
core/hsm_test.go
core/txbuilder/builder.go
core/txbuilder/finalize_test.go
core/txbuilder/txbuilder.go
core/txbuilder/txbuilder_test.go
core/txbuilder/types.go
core/txbuilder/witness.go
core/txbuilder/witness_test.go

The `WitnessComponent` interface used to be instantiated by a few different types relating to smart contracts. Now there's only `SignatureWitness` so there's no need for an interface.
`KeyIDs` and `AddWitnessKeys` were only ever being used together, so they're now coalesced.
Some previously exported identifiers didn't need to be, so no longer are.

core/txbuilder: remove unneeded code, unexport some identifiers

---

core/account/annotate.go

Correctly annotate spend inputs with account data. When annotating
inputs, determine the source account by looking up the spent output in
`account_utxos` instead of looking up the control program in
`account_control_programs`. The control program isn't guaranteed to
still exist once it's expired.
In a follow up, we should change the output annotating to use
`account_utxos` as well. We'll need to add the `change` flag to
the `account_utxos` table.
Fix #668.

core/account: annotate spend inputs correctly

---

core/core.go

This accounts for updates affecting validation-critical hashing
in #665 (#677 in 1.1-stable).

core: tick network RPC version to 3

---

installer/mac/CHANGELOG.md
installer/mac/Chain Core.xcodeproj/project.pbxproj
installer/mac/ChainCore/Config.swift
installer/mac/updates/updates.xml

Use `lsof` to check for a process listening on a required port instead of 
creating and binding a new socket. The previous implementation was prone
to false negatives when checking if a port was available.

installer/mac: improve startup port detection, 1.1.1

---

CHANGELOG.md
cmd/corectl/main.go
cmd/cored/main.go

This is a `1.1-stable`-only update that increments Chain Core to 1.1.2. This commit should act as the base for a `chain-core-server-1.1.2` release tag.

core: tick version to 1.1.2

---

core/txbuilder/finalize_test.go
protocol/tx/entry.go
protocol/tx/entry_test.go
protocol/tx/header.go
protocol/tx/issuance.go
protocol/tx/map.go
protocol/tx/mux.go
protocol/tx/nonce.go
protocol/tx/output.go
protocol/tx/retirement.go
protocol/tx/spend.go
protocol/tx/transaction.go
protocol/vm/vm_test.go

The pointers are outside each entry's `body` and `witness`. This is an alternative to the approach in https://github.com/chain/chain/pull/623.

protocol/tx: add cross-entry pointers in parallel with their hashes

---

docs/internal/package-tags-branches.md

It will take a fair amount of legwork to reconstruct 1.0-stable
from our various package release branches, and it may be error-
prone. For now, let's not commit to maintaining that branch, and
hope that updates to 1.0 will be rare.

docs/internal: don't commit to maintaining 1.0-stable

---

cmd/blockcache/main.go
cmd/cored/dev.go
cmd/cored/main.go
cmd/metricsd/main.go
cmd/vet/logparity.go
cmd/vet/testdata/logparity.go
cmd/vet/testdata/logparity_rename.go
core/account/accounts.go
core/config/dev.go
core/core.go
core/fetch/fetch.go
core/generator/block.go
core/generator/generator.go
core/http.go
core/leader/leader.go
core/migrate/migrate.go
database/sql/sql.go
log/log.go
log/log_test.go
protocol/block.go

Standard library package log uses the suffix "f" to
indicate that a function takes a format string. We adopt
the same convention here, plus we use the suffix "kv" to
incicate the arguments are key-value pairs.

log: adopt -kv naming convention

---

core/signers/signers.go
core/signers/signers_test.go

Avoid the Go pitfall involving reuse of loop variables.

core/signers: correctly record xpubs for a signer with multiple keys

---

core/asset/block.go

This is the result of a code audit following the discovery of the bug fixed in https://github.com/chain/chain/pull/716. I found only one other place that needed the same change.

core/asset: avoid Go loop-variable pitfall

---

core/asset/block.go
core/signers/signers.go
core/signers/signers_test.go

This is https://github.com/chain/chain/pull/716 + https://github.com/chain/chain/pull/717.

core/asset, core/signers: correctly record xpubs for a signer with multiple keys; avoid Go loop pitfall

---

sdk/java/src/main/java/com/chain/http/Client.java

Do not rely on OkHttp to retry IOExceptions and perform our own
retry logic in these cases.

sdk/java: retry IOExceptions

---

sdk/java/src/main/java/com/chain/http/Client.java

If a call throws an APIException, we should only advance the client
URL index if the error is a temporary, retriable error. Permanent
errors shouldn't cause us to move on to the next Core URL.
This is a fix for the 1.1-stable branch.

sdk/java: only advance URL on temporary errors

---

sdk/java/src/main/java/com/chain/http/Client.java

Leader election could potentially take 15secs. We need
to ensure the client retry logic takes this into account.

sdk/java: ensure the client retry timespan exceeds leader election

---

sdk/java/src/main/java/com/chain/http/Client.java

The client keeps a list of core URLs which it uses
to load balance requests to the server. An index
is kept corresponding to a position in this list. When
an error occurs the index is increased. 
Previously, it was possible for separate requests to
read the same index and increase it separately. We have
updated the logic to mitigate this by finding the position 
in the list (performing the modulo operation) just before
a request is made.

sdk/java: increase index to core url monotically

---

installer/mac/CHANGELOG.md
installer/mac/tools/build_chain.sh
installer/mac/updates/updates.xml

This replaces a previous commit that linked macapp 1.1.1 to server
1.1.2. We ended up using server 1.1.3.
This update should also be made to main, to keep main up-to-date.

installer/mac: update to version 1.1.1

---

bin/build-docker-de
cmd/corectl/main.go
cmd/cored/main.go
docs/core/get-started/sdk.md
installer/mac/CHANGELOG.md
installer/mac/tools/build_chain.sh
installer/mac/updates/updates.xml
installer/windows/CHANGELOG.md

This commit refreshes `main` with the latest build updates on `1.1-stable` (cored 1.1.3 and the corresponding installer updates).

all: update main branch with server 1.1.3 build updates

---

docs/README.md
docs/internal/package-tags-branches.md

Now that we have the 1.1-stable branch, we can simplify our
documentation workflow by simply generating and uploading
documentation from the tip of that branch. For the time being, it
doesn't seem like a separate docs tag is necessary.
This commit updates various pieces of documentation to account for
this simplified workflow.

docs: use release branches as source of production docs

---

core/account/indexer.go
core/account/reserve_test.go
core/migrate/data.go
core/schema.sql

When indexing account UTXOs, carry the `change` flag onto the
`account_utxos` SQL table from `account_control_programs`. This
will allow the query block processor to use exclusively `account_utxos`
for annotating transactions.
Note that this migration creates a new, non-nullable column. The
migration atomically backfills the column. However, in a rolling deploy,
an older cored binary may try to insert nulls into the `change` column.
This is okay because new rows are only ever inserted by the account
block processor. If the block processor is running on an older 1.1.x
cored, the block processor will error out and be reattempted until it
succeeds. It'll succeed when a 1.2.x process becomes leader and
reattempts the block processor.
Practically, this means the processing of blocks may be …

core/account: carry `change` onto `account_utxos`

---

protocol/tx/entry.go

Bart at chalkboard: A nil interface is not the same as a nil pointer.

protocol/tx: catch more nils in entryID

---

core/coretest/fixtures.go

These two new pins were added in a97b23 and 872e19 but weren't
added to the `coretest.CreatePins` function. The account package's
ProcessBlocks function will start all three of its block processors,
so all three of the pins should be initialized.

core/coretest: add missing pins to CreatePins

---

core/account/accounts_test.go
core/account/annotate.go
core/account/annotate_test.go
core/account/indexer_test.go

Use the `account_utxos` table instead of the `account_control_programs`
table for annotating outputs with account data. We already used it for
annotating inputs but were waiting on the addition of the `change`
column to use it for annotating outputs too.

core/account: annotate outputs using `account_utxos`

---

core/txdb/snapshot.go
core/txdb/snapshot_test.go
protocol/state/snapshot.go

Remove the PriorIssuances type. We only ever use it as a
`map[bc.Hash]uint64`.

protocol/state: remove PriorIssuances type

---

log/log.go
log/log_test.go

Other packages can use AddPrefixkv to add arbitrary
items to the log prefix. A future change will use this
to make chain/net/http/reqid depend on chain/log,
instead of the other way around. This will remove
special-case code in package log, and enable reqid to
use the logging functions defined here.

log: add function AddPrefixkv

---

core/asset/block.go
core/query/annotated.go

The VMVersion and RawDefinition fields on the query.AnnotatedAsset
struct were not used or populated except in the response of a
/create-asset request. The SDKs also do not expose these fields.

core/query: remove unused AnnotatedAsset fields

---

log/log.go
log/log_test.go
net/http/reqid/reqid.go
net/http/reqid/reqid_test.go

With this change, package chain/net/http/reqid uses
log.AddPrefixkv to add the request ID to the log prefix
in the context.
It also removes special-case code from chain/log to add
the request ID there.
This also reverses the dependency between these two
packages, and allows reqid to use other logging
functions from chain/log instead of needing to use
standard library package log.

net/http/reqid: add log prefix

---

protocol/bc/blockheader.go
protocol/bc/entry.go
protocol/bc/entry_test.go
protocol/bc/map.go
protocol/bc/map_test.go
protocol/bc/mux.go
protocol/bc/nonce.go
protocol/bc/output.go
protocol/bc/program.go
protocol/bc/retirement.go
protocol/bc/timerange.go
protocol/bc/txheader.go
protocol/bc/txissuance.go
protocol/bc/txspend.go
protocol/bc/txtransaction.go

This is in anticipation of landing the `entries-validation` branch, which uses some of the new data structures in `protocol/bc` in other packages.

protocol/bc: export various identifiers

---

core/http.go
log/log.go
log/stack.go

Each log line has an entry of the form at=main.go:123
added to it by Printkv. It's not helpful for this
file-line information to point to a logging helper
function (such as log.Printf or core.logHTTPError), so
there were mechanisms to supply an alternative:
- Outside of package log, helper functions were expected
to include an at=foo.go:456 key-value pair to override
the item added by Printkv. In practice, none ever did.
The code to obtain this information is fiddly and gross.
- Within package log, function 'caller' took a 'skip'
argument specifying how many frames to skip before
returning file-line information. This was used
inconsistently. Helper functions Printf and Error used
it to add override entries; Fatalkv and
RecoverAndLogError should have but didn't.
Hopefully, the new …

log: omit functions from 'at' field by name

---

cmd/cored/main.go
core/fetch/fetch.go
protocol/protocol.go

The `protocol.Chain.Store` method for getting a `Chain`'s underlying Store
is only used in one place, `core/fetch.BootstrapSnapshot`. We have
access to the store at its callsite, so pass the store in instead. This
keeps the `protocol.Chain` type cleaner. Generally, the store should
only be used by the `Chain` type itself.

protocol: remove Store getter method

---

protocol/patricia/patricia.go
protocol/patricia/patricia_test.go

The external interface for the patricia tree already exposes set
semantics instead of key-value pairs. The package unit tests still use
the unexported `insert` that took a key value pair. This commit rewrites
those tests to use the exported `Insert` and deletes the now redundant
`insert` method.

protocol/patricia: use set semantics in tests

---

net/http/reqid/reqid.go

Nothing ever uses this "default value" for a missing
request ID. It would be just as well to use the empty
string to represent that case. This is especially true
now that we no longer print a reqid=xxx field at all in
the log when the context doesn't contain a reqid.

net/http/reqid: remove unused exported constant

---

database/pg/pgtest/wrap.go

Alter `pgtest.WrapDB` to call the provided closure during
`driver.Conn.Prepare` instead of in the `driver.Stmt` functions.
We can do this now that Go 1.8 properly handles panics in
`driver.Conn.Prepare`:
https://go-review.googlesource.com/#/c/23576/

database/pg/pgtest: invoke WrapDB func in Prepare

---

cmd/slashland/main.go
cmd/slashland/revid.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Right now, when someone clones the repo and builds using 'go install chain/cmd/cored', the resulting binary will have some minimal version information: the latestVersion constant containing the version string of the last release we made. This comes in handy when someone is reporting trouble and we ask them to run `cored -version` to investigate. But this is only a little better than nothing; there are typically hundreds of commits between releases. Adding a unique string to every single revision (on main) will give us a much more precise idea of what code is being run.
We generate source files for our four main languages: Go, Java, JavaScript, and Ruby. It won't be difficult to add others if we need them.
This PR only begins recording the revision ID. We'll incorporate it into the version …

	cmd/slashland: generate a "rev id" for each commit on main

---

cmd/slashland/main.go
cmd/slashland/revid.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Two fixes here:
1. The revid is now measured on the base branch,
which is not always main. If a local main has never been
checked out, the rev-list command fails, so we must use
the remote ref (e.g. "origin/main" or "origin/1.1-stable").
2. Include the branch name in the revid string. This
lets us distinguish between rev123 on main vs rev123 on
1.1-stable (which can be a different commit).

cmd/slashland: fix revid computation

---

cmd/cored/main.go
core/account/accounts.go
core/config/config.go
core/leader/leader.go
core/recovery_test.go
core/txbuilder/finalize_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Most places in the code base take a `pg.DB` in their external
interfaces. Some take a `*sql.DB`. Update the remaining instances of
`*sql.DB` to `pg.DB`.
This was motivated by trying to call `accounts.NewManager` with a
`pg.DB` and haing to do a `db.(*sql.DB)` cast.

all: use pg.DB

---

cmd/cored/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This gives us more precise information on what code
contributed to a fresh-from-git build, and slightly
simplifies the logic for initializing the version string
on startup.

cmd/cored: use revid constant for dev builds

---

core/leader/leader.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Update the leader failover to update every 500 milliseconds. Allow a
new cored to takeover if the existing leader hasn't updated within 1
second.
Note, in practice, this means that when upgrading to 1.2 in a rolling
deploy, the first deployed 1.2 cored will quickly become leader.
Tested this locally by running a java program that creates
transactions sequentially. Tried killing cored and failing over
between the two.

core/leader: try more frequently; failover faster

---

cmd/slashland/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Before this change, we would blindly add a commit on
every rebase or attempt to land. Now, if the commit
would be empty, we skip it. This lets us land faster
when the HEAD commit has already been through CI.

cmd/slashland: avoid making empty commits

---

cmd/corectl/dev.go
cmd/corectl/main.go
cmd/corectl/prod.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This output mirrors what cored prints with its -version
flag. We also take this opportunity to switch from a
hard-coded "latest release version" string to using the
automatically-generated revid.

cmd/corectl: print additional version info

---

core/recovery_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

TestRecovery has been broken for a while. It only runs when the `LONG=1`
environment variable is set, so it's easy to accidentally break.

core: fix TestRecovery

---

core/account/accounts_test.go
core/account/annotate_test.go
core/account/indexer_test.go
core/account/reserve_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Some of the `core/account` tests can use `pgtest.NewTx` now that
`NewManager` takes a `pg.DB`. This shaves a few seconds off the
package's test time.
```
PASS
ok  	chain/core/account	5.309s
```
vs
```
PASS
ok  	chain/core/account	9.114s
```

core/account: use pgtest.NewTx where possible

---

cmd/cored/dev.go
cmd/cored/main.go
cmd/cored/prod.go
core/api.go
core/api_test.go
core/hsm.go
core/hsm_test.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Rework the construction of the API's http.Handler to avoid a second
function call (to API.Handler). Instead, construct the http.Handler
during Run. Also:
* move the MockHSMHandler into a RunOption.
* move the blockchain ID middleware into the core package
Tested locally through dashboard, including transacting on testnet, resetting, reconfiguring and creating mock HSM keys.

core: implement http.Handler on *API

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
vendor/github.com/coreos/etcd/pkg/fileutil/fileutil.go
vendor/github.com/coreos/etcd/pkg/fileutil/purge.go
vendor/github.com/coreos/etcd/pkg/fileutil/purge_test.go
vendor/github.com/coreos/etcd/raft/README.md
vendor/github.com/coreos/etcd/raft/node.go
vendor/github.com/coreos/etcd/raft/node_test.go
vendor/github.com/coreos/etcd/raft/raft.go
vendor/github.com/coreos/etcd/raft/raft_test.go
vendor/github.com/coreos/etcd/raft/rawnode_test.go
vendor/github.com/coreos/etcd/snap/db.go
vendor/github.com/coreos/etcd/snap/snapshotter.go
vendor/github.com/coreos/etcd/snap/snapshotter_test.go
vendor/github.com/coreos/etcd/wal/file_pipeline.go
vendor/github.com/coreos/etcd/wal/repair.go
vendor/github.com/coreos/etcd/wal/repair_test.go
vendor/github.com/coreos/etcd/wal/wal.go
vendor/github.com/coreos/etcd/wal/wal_test.go

Update our copy of coreos/etcd to `5015480e0c385e7fd9aa8825c26f18c6eba17395`. This picks up changes that are required for compatibility with Windows.

vendor: update coreos/etcd

---

generated/rev/RevId.java
sdk/java/src/main/java/com/chain/http/Client.java

This will allow client applications to build their own
SslSocketFactory and provide it to the SDK's http client.

sdk/java: expose Client.Builder method to set SslSocketFactory

---

core/api.go
core/core.go
core/leader/leader.go
core/transact.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Replace IsLeader() with an enum that can be FOLLOWING, RECOVERING or
LEADING. RECOVERING is used when a process has been elected leader but
has not yet finished recovering the blockchain and becoming leader.
Use this more fine-grained status to enable the /info endpoint even when
RECOVERING. This fixes snapshot downloads so that the /info endpoint can
be used to track the progress of a downloading snapshot.
It's OK for a Recovering process to call forwardToLeader. It'll detect that
it's trying to forward to itself and return a 503 status code.
I tested this locally by connecting to testnet through dashboard. I was able to
watch the snapshot download progress in the lefthand bar.

core/leader: add State enum

---

core/api.go
core/api_test.go
core/core.go
core/leader/leader.go
core/leader/leader_test.go
core/run.go
core/transact.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Encapsulate all of the core/leader state into a struct instead of
using package-level global variables. Also, add a test for leader
failover since it's now possible to unit test.

core/leader: encapsulate state

---

core/fileutil/dir.go
core/fileutil/dir_darwin.go
core/fileutil/dir_windows.go
core/fileutil/doc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

package `fileutil` contains OS-compatible utilities for writing Chain Core's application data

core/fileutil: new package

---

cmd/cored/main.go
cmd/md2html/main.go
cmd/slashland/main.go
cmd/vet/testdata/logparity.go
core/recovery_test.go
core/txbuilder/types.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/txtransaction.go

Clean up some small items found manually and by linters:
* blockPeriod, expireReservationsPeriod are no longer used in cmd/cored/main.go
* move remoteSigner struct definition to be beside its method declarations
* don't include newline in error message in md2html
* simplify boolean check in slashland
* tweak a few function comments to be in "[FunctionName] ..." format
* fix misspelling of "Receiver" in a comment
* check unchecked error value in TestRecovery
* avoid a couple of unnecessary conversions to *bc.Hash in ComputeTxHashes

all: clean up

---

core/pin/pin_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Improve the test coverage of the pin package. This brings statement
coverage from 27.9% to 82.1%.

core/pin: add unit tests

---

core/account/indexer.go
core/asset/block.go
core/query/index.go
core/query_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Fix a few block processor dependencies that were incorrectly missing or
unnecessary.
expire ACPs processor
The expire account control programs processor used to have a dependency
on the query package's transaction annotator and indexer. However, we no
longer use the account control programs for annotation. We only use the
account_utxo table. Instead, we just need to make sure that the account
indexer has successfully added the utxos to the account_utxo table
before we delete the control programs.
asset processor
A block processor can be run on multiple blocks at once. Previously, if
two consecutive blocks both contained transactions issuing a previously
unknown asset, there was a race condition for which value would be
recorded in the first_block_height column. We can fix this by always …

core: fix processor dependencies

---

docs/internal/package-tags-branches.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This change attempts to codify the standards we use to
include changes in a point release. It'll help to have
them written down. We can refine them over time if we
think it's necessary.

docs/internal: document point release standards

---

core/api.go
core/health.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Unexport API.HealthSetter. Now that the leader run function is in the
core package, HealthSetter doesn't need to be exported.

core: unexport API.HealthSetter

---

core/api.go
core/metrics.go
core/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The /rpc/get-blocks RPC endpoint was replaced with the /rpc/get-block
endpoint shortly before the 1.0.0 release.
See 0a590e07e9484872d2ee7a5b28d5b8b3a582764f.

core: remove deprecated /rpc/get-blocks endpoint

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/validation/merkle_test.go

We were importing chain/protocol/vm for some constant values that don't affect the meaning of the tests in merkle_test.go. It's useful to remove edges in the dependency graph where possible so that future refactoring is less unnecessarily constrained.

protocol/validation: remove import of chain/protocol/vm

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/merkle.go
protocol/bc/merkle_test.go
protocol/block.go
protocol/recover_test.go
protocol/validation/bench_test.go
protocol/validation/block.go
protocol/validation/block_test.go

This is part of "entries"-based validation, which moves much of the validation logic into the `protocol/bc` package.
Another carved-off piece of https://github.com/chain/chain/pull/788

protocol/bc: move CalcMerkleRoot here

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/blockheader.go
protocol/bc/entry.go
protocol/bc/map.go
protocol/bc/map_test.go
protocol/bc/mux.go
protocol/bc/nonce.go
protocol/bc/output.go
protocol/bc/retirement.go
protocol/bc/timerange.go
protocol/bc/txheader.go
protocol/bc/txissuance.go
protocol/bc/txspend.go
protocol/bc/txtransaction.go
protocol/bc/value.go
protocol/vm/crypto.go

The `Body` field of each entry type is now exported, and the `body` method of the `Entry` interface is not. Also, some entry fields that hold the IDs of other entries have been renamed fooID. These changes will allow better access to entry data during "entries"-based validation, coming soon.
A carved-off piece of https://github.com/chain/chain/pull/788

protocol/bc: adjust exports and field names

---

dashboard/src/features/app/reducers.js
dashboard/src/features/shared/components/Flash/Flash.jsx
generated/rev/RevId.java
generated/rev/revid.go

Safari 8 and earlier does not natively support the `Map` object. Rather
than adding a polyfill, this replaces the single use of a `Map` as a 
data structure with a plain JavaScript object.

dashboard: replace Map with object in flash message state

---

docs/enterprise/thales-install-guide.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

- update machine key for tct2 command
- include instructions for loading machine image and user files
from HSM front panel

docs/enterprise: update thales install docs

---

core/transact_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add unit tests for `waitForTxInBlock` to verify that the correct
block height is returned when a tx is confirmed and that the tx is
re-submitted for every block that does not contain the unconfirmed tx.

core: add unit tests for waitForTxInBlock

---

sdk/node/src/api/transactionFeeds.js

Fixes a typo in the node SDK transactionFeeds.

sdk/node: fix alias typo

---

generated/rev/revid.go
sdk/ruby/CHANGELOG.md
sdk/ruby/README.md
sdk/ruby/chain-sdk.gemspec
sdk/ruby/lib/chain/access_token.rb
sdk/ruby/lib/chain/response_object.rb
sdk/ruby/lib/chain/version.rb
sdk/ruby/spec/integration/integration_spec.rb

This commit ports the Ruby SDK from tag sdk-ruby-1.0.3 to the

sdk/ruby: update 1.0-stable to most recent 1.0.x Ruby SDK

---

generated/rev/revid.go
installer/windows/CHANGELOG.md
installer/windows/ChainMgr/ChainMgr.go
installer/windows/ChainPackage/ChainCoreInstaller.wxs

This commit ports the Windows installer from tag installer.windows-1.0.2 to the

installer/windows: update 1.0-stable to most recent 1.0.x windows installer

---

generated/rev/revid.go
installer/mac/ChainCore/Base.lproj/Main.storyboard
installer/mac/ChainCore/ChainCore.swift
installer/mac/tools/build_chain.sh
installer/mac/updates/updates.xml

This commit ports the Mac app from tag installer.mac-1.0.2 to the

installer/mac: update 1.0-stable with most recent 1.0.x Mac installer

---

cmd/slashland/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Anecdotal evidence suggests that the current timeout of 3 minutes
is too slow, especially given that the new revid functionality
forces a fresh CI check for any PR.

cmd/slashland: extend success timeout to 4 minutes

---

bin/build-docker-de
generated/rev/revid.go

This commit ports the Docker build tool from tag docker.de-1.0.1 to the

bin/builder-docker-de: update 1.0-stable to most recent 1.0.x Docker build

---

generated/rev/RevId.java
generated/rev/revid.go
installer/mac/CHANGELOG.md
installer/mac/Chain Core.xcodeproj/project.pbxproj
installer/mac/tools/build_chain.sh
installer/mac/updates/updates.xml

Update to Chain Core 1.1.4, which brings improved support for Macs running Yosemite.

installer/mac: tick version to 1.1.2

---

docs/internal/package-tags-branches.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Adjust language to reflect that 1.0-stable should be considered usable
for future releases (if any) on 1.0.x.

docs/internal: revise tagging doc

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/map.go
protocol/block.go

The BlockEntries equivalent of a nil Block is nil. This
change makes MapBlock cover its entire domain -- it's
valid for all values of *Block, including nil.

protocol/bc: make MapBlock correctly transform nil

---

core/api.go
core/core.go
core/fetch/bootstrap.go
core/fetch/fetch.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Refactor bootstrapping by snapshot to not rely on global
variables in core/fetch for reporting download progress.
Previously, as a proxy for detecting successful recovery
from the snapshot, there was an undocumented relationship
between fetch.BootstrapSnapshot and fetch.Fetch where
Fetch would mark the snapshot as completed:
```
// If we downloaded a snapshot, now that we've recovered and successfully		
// booted from the snapshot, mark it as done.		
if sp := SnapshotProgress(); sp != nil {		
sp.done()		
}
```
Instead, return a progress type from BootstrapSnapshot
that can be stored on the core.API and used in /info calls.
Remove this value from the core.API after Chain.Recover
completes. This commit also reorganizes all bootstrapping
-specific code in core/fetch to a bootstrap.go file.
I …

core/fetch: refactor snapshot bootstrap

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/vm/bitwise_test.go
protocol/vm/control_test.go
protocol/vm/crypto.go
protocol/vm/crypto_test.go
protocol/vm/introspection_test.go
protocol/vm/numeric_test.go
protocol/vm/splice_test.go
protocol/vm/stack_test.go

This change adds unit tests for stack underflow
conditions in all operations. It uncovered two spec
deviation bugs in CHECKSIG. These are now fixed.
This increases stmt coverage from 95% to 95.3%.

protocol/vm: test stack underflow; fix 2 bugs

---

cmd/slashland/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Running 'git commit' (without --allow-empty) will fail
when the file contents haven't changed, regardless of
the files' time stamps. We want to detect this situation
ahead of time and skip committing when the tree is
clean.
Unfortunately, diff-index, which is what we use to check
for a clean tree, *does* consider timestamps when
computing the diff; fortunately, running 'git add' fixes
this and causes the behavior of diff-index to match what
commit looks for in its "nothing to commit" error
message.
So now we explicitly add the files before checking to
see if the tree is clean.
This also gives us enough confidence to remove the
--allow-empty check on commit. It would be preferable
for chainbot simply to fail, alerting us that there's a
problem, rather than producing an empty commit and …

cmd/slashland: fix logic to avoid empty commits

---

cmd/md2html/doc.go
cmd/md2html/main.go
docs/index.html
docs/layout.html
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Adds command line option for specifying a version prefix for all docs, using
`text/template` for substituting values in HTML.

cmd/md2html: support version prefix in doc generation

---

core/config/config.go
core/fetch/fetch.go
core/generator/block.go
core/recovery_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/block.go
protocol/block_test.go
protocol/prottest/block.go
protocol/recover.go
protocol/recover_test.go

The intent here is to clarify the sequence of events: validate, apply, commit. It's part of a larger simplification of the validation API, most of which happened in (and leading up to) https://github.com/chain/chain/pull/788.

protocol: rename Chain.CommitBlock to CommitAppliedBlock

---

cmd/cored/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

By default, package crypto/tls uses the operating
system's set of global root CAs. This is unsuitable for
a typical production deployment, where the opeator will
run its own CA and provision its own certs.
This change provides a new environment variable:
ROOT_CA_CERTS=certs.pem
This variable holds a filename of a file containing a list
of PEM-encoded root X.509 certificates.
This is a back port of a change made in #684 with
updates to the logging call sites.

cmd/cored: configure root CA pool

---

bin/build-centos-rpm
bin/build-cored-release
cmd/benchcore/main.go
cmd/cored/main.go
cmd/cored/plain_http.go
cmd/deploy/main.go
docker/ci/bin/setup-core
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The `insecure_disable_https_redirect` build tag has been
renamed to `plain_http`. This commit is a part of the work
involving replacing the `dev` and `prod` build tags with more
granular options (started in #859).

cmd/cored: rename insecure_disable_https_redirect

---

cmd/md2html/main.go
docs/core/get-started/install.partial.html
docs/css/style.css
docs/layout.html
docs/protocol/specifications/txgraph-draft.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

For layouts, the content variable is parsed first as its own template, followed 
by the layout with the newly updated content.
Valid filetypes are whitelisted for template processing. All others are passed 
through without processing.

cmd/md2html: parse all text content as templates

---

cmd/md2html/doc.go
cmd/md2html/main.go
docs/core/get-started/install.partial.html
docs/css/style.css
docs/index.html
docs/layout.html
docs/protocol/specifications/txgraph-draft.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Backport of #852 and #866 from main. 
Includes version strings in documentation templates, and an updated
`md2html` supporting template substitution.

docs: add version prefix

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/transactionFeeds.js

sdk/node: transactionFeeds use correct MAX_BLOCK_HEIGHT

---

docs/js/layout.js
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Previous regex relied on the presence of `/core` in the
URL. This prevented the correct version from being detected
on multiple paths.

docs: improve version string parsing

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/CHANGELOG.md
sdk/java/src/main/java/com/chain/api/BaseQueryBuilder.java

This is a backport of #888 and includes a pre-emptive changelog
entry.

sdk/java: support more flexible filter parameter types

---

cmd/slashland/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

GitHub removed support for the squash property in merge
requests. They replaced it with a new property called
merge_method, which is an enum rather than a bool.
See https://developer.github.com/changes/2017-04-07-end-merge-methods-api-preview/.

cmd/slashland: support new GitHub merge API

---

database/pg/pgtest/ctx_test.go
database/sql/sql.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Propagate the context from our own database/sql package to the standard
library database/sql package.
For now, we still need our own database/sql wrapper for logging. We
might be able to replace it with a driver that performs the logging, but
composing drivers is tricky.

database/sql: propagate context to standard lib

---

core/hsm.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This file should also be excluded when cored
is built using the `no_mockhsm` tag.

core/hsm: adhere to no_mockhsm tag

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/validation/vmcontext.go
protocol/validation/vmcontext_test.go
protocol/vm/context.go
protocol/vm/introspection.go

The spec for `CHECKOUTPUT` says that when matching a retirement entry, `code` must be the empty string only if the expansion flag is false. The implementation was missing that check.

protocol/validation: add test of expansion flag to checkoutput

---

bin/wait-and-configure
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

`wait-and-configure` waits until a local Chain Core daemon is ready, and
then attempts to configure it. You can use this script as part of a
quick reset-and-configure loop while iterating on code. For example,
some of our teammates use a Make target that executes the equivalent of
the following:
```
go install $(CHAIN)/cmd/corectl
go install $(REPO)/cmd/cored
-dropdb core
createdb core
rm -rf ~/Library/Application\ Support/Chain\ Core/raft
bin/wait-and-configure &
cored
```
Previously, `corectl config-generator` could be used in place of `wait-and-configure` for fast iteration loops, but since it now requires a running instance of Chain Core, we need something that can run in the background.

bin/wait-and-configure: new utility script

---

database/pg/listen.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The lib/pq library will invoke the listener callback for new database
connections in listeners, in addition to error conditions. Don't log
anything if there's no error.
This removes the error=<nil> log statements that appear during startup.
```
app=cored buildtag=? processID=chain-mba.local-15286-aa73de33b589e552cb0e at=leader.go:102 t=2017-04-12T01:06:13.303830156Z message="I am the core leader"
app=cored buildtag=? processID=chain-mba.local-15286-aa73de33b589e552cb0e at=listen.go:19 t=2017-04-12T01:06:13.309256877Z error=<nil>
app=cored buildtag=? processID=chain-mba.local-15286-aa73de33b589e552cb0e at=listen.go:19 t=2017-04-12T01:06:13.312147977Z error=<nil>
app=cored buildtag=? processID=chain-mba.local-15286-aa73de33b589e552cb0e at=listen.go:19 t=2017-04-12T01:06:13.312951798Z …
```

database/pg: ignore non-errors in listener

---

core/config/config.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Before using raft to store core config, this value was directly
inserted into the config table. This fixes a bug causing this
value to default to 0.

core/config: set ConfiguredAt

---

Readme.md
core/config/config.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The `prod` build tag has been replaced with granular options.
This commit also adds notes to the Readme about the build
tags that have replaced it.

core/config: remove unused Production field

---

analytics/.gitignore
analytics/README.md
analytics/pom.xml
analytics/src/main/java/com/chain/analytics/Application.java
analytics/src/main/java/com/chain/analytics/Importer.java
analytics/src/main/java/com/chain/analytics/Schema.java
analytics/src/main/resources/log4j2.xml
analytics/src/test/java/com/chain/analytics/SchemaTest.java
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add new java service for importing Chain Core transactions
to an Oracle database.
Future work:
* custom reference data fields
* high-availability (leader election?)
* true batch inserts of transactions
* PL/SQL function for archiving old data
* alerting / health checks?
* configuring views / materialized views?

analytics: add Oracle transaction importer

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/vm/crypto_test.go

This change converts the tests in crypto_test.go to stop
using packages bc and validation to build test fixtures,
and instead define a Context object in one step. Code
coverage stays at 95.3%.
This is a continuation of #886.
Future work: once all test files stop depending on
package bc, move the test code back into package vm
(from vm_test).

protocol/vm: create a Context directly

---

core/txbuilder/finalize_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/tx.go

In https://github.com/chain/chain/pull/788 we lost logic that wrapped validation errors in `ErrBadTx`, which `core/txbuilder` was expecting in order to produce a friendly "transaction rejected" message for the caller. This PR restores that and adds a regression test.
Fixes https://github.com/chain/chain/issues/924.

protocol: wrap validation errors in an ErrBadTx

---

docker/ci/Dockerfile
docker/ci/Readme.md
docker/ci/install/install-codesafe
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
wercker.yml

This will allow us to test our production build targets.
Future work: update the test harness in chainprv to
check production builds.

docker/ci: install Thales CodeSafe SDK

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/transactionFeeds.js

It is an internal value that doesn't need to be exposed to users
developing with the SDK.

sdk/node: remove MAX_BLOCK_HEIGHT from documentation

---

crypto/ed25519/internal/edwards25519/chain_export.go
crypto/ed25519/math/point.go
crypto/ed25519/math/point_test.go
crypto/ed25519/math/scalar.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

A more Go-idiomatic interface to the routines in `ed25519/internal/edwards25519` for doing point and scalar (mod L) arithmetic.

crypto/ed25519/math: EC math primitives

---

crypto/ed25519/ecmath/point.go
crypto/ed25519/ecmath/point_test.go
crypto/ed25519/ecmath/scalar.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This renames `Uint256le` to `Scalar` since it's easier to read. Consequently, to avoid the spelling of `math.Scalar` as deceivingly abstract, the package is renamed to `ecmath`.
PTAL @bobg @kr @danrobinson

crypto/ed25519/math: Rename math.Uint256le to ecmath.Scalar for brevity

---

analytics/src/main/java/com/chain/analytics/Application.java
analytics/src/main/java/com/chain/analytics/Config.java
analytics/src/main/java/com/chain/analytics/Importer.java
analytics/src/main/java/com/chain/analytics/JsonPath.java
analytics/src/main/java/com/chain/analytics/Schema.java
analytics/src/test/java/com/chain/analytics/JsonPathTest.java
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add ability to index custom columns extracted from JSON reference data.
This does not yet handle configuration of these custom columns. I'm not
sure what the best interface for configuration is?
Some of the logic to follow json paths got a little gross. I was trying to avoid
unmarshaling the entire transaction object a second time into a 
`Map<String,Object>`, hence the `JsonPath.extract` methods for `Transaction`,
`Transaction.Input` and `Transaction.Output`.

analytics: add indexing of custom columns

---

core/transact.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Fix the transaction rejected log line to include the transaction hex.
It was including the bc.Hash struct:
```
app=cored buildtag=? processID=chain-f2473408badf-1312-75849f6537c61139932c reqid=8e02eefc091511e1137a subreqid=8a9f632c4d23ebc7fd76 at=api.go:406 t=2017-04-17T21:29:52.208568849Z status=400 chaincode=CH738 path=/submit-transaction error="tx {%!s(uint64=9959100764939771229) %!s(uint64=15390949537693335959) %!s(uint64=18383847051763105326) %!s(uint64=11411281842560845055)}: no tx sighash attempted"
```
Should we define a `String` method on the value receiver too? I think
the protobuf type only has one on the pointer receiver.

core: fix log statement to print tx id correctly

---

core/api.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Dashboard knows how to interpret errNotAuthenticated
(CH009) but not the new authz.ErrNotAuthorized (CH011).
For now, just return the authn error even for authz
failures. We can remove this workaround once dashboard
is updated.

core: work around existing auth response handling

---

core/grants.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Policy keys are occasionally getting set without any data, which leads us to this situation where we try to fetch the policy's grant list, see nothing, and then try to conditionally write (`Insert`) a new grant list--which fails, because the key has already been set. 
In the future, we will have more safe conditional writes, but this will fix it for now.

core: use Set instead of Insert when storing grants

---

core/rpc/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This will be used to supply a TLS client cert for requests across corectl and cored.

core/rpc: let the caller provide an HTTP client

---

cmd/corectl/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Read the Chain Core TLS cert/key pair from the data dir.
This allows corectl to connect to a running local cored
even when that cored is built with loopback auth disabled.

cmd/corectl: present a TLS client cert if available

---

cmd/cored/main.go
core/api.go
core/core_test.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

`cored` can now authenticate itself during client calls
to other cored's using a tls certificate.

cmd/cored: allow intra-node client auth

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/ruby/lib/chain/connection.rb

File paths to the client cert, key and trusted CAs
can be passed through the opts param of the Client
constructor.

sdk/ruby: support client cert authn

---

dashboard/src/utility/environment.js
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/client.js

The Client constructor now accepts an opts object as its only argument.
The baseUrl and optional token should be passed as attributes.
The original constructor is now deprecated, but still supported.

sdk/node: new Client constructor

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/client.js
sdk/node/src/connection.js

The Client object can be passed an `https.Agent` with
its `ca`, `key`, and `cert` attributes set as file paths.

sdk/node: support client cert authn

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/ruby/lib/chain/connection.rb

Previously, the Client constructor accepted cert and key
data as separate attributes on its opts config parameter.
It will now accept tls options on an `ssl_params` hash.
The options supported map to `OpenSSL::SSL:Context` params.
Currently, we support `ca_file`, `cert` & `key`.

sdk/ruby: configure client authn with ssl_params hash

---

cmd/corectl/main.go
cmd/cored/main.go
core/tls.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

A Chain Core TLS config is used by cored peers to talk
to each other, and by corectl to talk to cored. All
those processes have the same identity, so now we
automatically trust the local cert, with the expectation
that the peer will also be using it. This makes
authn misconfiguation impossible as long as the cert and
key files are loaded successfully.

core: trust the current process cert

---

encoding/blockchain/blockchain.go
encoding/blockchain/blockchain_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Don't trust the element count when decoding VarstrLists. Allocating an
array at that size may exhaust all memory available. I found this
particular instance using fuzz testing. I think there are probably more
instances of this, like `ReadVarstring31`.
This bug seems most relevant to a multi-Core network. A bad actor could
submit a transaction to the generator with a math.MaxInt32 element in a
VarstrList to crash the generator. Because the transaction doesn't
actually encode math.MaxInt32 elements, it doesn't hit max byte request
body limits.
To fix this generally, we could:
* read incrementally into smaller buffers rather than allocating one
buffer that is the claimed size.
* not use the `io.Reader` interface and instead expose the length of
the unread buffer to decoding routines for …

encoding/blockchain: guard against large mallocs

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/src/main/java/com/chain/api/MockHsm.java
sdk/java/src/main/java/com/chain/http/Client.java

The new constructor takes a Client object as an argument. The private
members of the Client are copied into the resulting builder.
To facilitate this change, a private OkHttpClient member was added to
the builder (no setter method was provided). A new builder method was
also added to allow a user to set a list of URLs.
The impetus for this change was a bug I found when adding client cert
authn to the SDK. Our current method of creating a Client for the MockHsm
(`getSignerClient`) does not persist any configurations set on the httpClient.
The user can get around this by creating a separate Client with the appended
"/mockhsm" string but our provided mechanism is broken as is.

sdk/java: new Client.Builder constructor

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/authorizer.go

Package chain/core will use this to authorize other
cored and corectl processes using the same Subject Name.

net/http/authz: allow caller to add an extra grant

---

core/api.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

A Chain Core TLS config is used by cored peers to talk
to each other, and by corectl to talk to cored. All
those processes have the same identity, so now we
automatically trust the local cert, with the expectation
that the peer will also be using it. This makes
authz misconfiguation impossible as long as the cert and
key files are loaded successfully.
(Motivation copied from
13528a40544824cffd29875e517bb80e1daeec5b.)

core: grant internal access to local subject name

---

core/access_tokens.go
core/api.go
core/authz.go
core/grants.go
dashboard/src/features/accessControl/actions.js
dashboard/src/features/accessControl/components/AccessControlList.jsx
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/accessControl.js
sdk/node/test/callbacks.js
sdk/node/test/promises.js

- use "authorization grant" instead of "ACL grant"
- use "delete grant" instead of "revoke grant" ("delete" is the opposite
of "create")
To avoid conflicts with large ongoing PRs, identifiers in the Node SDK
and dashboard have not been updated, but a future PR will clean those
up.

core: enforce consistent language for authorization grants

---

core/authz.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This will allow a `corectl` configured with the same TLS certificate as
its remote `cored` to make authenticated requests. This is a part of
the work to make `corectl` use the `cored` API exclusively.

core/authz: add endpoints used by corectl to the internal policy

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/authorizer.go

Previously, we were serializing the subj name fields as a map while
deserializing into a nested map keyed with "subject". This was causing
unexpected, unauthorized requests during testing.
This logic will change once we introduce a subj name parser and
finalize the guard data structure but this currently impedes testing.

net/http/authz: make x509 guard data de/serialization consistent

---

dashboard/package.json
dashboard/src/actions.js
dashboard/src/features/accessControl/actions.js
dashboard/src/features/accessControl/components/AccessControlList.jsx
dashboard/src/features/accessControl/components/AccessControlList.scss
dashboard/src/features/accessControl/components/EditPolicies.jsx
dashboard/src/features/accessControl/components/EditPolicies.scss
dashboard/src/features/accessControl/components/GrantListItem.jsx
dashboard/src/features/accessControl/components/NewCertificate.jsx
dashboard/src/features/accessControl/constants.js
dashboard/src/features/accessControl/index.js
dashboard/src/features/accessControl/reducers.js
dashboard/src/features/accessControl/routes.js
dashboard/src/features/accessControl/selectors.js
dashboard/src/features/app/reducers.js
dashboard/src/features/shared/components/CheckboxField/CheckboxField.jsx
dashboard/src/features/shared/components/CheckboxField/CheckboxField.scss
dashboard/src/features/shared/components/TableList/TableList.scss
dashboard/src/reducers.js
dashboard/src/routes.js
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/accessControl.js

When rendering access control objects, we merge multiple 
authorization grants into a single table row. Policies for
the merged row can be edited inline.

dashboard: coalesce authorization grants by guard data

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/legacy/fuzz_test.go
protocol/bc/legacy/txinput.go

Ignore the input witness if the input's asset version is unknown.
I included a test with the fuzz input transaction that found the
problem.
Fix #982.

protocol/bc/legacy: fix unknown asset versions

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/authorizer.go
net/http/authz/tls.go

Future work: update /create-authorization-grant to verify that the grant data is well-formed.

net/http/authz: standardize X.509 matching

---

core/api.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/authorizer.go

We need to be able to pattern match on routes when looking up policies, so that we don't need to define a route-policy mapping for every asset dashboard attempts to return.

net/http/authz: match on routes, mux-style

---

core/authz_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Adds basic tests for authz grants and policies. Testing is done at the
http level.

core: add tests for authz grants/policies

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/legacy/transaction.go

Remove TxData.Scan and TxData.Value. We never store individual
blockchain transactions in the database any more.

protocol/bc/legacy: remove TxData db methods

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/legacy/map.go
protocol/bc/tx.go
protocol/state/snapshot.go
protocol/state/snapshot_test.go

Remove spent prevouts from the state tree. Previously, we would
remove the prevouts but then immediately add them back.
Fix #1018

protocol: delete spent prevouts

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/asset.go
protocol/bc/tx.go
protocol/validation/fuzz_test.go
protocol/validation/validation.go

Guard against nil pointer dereferences.
Currently, the protocol/bc protos are only created from legacy.MapTx so
not all fields may be nil. There are probably more, but these are the
ones that the fuzz tester or I found.
Fix #983.

protocol/validation: check for missing fields

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/pom.xml
sdk/java/src/main/java/com/chain/api/MockHsm.java
sdk/java/src/main/java/com/chain/exception/ConfigurationException.java
sdk/java/src/main/java/com/chain/http/Client.java
sdk/java/src/test/java/com/chain/TestUtils.java
sdk/java/src/test/java/com/chain/integration/FailureTest.java

File paths to the client cert and key can now be passed as `TLSCRT`
and `TLSKEY` respectively. RSA private keys adhering to both PKCS#1
and PKCS#8 are supported. The Java standard library doesn't support
PEM encoded keys so the BouncyCastle Crypto APIs library has been
added for its parsing functionality.

sdk/java: support client cert authn

---

core/access_tokens.go
core/config/config.go
core/grants.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/grant.go

When a core migrates from 1.1 to 1.2, it will need to turn its access tokens into grants. When we start a core that needs to migrate its config table, we also migrate these access tokens.

core/config: migrate access tokens to grants 

---

desktop/windows/ChainMgr/ChainMgr.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

As of 338f54eb2dda298fcf3d6d0baa2c1f0d40c088b1, the
default home dir for cored is simply $HOME/.chaincore.
For a windows desktop install, it's better to use
LOCALAPPDATA.
This change also moves the Postgres data dir inside the
Chain Core home dir and improves support for older
versions of Windows.

desktop/windows: override home dir

---

core/grants.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Previously, the check for bad subject fields was iterating through
the top-level "guard_data" object. We expect these fields to be
wrapped in a nested "subject" map.

core: fix x509 guard data validation

---

core/blocksigner/blocksigner.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Always lock the block height, even on the generator.
If the generator is a signer, it calls SignBlock directly instead of
ValidateAndSignBlock. Since the generator created the block, it's
safe to skip the validation. Previously, calling SignBlock directly
also skipped locking the block height in the `signed_blocks` table.
This change modifies the generator flow to also lock the block height.
The generator _should_ only generate one block at each height. Locking
the block height can help guarantee we don't violate that.
Also, currently on main there's a bug where anyone with network access
could call the sign-block RPC endpoint and get the generator to sign its
own alternative, valid next block. With this change at least that scenario
would be detected.

core/blocksigner: always lock block height

---

core/access_tokens.go
core/authz_test.go
core/config/config.go
core/grants.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/grant.go

This makes the `/create-authorization-grant` RPC consistent in behavior to all other `/create-`-prefixed endpoints.

core: return grant in create-grant API response

---

core/account/builder.go
core/asset/builder.go
core/txbuilder/types.go
core/txbuilder/witness_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/src/main/java/com/chain/api/Transaction.java

Can it really be that we've had an unneeded `AssetAmount` in the `SigningInstruction` structure all this time?

core/txbuilder: remove the AssetAmount from a SigningInstruction

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/validation/validation_test.go

Use t.Run in validation tests. Most of the validation tests have
convenient descriptions in the test case struct already.

protocol/validation: use subtests

---

core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The SDKs expect /info to return the `configured_at` property as an
RFC3339, but recent changes had converted it to millisecond Unixtime.
This PR restores the original format.

core: convert info's configured_at property to RFC3339

---

cmd/cored/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The chain/core API object depends on reading a config
object during startup, and reading the config object
depends on reading from raft storage, which in turn
depends on handling HTTP requests. We previously handled
this by adding the API handler to the mux after setup.
This caused us to respond 404 to any non-raft request
received during the brief startup time.
Now, we install a handler in the mux immediately, but
synchronized with the API handler, so it blocks until
the API handler is ready. This should provide the
correct behavior for all HTTP responses at all times.
In the future, we might investigate lazily loading the
config object to avoid this awkward data dependency
sequence altogether.
Fixes #1053.

cmd/cored: avoid spurious 404 responses

---

core/api.go
core/authz_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This workaround, returning HTTP 401 instead of 403,
turns out not to be ideal, since dashboard has behavior
for 401 we don't want here. We decided to update
dashboard in a followup, but for now we can remove
this so at least we're returning the correct status.

core: remove authz workaround

---

cmd/cored/main.go
core/api.go
core/authz.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The matching rules for policies are the same as for
ServeMux: it treats a pattern ending in / as a prefix.
Adding / to the table not only matches the exact request
path /, but any other path not reflected in the table.
Putting policy public on that pattern therefore allows
any unauthenticated request to any path we may have
inadvertently left out of the table. It is safer to
"fail closed" -- to reject missing paths.
Redirecting / to /dashboard/ entirely outside of authz
lets us avoid adding this pattern to the policy table.

core: remove req path / from policy public

---

Readme.md
cmd/cored/main.go
cmd/cored/plain_http.go
core/config/config.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

With this change, TLS will be required by default, and can be made optional with build tag plain_http. Our intention is to require TLS internally during development (hence why the default build configuration is to require it) and for production, but not to require TLS for desktop builds (Mac OS X and Windows).
This change also unconditionally sets the secureheader field HTTPSRedirect to false. Chain Core never listens on both TLS and non-TLS ports simultaneously, so it is pointless to ever set this field to true. Doing so was a longstanding mistake, which we might as well fix now.
Future work: consider renaming plain_http to plain_http_ok to better reflect that TLS is optional (not prohibited) in that configuration.

cmd/cored: enforce TLS without build tag plain_http

---

core/account/reserve_test.go
core/recovery_test.go
core/rpc_test.go
core/txbuilder/finalize_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/prottest/block.go

Use option functions for configuration in NewChain.
In #1046, I'd like to add an Option for configuring the
initial block program's quorum.

protocol/prottest: use option funcs

---

cmd/cored/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Commit 9cadcdc68e9933cb8be17fd4232e982b0d48756f meant to
put the redirect handler outside of (before) authz, but
didn't.

cmd/cored: handle / redirect outside authz

---

core/generator/block.go
core/generator/generator.go
core/generator/generator_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/prottest/block.go

Handle failures to commit blocks gracefully. Previously, the generator
could get stuck requiring a restart to make progress.
Fix #1034.

core/generator: handle commit block failures

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/authorizationGrants.js
sdk/node/src/connection.js
sdk/node/src/util.js
sdk/node/test/camelSnake.js
sdk/node/test/promises.js
sdk/node/test/util.js

This commit enforces consistency of behavior and language for the Node
SDK's auth grant interface. Most significantly, the Node SDK will now
arrayify X509 Subject attributes where necessary.

sdk/node: sanitize X509 guard data

---

cmd/corectl/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This fixes a 400 HTTP response from cored.
The fields 'guard_type' and 'guard_data' are defining
a guard, not a grant (which is the overall request).
With this change, editAuthz reuses the type definition
from createToken, factored out into a package-level
named type.

cmd/corectl: fix grant/revoke request body

---

cmd/cored/main.go
core/authz_test.go
core/grants_test.go
database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Both package raft and package core used to rely on a TLS
client config in DefaultTransport. We inadvertently
broke raft when core stopped using DefaultTransport and
we stopped configuring it.

database/raft: plumb TLS config into raft

---

core/fetch/fetch.go
core/generator/block.go
core/generator/generator.go
core/generator/generator_test.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Previously, core/generator and core/fetch had their own local pointers
to the latest block and latest snapshot. We already need to store and
expose blockchain state on the Chain struct for the /sign-block RPC.
To address #519 without too invasive of changes, I think we'll need to
pull the state from the shared Chain struct.

core: use Chain.State to retrieve latest bc state

---

cmd/cored/main.go
core/blocksigner/blocksigner.go
core/generator/block.go
core/generator/generator.go
core/generator/generator_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When requesting signatures, marshal the block once. Besides avoiding the
extra work of marshalling multiple times, this resolves the data race in 
https://github.com/chain/chain/issues/988#issuecomment-296818634
Tested locally by setting up and using a 2-of-2 network.

core/generator: marshal block once

---

database/raft/membership.go
database/raft/membership_test.go
database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When a new cored joins a raft cluster, there must be an associated grant stored in that cluster in order for this new cored to talk to the other members of the cluster. 
We'd like the existence of this grant to be a prerequisite for a new member joining the cluster. Similarly, we'd like it to be impossible to delete a grant that is associated with a cluster member, unless that member is also removed from the cluster. In order to keep track of this, we're creating a list of "allowed members"--that is, addresses associated with nodes that are allowed to become members. 
This commit creates that list, but doesn't hook it up to the rest of the code managing cluster membership.

database/raft: create the allowed members list

---

core/api.go
core/health.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The only reason we used interface{} as the value type in
map healthErrors was so we could include nil values (to
show up as JSON null). If we delete entries instead, we
don't need to show null and we can type check the values.

core: use more specific type for health errors

---

dashboard/src/features/app/components/Sync/Sync.jsx
dashboard/src/features/core/components/CoreIndex/CoreIndex.jsx
dashboard/src/features/core/reducers.js
dashboard/src/features/testnet/reducers.js
dashboard/src/features/testnet/utils.js
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/src/main/java/com/chain/api/CoreConfig.java
sdk/node/src/api/config.js
sdk/ruby/lib/chain/config.rb

SDKs maintain backward compatibility with network RPC version, but this
field is deprecated in favor of the equivalently-valued crosscore RPC
version.
Also includes dashboard updates. The dashboard assumes the
presence of a 1.2 Core.

sdk: rename network RPC version to crosscore RPC version

---

database/raft/raft.go
database/raft/state/state.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

We want cored log output to be useful for operators. For
our own debugging purposes, we can add and remove
logging as necessary during development, or use other
tools such as memory debuggers and tracing.

database/raft: remove debugging log messages

---

docs/core/learn-more/authentication.md
docs/core/learn-more/blockchain-operators.md
docs/core/learn-more/configure-block-signers.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This commit is meant to be an MVP update to documentation that
addresses authentication and authorization. In particular, it updates
language around "network tokens" to account for our new worfklow around
crosscore and crosscore-signblock policies.

docs: update docs to account for authz updates

---

cmd/cored/main.go
core/authz_test.go
core/grants_test.go
database/raft/membership_test.go
database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The standard library's `net/http` package modifies the http client's transport field when requests are made. Therefore it's not safe to check if we should use TLS by checking the transport. This PR adds a `useTLS` flag to the raft service; in the future, the raft service may be configured by passing in run options, a la cored.

database/raft: add useTLS config option

---

core/api.go
core/errors.go
core/leader/leader.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

If there's no leader process yet, respond with a 503 status code
from leader-only endpoints.
Fix #1064.

core/leader: handle missing leader

---

core/generator/block.go
core/generator/block_test.go
core/migrate/data.go
core/schema.sql
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When upserting a pending block as the generator, only upsert if the
new block is at a higher height than the previous block. This wraps
up #519 for the generator.
This should land after #1079.

core/generator: only upsert higher pending blocks

---

database/raft/tls.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

We need to verify just the hostname, not including the
colon and port number suffix.

database/raft: match behavior of crypto/tls

---

database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

DefaultClient (which uses the system cert pool) will
refuse to validate the peer's certificate.

database/raft: use correct HTTP client

---

Readme.md
cmd/cored/loopback_auth.go
cmd/cored/main.go
core/config/config.go
dashboard/src/features/core/components/CoreIndex/CoreIndex.jsx
dashboard/src/features/core/reducers.js
docs/internal/api-spec.swagger.yml
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/loopback_authz.go
sdk/java/src/main/java/com/chain/api/CoreConfig.java
sdk/node/src/api/config.js
sdk/ruby/lib/chain/config.rb

"Localhost" is more legible than "loopback". This builds on the
direction already started by the "localhost" authorization guard.
The loopback_auth build tag will be updated in the future, when there is
less QA churn.

all: use "localhost auth" instead of "loopback auth"

---

core/api.go
core/authz.go
core/errors.go
core/membership.go
database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Enforces the allowed members list and adds an endpoint to actually add to this list. 
Next: Connecting corectl to that endpoint.

database/raft: enforce allowed members list

---

database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

We need to save the initial snapshot to the WAL
immediately when joining a cluster. Failing to do this
means subsequent entries are not saved until the next
snapshot, causing a crash on restart.
In the vendored raft package, on startup, the read
snapshot serves as the base index for the slice of
entries. The slice of entries is initially empty, and
entries are appended as they're read. Entries with an
index greater than the currently read entry are sliced
off.
The crash happens there. If we fail to save the initial
snapshot, then the base index will be 0 and the first
entry record has a nonzero index, causing an
out-of-bounds slice operation.

database/raft: fix WAL snapshot after joining a cluster

---

cmd/corectl/main.go
core/membership.go
database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

... for raft. 
Also includes a fix to the raft package: previously, raft did not anticipate a failure partway through a node attempting to join the cluster, and so it created the WAL directory and the node ID in an order that did not accommodate retrying after a partial failure.

cmd/corectl: new command to add allowed addresses

---

dashboard/src/features/accessControl/actions.js
dashboard/src/features/accessControl/components/EditPolicies.jsx
dashboard/src/features/accessControl/components/GrantListItem.jsx
dashboard/src/features/accessControl/constants.js
dashboard/src/features/accessControl/reducers.js
dashboard/src/features/accessControl/selectors.js
dashboard/src/features/shared/components/CheckboxField/CheckboxField.jsx
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Persist individual grants in the redux store instead of just policy names
to allow access to the `protected` flag.
Protected grants are marked as `checked` and `disabled` when editing,
indicating to users that they cannot be removed.

dashboard: support protected grant flag

---

cmd/corectl/main.go
core/rpc/rpc.go
core/rpc/rpc_test.go
docs/core/reference/corectl.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This is a generic utility for blocking until cored is available.
A typical usecase would be as follows:
```
cored &
corectl wait
corectl config-generator
corectl create-token foobar client-readwrite
```

cmd/corectl: add wait subcommand

---

cmd/cored/main.go
core/rpc/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When connecting to signerd we need to use the trusted
root cert pool that was configured, so we can't use the
DefaultTransport in package net/http.

cmd/cored: use correct HTTP client

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authn/authn.go
net/http/authn/loopback_auth.go

This is a temporary workaround until we can more
carefully plan how to treat authn vs authz in various
clients such as Dashboard. Currently, we want to return
a 401 to indicate that the user needs to supply some
credentials, but we want to avoid returning that error
for requests to known-public resources (/dashboard/).
In the future, we should avoid ever returning 401,
internally treating authn as a set of orthogonal
credentials, which may legitimately be empty. (An empty
set of credentials is still useful when accessing public
resources.) Clients should then detect the "needs to
prompt for credentials" situation by requesting access
to a known lowest-common-denominator resource (most
likely /info) and looking for a 403 response to that
request.

net/http/authn: return 401 when loopback_auth is off

---

cmd/corectl/main.go
core/rpc/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This commit allows corectl to report formatted error data (chain code,
message, and detail) to the command-line user.
Fixes #1078

cmd/corectl: expose cored error messages

---

docker/ci/install/install-rust
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
wercker.yml

Pin the versions of all crates to the ones originally installed when rust was
added to the docker image.
This makes the build reproducible so future versions of crates won't break the
docker image build (like they're doing now)

docker/ci: Pin rust crate versions

---

bin/upload-testnet-info
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
testnet/public-info.json

testnet-info.chain.com provides publicly-available information
that is consumed by the dashboard when configuring Chain Core DE
for testnet. Historically, there were two methods of hosting this
information:
1. via Heroku, using the server implemented in cmd/testnet-info.
This is the current hosting solution.
2. via S3, using bin/upload-testnet-info and the testnet package.
This is a legacy implementation and is not used.
This commit removes files related to Item 2 above.

testnet: remove legacy testnet-info files

---

docker/de/startup.sh
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Now that corectl does not talk to the data store directly, we need the Docker startup script to wait for cored to become available before generating an access token.
Example output:
Chain Core is online!
Listening on: http://localhost:1999
Autogenerating acccess token with client-readwrite privileges...
Copy the whole line below:
client:965aca3b62a068bf57af2302c621359237116ee6683f17fd5ca09d86645886ed

docker/de: fix startup.sh token generation

---

cmd/testnet-info/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

"network RPC" has been superseded by "crosscore RPC".
testnet-info.chain.com should provide the crosscore RPC version with
both the old and new names.

cmd/testnet-info: use "crosscore RPC" language

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/tx.go
protocol/state/snapshot.go

Changes the snapshot to store and check the max time of the nonce,
rather than the tx maxtime. Also enforces the nonce uniqueness with
the block timestamp.
Fixes #1128

protocol/state: fix duplicate nonce bug

---

cmd/cored/main.go
core/api.go
core/tls.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authn/authn.go

The std library package crypto/tls provides several
options for ClientAuthType; see
https://godoc.org/crypto/tls#ClientAuthType. None of
these do what we want, which is to request a client
cert, and validate it if given, but to treat an invalid
cert the same as a missing client cert: the connection
should be permitted but the cert should not be used in
authz.
We can fix this by using RequestClientCert and calling
Verify ourselves in the authn package. This also
requires plumbing to give authn access to the cert pool.

net/http/authn: make client certs more optional

---

core/config/config.go
core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

We need the configured root cert pool to verify the
generator's TLS cert.

core/config: use TLS config for cross-core RPC

---

cmd/cored/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

We need the configured root cert pool to verify the
generator's TLS cert.

cmd/cored: use TLS for remote generator RPCs

---

desktop/windows/README.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This clarifies that the README is mostly intended to be used for building the installer from source. It also fixes the paths used in the step-by-step build instructions and adds the necessary build tags to the compilation step.

desktop/windows: fix README for 1.2

---

Readme.md
bin/build-docker-de
desktop/mac/Chain Core.xcodeproj/project.pbxproj
desktop/mac/tools/build_chain.sh
desktop/windows/ChainPackage/ChainCoreInstaller.wxs
docs/core/get-started/sdk.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/pom.xml
sdk/node/README.md
sdk/node/package.json
sdk/ruby/README.md
sdk/ruby/lib/chain/version.rb

Notes:
- Mac app is not taggable until full build size is known (will follow
in subsequent commit)
- Windows app is versioned as 1.2.0, since it's not clear what the
installer will do with prerelease suffixes. The Windows app with the
final 1.2.0 cored will have a patch version greater than zero.

all: version tick to 1.2.0-rc1

---

core/api.go
core/core_test.go
core/membership.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This fixes a bug where a single internal grant was being created with an empty certificate for cores that were being run without a TLS config.

core: don't create self-grant for raft member list if not using TLS

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/java/src/main/java/com/chain/api/Transaction.java

Moving visibility from private to protected allows derived classes to
access the builder internals for custom client-side behavior.

sdk/java: relax visibility of Transaction.Builder properties

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/CHANGELOG.md
sdk/node/package.json

Forgot to do this, needs to be 1.2.1 because 1.2.0 was already tagged.

sdk/node: tick verson to 1.2.1

---

core/migrate/data.go
core/schema.sql
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Remove a few secondary indexes that are redundant or unused:
* The account_utxos_output_id_key constraint is redundant with the
primary key of the account_utxos table which is already on the
output_id.
* The signers_type_id index is intended to be used on JOINs between
the assets/accounts tables and the signers table. The primary key
of the signers table is already on the ID. The signers table also
already scopes its IDs by the type of signer (ex, acc123). There's
also not a high enough cardinality on the type column to be useful.
* The assets_sort_id index is never used.

core/migrate: drop unnecessary secondary indexes

---

cmd/blockcache/main.go
cmd/decode/main.go
core/transact_test.go
core/txdb/snapshot_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/hash.go
protocol/patricia/patricia_test.go
protocol/recover.go

These are picked up by go vet. The pointer has a String
method, the value does not. Unfortunately, this makes
non-addressable bc.Hashes a little difficult to format.
I opted for calling the value-receiver method `Bytes` and
using the `%x` format specifier here. Another option is to
keep the `HexString` method and prefer `HexString` to
`String` so that we can use it when we have a non-pointer
value. Thoughts?

all: fix use of %s format string with bc.Hash

---

core/asset/asset.go
core/txbuilder/actions.go
core/txbuilder/constraint.go
core/txbuilder/txbuilder_test.go
core/txbuilder/witness.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/bc/bctest/tx.go
protocol/bc/legacy/map.go
protocol/vmutil/builder.go
protocol/vmutil/builder_test.go
protocol/vmutil/script.go

The `Builder` object keeps track of jump-target addresses and fills them in when `Build` is called.

protocol/vmutil: add mechanism for adding jumps in Builder

---

cmd/cored/mockhsm.go
cmd/cored/no_mockhsm.go
core/config/config.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This affects two features: mockhsm and reset (with
corresponding build tags no_mockhsm and no_reset).
The rule is: feature flags in chain/core/config always
default to false; build tags in chain/cmd/cored must set
them to true when the feature is enabled. This can be
either because the build tag is present, e.g. http_ok,
or absent, e.g. no_reset.
This also fixes a bug. Previously, building with
no_reset would incorrectly report reset=true in the
cored version output. A file in cored was explicitly
setting it to true when the feature was enabled, and the
default value hard coded in package config was also
true, but nothing ever set it to false when the feature
was disabled.

cmd/cored: set feature flags consistently

---

cmd/report/doc.go
cmd/report/main.go
cmd/report/summary.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The new command "report" executes its arguments, then uploads the result to S3 and adds a summary of the result to a history table for a convenient web-accessible overview.
Future work: announce in Slack when a test fails.

cmd/report: report test results to S3

---

cmd/vet/defaulthttp.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add check to cmd/vet to check for use of the http.DefaultClient and
its package-level convenience functions.

cmd/vet: add defaulthttp check

---

core/authz_test.go
core/grants_test.go
database/sinkdb/sinkdbtest/sinkdbtest.go
database/sinkdb/state_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add package with test utilities for creating test sinkdb instances.
This will also prevent tests in separate packages from interacting.

database/sinkdb/sinkdbtest: new package

---

database/sinkdb/sinkdb.go
database/sinkdb/state.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Propagate a flag indicating the existence of the key instead of
interpreting an empty byte slice as a nonexistent key.

database/sinkdb: fix key existence check

---

database/pg/pgtest/pgtest.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This package doesn't use nearly all of the methods of
type testing.TB. By defining a new interface containing
just what we need here, we let the caller supply their own
object. In particular, *log.Logger satisfies Fataler.

database/pg/pgtest: make useful outside of package testing

---

cmd/integtest/doc.go
cmd/integtest/main.go
cmd/integtest/pg.go
cmd/integtest/sysprocattr_darwin.go
cmd/integtest/sysprocattr_linux.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This new command provides support for integration test
packages. It sets up common resources neede by most or
all tests, such as running a postgres cluster and
providing a working directory.

cmd/integtest: run integration tests (new command)

---

database/sinkdb/state.go
database/sinkdb/state_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Before the sinkdb refactor, all accesses to the state were protected
by raft.Service's stateMu. After the refactor, sinkdb directly accesses
the state without acquiring raft.Service's mutex, allowing data races.
This adds a mutex to protect the state. The raft package's stateMu is
still necessary for protecting raft-specific fields and for the
condition variable. There are a few places where we can likely avoid
acquiring stateMu's mutex and instead rely on State's internal locking.

database/sinkdb: protect state with a mutex

---

core/errors.go
database/sinkdb/sinkdb.go
database/sinkdb/state.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Remove raft.ErrUnsatisifed, replacing it with sinkdb.ErrConflict. By
default map sinkdb.ErrConflict to a 409 status code. When we introduce
code paths where sinkdb.ErrConflict is result of a temporary conflict in a
read-modify-write cycle, we can add another error mapped to a temporary
error.
Also, remove the error return value from raft.State.Apply. The raft
package would panic if it was non-nil. Now, the sinkdb state will panic
in those error conditions.

database/sinkdb: expose ErrConflict

---

core/config/mockhsm.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Log the block pub key in hex.
When configuring with the blockhsm, previously cored would log the
raw bytes of the block-signing key and add an unnecessary "\n"
to the end:
```
app=cored buildtag=? processID=chain-mba.local-26010 reqid=5ab5bcc6660c33989b9f at=mockhsm.go:21 t=2017-05-18T17:15:14.019931843Z message="Generated new block-signing key J\xd4\x00\x0f\xbcR*\xf84(\x1c\xa0q\xb1\xe3\x16\xd1;\u0382R\xb2\xdbuS\x15\x0f4\xc3\x00\x852\n"
```

core/config: fix mockhsm log statement

---

core/bench_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/validation/validation.go
protocol/validation/validation_test.go

A new benchmark (included in this PR) led us to discover that during `ValidateTx` of certain kinds of very large transactions, some entries were being validated multiple times - in some cases, thousands of times each. This short-circuits that by caching the result of entry validation for the duration of `ValidateTx`.
```
$ benchstat before.txt after.txt 
name                                                   old time/op  new time/op  delta
BuildTx/1-asset--1-issuance--build-8                    591µs ± 1%   606µs ± 3%     ~     (p=0.056 n=5+5)
BuildTx/1-asset--1-issuance--build-sign-8               852µs ± 1%   838µs ± 0%   -1.56%  (p=0.008 n=5+5)
BuildTx/1-asset--1-issuance--build-sign-finalize-8      339ms ± 7%   333ms ±12%     ~     (p=0.841 n=5+5)
BuildTx/1-asset--10-issuance--build-8 …
```

protocol/validation: cache per-entry validation results during ValidateTx

---

core/errors.go
core/membership.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

In calls to the /add-allowed-member RPC endpoint, return a 400 Bad
Request error response when the provided address is invalid.
```
jackson@mba ~ $ corectl allow-address http://:1999
RPC error: CH161 Address is invalid
Detail: too many colons in address
```

core: respond with Bad Request on bad address

---

core/authz.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The handler installed at the path /debug/pprof/ serves the heap and
blocking profiles at /debug/pprof/heap and /debug/pprof/block. The
handler was installed at /debug/pprof/ but the policies were defined on
the path /debug/pprof, so these profiles were inaccessible.
Fix #1213

core: set policies for /debug/ endpoints

---

cmd/cored/main.go
database/sinkdb/sinkdb.go
database/sinkdb/sinkdbtest/sinkdbtest.go
database/sinkdb/state_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go
net/raft/raft_test.go

Move cluster initialization out into two explicit methods: Init to
initialize a new cluster and Join to join an existing cluster.
For now this only changes the interface of the net/raft package. In a
followup we can introduce init and join endpoints.

net/raft: add explicit cluster initialization

---

docs/core/reference/versioning.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This commit refines our versioning language such that
backward compatibility guarantees only hold between server packages and
client packages of the previous minor version. In particular, this
is intended to eliminate any interpretation that holds that new SDKs
should be backward-compatible with application code written for a
previous SDK version.
The goal of this change is to allow us to pursue a more aggressive
release roadmap, and to eliminate versioning kludges in the SDK. It
allows us to introduce new usage patterns (potentially breaking changes)
in consecutive minor versions of the SDK without eliminating a smooth
upgrade path for application code.

docs: clarify backward compatibility rules for SDKs

---

core/errors.go
core/rpc/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/httperror/httperror.go
net/raft/raft.go

Use the httperror package to format and parse raft endpoints' errors. When we add separate join and init endpoints, this change will help propagate meaningful errors.

net/raft: format and parse errors using httperror

---

cmd/cored/main.go
cmd/testnet-reset/main.go
core/rpc/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Use the Chain Core version in the rpc client user agent instead of the
raw build tag. The version string is strictly more useful than the
buildTag that it's derived from.

core/rpc: use version over buildTag

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/lookup_test.go
net/net.go

Be sure to call SplitHostPort only on address types
where it is known to be meaningful. A Unix domain socket
uses a filepath as the address and SplitHostPort will
return an error.

net: fix Dial for Unix domain sockets

---

cmd/cored/main.go
database/sinkdb/sinkdb.go
database/sinkdb/sinkdbtest/sinkdbtest.go
database/sinkdb/state_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go
net/raft/raft_test.go

Developer Edition does not support multi-process Chain Cores. In EE,
processes are required to use TLS for authentication internally, so we
can remove the useTLS parameter to raft.Start.
Related to #1220.

net/raft: only use HTTPS

---

bin/build-cored-release
bin/run-tests
cmd/benchcore/main.go
cmd/corectl/main.go
cmd/cored/init_cluster.go
cmd/cored/main.go
core/api.go
core/authz.go
core/config/config.go
core/core.go
core/errors.go
core/run.go
docker/ci/bin/setup-core
docs/core/reference/corectl.md
docs/core/reference/cored.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Remove the BOOTURL environment variable from cored. If there is no
existing raft cluster configuration, start cored but return an error
from all RPCs indicating that the process's cluster needs to be
initialized.
The operator can call the /init-cluster or /join-cluster endpoints to
start a new Chain Core cluster or join an existing cluster.
Introduce a new 'init_cluster' build tag to automatically initialize
a new cluster if one doesn't exist in cmd/cored. Use this new build tag
when building Developer Edition.

cmd/cored: do not automatically setup raft cluster

---

core/api.go
core/core_test.go
core/membership.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

The useTLS flag is unnecessary now that Chain Core always uses TLS for
internal RPCs.

core: remove useTLS flag on API struct

---

core/health.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Propagate raft errors into the /info health object.
Fix #1219.

core: propagate raft errors

---

core/access_tokens.go
core/config/config.go
core/grants.go
core/membership.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/store.go

The caller doesn't need a copy of the existing grant;
it already has all that data at hand.

net/http/authz: remove unnecessary return param

---

cmd/integtest/doc.go
cmd/integtest/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Don't inherit the Unix user's GOPATH and CHAIN
variables. Instead, maintain a dedicated Go workspace
with a checkout of the repos in $HOME/integration.

cmd/integtest: check out repos into working dir

---

core/asset/block.go
core/query/annotated.go
core/query/index_test.go
database/pg/pg.go
database/pg/pg_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Ignore invalid json in reference data when indexing transactions, and skip
reference data that contains the null byte escape sequence. This
fixes two separate but related issues:
1. A user could use Chain Core to create a transaction with the
`\u0000` escape sequence inside a string within the reference data.
Chain Core would allow the transaction, because `\u0000` is a valid
escape sequence in a JSON string, but indexing the transaction
would fail (#1239) due to Postgres jsonb limitations:
https://www.postgresql.org/message-id/E1YHHV8-00032A-Em@gemulon.postgresql.org
2. A non-Chain Core client could create transactions with any sort of
invalid json, and Chain Core would fail to index them. These
transactions would be impossible to create with Chain Core, but
another but other Chain …

core/query: validate reference data

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Immediately campaign for leader when initializing a new cluster. This
should speed up tests. We'll no longer need to wait electionTick * tickDur
before having a usable raft node.
If we convert to raft.RawNode at some point, we could avoid the
less-than-ideal synchronous Ready channel wait. Because StartNode
documents that it appends ConfChangeAddNode entries for each peer
to the initial log, I think we are guaranteed that the channel wait will
not block indefinitely. We might not be guaranteed that it'll actually
contain all the initial config changes, but in that case Campaign will
fail silently and the node will campaign after electionTick ticks.
See coreos/etcd#7985.

net/raft: campaign immediately in Init

---

core/access_tokens.go
core/config/config.go
core/grants.go
core/membership.go
database/sinkdb/op.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/store.go

This will allow the caller to combine the returned Op
with other Ops into an atomic batch.

net/http/authz: return sinkdb Op instead of executing

---

docker/ci/install/install-java
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Downloads of JDK 7 are now behind a registration wall. This commit uses
a copy that is cached to the chain-qa S3 bucket.

docker/ci: fix java installation

---

database/sinkdb/sinkdb.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

It is extremely error-prone to write the same key more
than once in a batch. So we disallow it.

database/sinkdb: disallow multiple writes to a key in a batch

---

database/sinkdb/op.go
database/sinkdb/sinkdb.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This will allow clients to combine conditions and
effects in constructors for composite operations, with
an interface convenient for other packages to use in a
call to Exec.
Consider a hypothetical create function:
func create(key, value) sinkdb.Op {
return sinkdb.All(
sinkdb.IfNotExists(key),
sinkdb.Set(key, value),
)
}
Create could return []Op, but Op is easier to
combine with further operations:
db.Exec(ctx,
create(key, value),
sinkdb.Delete(key2),
)

database/sinkdb: introduce All combinator

---

core/asset/block.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Passing the definition as a string can cause unexpected problems with
escaped strings, so we pass it as a byte array instead.

core/asset: fix inserts for escaped strings

---

core/query/annotated.go
sdk/java/src/main/java/com/chain/api/Transaction.java
sdk/node/src/api/transactions.js
sdk/ruby/lib/chain/transaction.rb

This PR allows witness arguments to be viewed in the SDK. This is necessary for certain applications of Ivy for which a client needs to be able to inspect the values used to satisfy a contract.

core/query: annotate witness arguments

---

core/config/config.go
database/sinkdb/sinkdb.go
database/sinkdb/state.go
database/sinkdb/version.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/store.go

We replace the "found" bool with a Version object that
contains more information, and update the call sites to
use the new interface.
In the future, we can define a conditional Op, IfMatch,
that checks the key's version.

database/sinkdb: return the version of a read key

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

cored cannot operate without an active raft service. Chain Core
leadership is maintained Postgres, so crashing the process ensures
that the leader will abdicate if its raft service fails.
Since runUpdates runs forever, there is now no way for a raft.Service
to be marked as 'done'. If we want to add a way to gracefully shutdown
a raft service in the future, we can add back the donec channel and
related logic.

net/raft: crash process on unrecoverable errors

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

In WaitRead we ignore context.DeadlineExceeded errors returned from
waitRead because we use context.WithDeadline for timing out
individual retries. It's also possible that the parent context has
expired, so return the parent context's error if that happens.

net/raft: respect context deadline in WaitRead

---

bin/upload-docs
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This bug is a legacy from the previous version of upload-docs, which
only uploaded a specific release directory.

bin/upload-docs: fix upload paths

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

If no context deadline is set, use a 30 second timeout in WaitRead.
Otherwise, WaitRead may block forever.

net/raft: add default WaitRead timeout

---

core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

If the joined cluster is already configured, the process will still be
running as an unconfigured Core process. Exec self to restart and
reload the config, if any. In the long term, configuration should be
incremental and not require a process restart to pick up changes.

core: exec self in /join-cluster

---

docs/1.2/core/reference/corectl.md
docs/1.2/core/reference/cored.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

These commands and their documentation were added in
d20cecb8ca646d547b9031f9db9180753245115d, in the 1.3 development branch.
When the documentation was reorganized, it seems that it was cut from
main and the documentation for these commands snuck in.

docs/1.2: remove corectl init, corectl join

---

database/sinkdb/state.go
database/sinkdb/version.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

For now use the existence of the key in the state map for
Version.Exists. Once we have a backfill for Chain Core 1.2.x
snapshots that omit versions, we can use the version check
instead.

database/sinkdb: use map key existence for Exists

---

bin/upload-docs
cmd/docsync/main.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add support for zero-downtime doc deploys by uploading files one at a time 
with correct the content type, and removing files not present on the local 
system after the fact.

cmd/docsync: new command

---

database/sinkdb/state.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Always update the state's applied index, even if there is no change to
the state. Otherwise, triggerSnapshot will create a snapshot at an index
less than the true applied index. This can result in less than
`nSnapCatchupEntries` entries being available.
Also, document that `nSnapCatchupEntries` must be <= `snapCount`.
We might want to consider making snapCount and nSnapCatchupEntries
fields on Service so that we can write snapshot tests without simulating
a 10,000 entries.

net/raft: always update AppliedIndex

---

database/raft/raft.go
database/raft/state/state.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Always update the state's applied index, even if there is no change to
the state. Otherwise, triggerSnapshot will create a snapshot at an index
less than the true applied index. This can result in less than
`nSnapCatchupEntries` entries being available.
This is a fix for the 1.2 branch.

database/raft: always update AppliedIndex

---

dashboard/NOTICE
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/NOTICE

Add license notices for dependencies of dashboard and Node SDK, generated with [yarn](https://yarnpkg.com/lang/en/docs/cli/licenses/), with one additional notice added manually.

dashboard: add notices for dependencies

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/test/accessTokens.js
sdk/node/test/accounts.js
sdk/node/test/assets.js
sdk/node/test/mockHsmKeys.js
sdk/node/test/transactionFeeds.js
sdk/node/test/transactions.js

Does not include tests for objects that don't have individual test files
yet:
- utxos
- balances

sdk/node/test: add per-object tests for queryAll

---

dashboard/package.json
dashboard/src/features/shared/components/SelectField.jsx
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

An earlier design used markdown formatting for
conveying important information. It has since been
redesigned.

dashboard: remove markdown dependency

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
vendor/golang.org/x/crypto/sha3/cshake.go
vendor/golang.org/x/crypto/sha3/cshake_test.go
vendor/golang.org/x/crypto/sha3/kmac.go
vendor/golang.org/x/crypto/sha3/kmac_test.go
vendor/golang.org/x/crypto/sha3/sha3.go
vendor/golang.org/x/crypto/sha3/tuple_hash.go
vendor/golang.org/x/crypto/sha3/tuple_hash_test.go

Upstream SHA1: 01149f4f7c0fce7c9a9dde8465f684ed34bb5eb5
Upstream URL: https://github.com/chain/golang-crypto/tree/cshake/sha3
Requirement for Confidential Assets spec.
Discussion: https://groups.google.com/forum/#!topic/golang-dev/e2q_nHWGWyE

vendor/golang.org/x/crypto: add cSHAKE, KMAC and TupleHash

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/tls.go

X25519 should be faster and less likely to experience timing sidechannels.
(See CVE-2016-7056 for a recent practical key recovery attack against P-256)

net/tls.go: Prefer X25519 over NIST P-256

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/util.js

Removes the use of functions that are not compatible with Node 4.x.

sdk/node: ensure Node 4 compatibility

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
wercker.yml

Wercker requires a pipeline specification in `wercker.yml` (however trivial) to publish successful statuses to a PR. We are not backporting Node SDK updates to older branches (yet), but this will allow us to publish Node integration test statuses to PRs that merge into the 1.2-stable branch.

wercker.yml: make branch compatible with node pipeline

---

database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Save the snapshot position to the WAL before saving the snapshot data to
disk. On boot, we open the WAL at the most recently saved snapshot's
position. If we don't save the position to the WAL first, we might open
the WAL at a snapshot position that was never saved to the WAL.
This is a fix for the 1.2.x release line.
See coreos/etcd#8082, coreos/etcd#8088.

database/raft: save snapshot position first

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

When adding a new node to the cluster, wait for the conf change to be
committed and applied before taking a state snapshot and responding
to the new node.
Previously, Join had a race condition between the application of the
conf change entry and the taking of the snapshot. If the snapshot was
taken before the conf change was committed or applied, the new node
would try to boot its state machine from a state that did not include
itself in the configuration. It could mistakeningly think that it is a
single-node cluster and try to elect itself, panicking when its node
id doesn't exist in the progress list: See issue #1330.
Waiting for the conf change to be applied ensures that:
* The /raft/join endpoint only returns if adding the node to the cluster
was committed.
* The snapshot returned …

net/raft: wait for ConfChange to be applied

---

database/raft/raft.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When adding a new node to the cluster, wait for the conf change to be
committed and applied before taking a state snapshot and responding
to the new node.
Previously, Join had a race condition between the application of the
conf change entry and the taking of the snapshot. If the snapshot was
taken before the conf change was committed or applied, the new node
would try to boot its state machine from a state that did not include
itself in the configuration. It could mistakeningly think that it is a
single-node cluster and try to elect itself, panicking when its node
id doesn't exist in the progress list: See issue #1330.
Waiting for the conf change to be applied ensures that:
* The /raft/join endpoint only returns if adding the node to the cluster
was committed.
* The snapshot returned …

database/raft: wait for ConfChange to be applied

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Save the snapshot position to the WAL before saving the snapshot data to
disk. On boot, we open the WAL at the most recently saved snapshot's
position. If we don't save the position to the WAL first, we might open
the WAL at a snapshot position that was never saved to the WAL.
See coreos/etcd#8082, coreos/etcd#8088.

net/raft: save snapshot position first

---

cmd/corectl/main.go
cmd/cored/main.go
core/api.go
core/authz.go
core/core.go
core/errors.go
database/sinkdb/sinkdb.go
database/sinkdb/state.go
database/sinkdb/state_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Add an evict command to corectl to remove a node from a Chain Core
cluster.
On startup in cmd/cored, call sinkdb.DB.Ping to perform an empty write
to test the raft configuration. This helps handle the scenario where an
evicted node boots up without realizing it's been evicted. The other
nodes won't necessarily replicate the eviction entry to the node if
they've already moved on and forgotten the evicted node's address.
Addresses part of #1118.

core: add /evict rpc endpoint

---

Readme.md
bin/build-centos-rpm
docs/future/core/reference/corectl.md
docs/future/core/reference/cored.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Document the changes to cored and corectl for explicit cluster
management.
These changes were introduced in d20cecb8ca646d547b9031f9db9180753245115d.

docs/future/core: document cluster commands

---

bin/build-cored-release
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

`git rev-parse HEAD` needs to be run before navigating away from
the temporary git repo.

bin/build-cored-release: fix rev-parse bug

---

database/sinkdb/sinkdb.go
database/sinkdb/sinkdb_test.go
database/sinkdb/sinkdbtest/sinkdbtest.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Add Close method to release resources associated with a sinkdb handle
and stop its raft service. Also use this Close method to write a basic unit
test for persistence.
Ideally, we could unit test without gracefully closing the database and the
raft WAL, but the WAL file lock won't be released until the process exits
and the file descriptors are released.

database/sinkdb: add Close method

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft_test.go
net/raft/state_test.go

Add a simple go test for creating a new three-node cluster. In Chain
Core, the database/sinkdb package provides the implementation to raft's
State interface. For this internal test (and future tests), this adds a
simple State key-value store implementation.
This new test takes test statement coverage in net/raft from 14.6% to
63.9%.

net/raft: add unit test for cluster setup

---

docker/ci/install/install-protobuf
docker/ci/install/install-rust
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
wercker.yml

This includes some pretty major upstream changes that affect us: libcollections was merged into liballoc, and that's where we get all of our heap-allocated data structures.
Also bumps rustfmt to 0.9.0, which includes a number of changes to the rustfmt style guide.
Lastly, bumps clippy to 0.0.140, which is confirmed to build on this nightly release.

docker/ci: Update Rust to nightly-2017-06-15

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/http.go
net/raft/raft.go

Move http related logic into a separate file. raft.go was over
1k lines of code and getting unwieldy.

net/raft: split http logic into separate file

---

Makefile
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This commit adds convenience Make tasks for rapid iteration:
- `make`/`make run`: Run Chain Core
- `make resetdb`: Delete contents of development databases in both Postgres and the Chain Core data directory
- `make rerun`: Delete contents of development databases, configure the local core as a generator, and run Chain Core
- `make dashserve`: Run the development dashboard at http://localhost:3000
- `make docserve`: Run the development documentation server at http://localhost:8080

Makefile: add convenience tasks for development

---

docker/ci/install/install-rust
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
wercker.yml

The PPC32 version of the previous nightly we were using seems slightly too old
to cross-compile our code.

docker/ci: Update Rust to nightly-2017-06-20

---

cmd/cored/main.go
core/config/config.go
core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/dev/run-additional-node.sh
net/raft/dev/run-bootstrapped-node.sh
net/raft/raft.go

Adds goroutine for unconfigured cores to check for an updated config from sinkDB and exec themselves to update.
Also includes small fix to make sure raft run scripts don't break if chaincore directories exist already
Fixes #1371

cmd/cored: make unconfigured cores poll for config

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go

Advancing ticks until right before election to speed up tests when initializing a raft cluster (see https://github.com/coreos/etcd/pull/3184) . Changes the approach from #1242 to avoid errors from artificially changing the state machine.
There is some randomness in test timing now, since electionTimeout is randomized in the Raft algorithm (up to +/- 0.4s)
Addresses #1334

net/raft: advance ticks on cluster init

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/transactions.js
sdk/node/test/transactions.js

Per the principle of least surprise, errors in transaction builder functions should bubble up via the promise chain, rather than via a `throw`.
Supersedes #1369.

sdk/node: transaction builder errors should surface in promise rejection

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/http.go
net/raft/raft.go
net/raft/raft_test.go

Adds two unit tests for node eviction: for evicting a single node, and multiple nodes. Also slightly refactors to add a helper function to create a test Raft cluster.

net/raft: add unit tests for node eviction

---

database/sinkdb/state.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft_test.go

Adds unit tests and a fix for restarting a node in a cluster. Previously, restarting the initial node in a cluster would segfault since there was no snapshot to restore from. 
Now, we trigger snapshot while initializing a raft cluster to ensure that we can always restart nodes without errors.

net/raft: add unit test for node restart

---

core/migrate/data.go
core/schema.sql
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

To detect and report out-of-date raft configs (see https://github.com/chain/chain/issues/1167), we'll be writing the core ID to postgres and raft. This migration adds a core ID table to postgres to be able to crosscheck the core ID that we'll write to raft.

core/migrate: add core_id table

---

core/config/config.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

To detect and report out-of-date raft configs (see https://github.com/chain/chain/issues/1167), we'll be writing the core ID to postgres and raft. 
This writes the core ID to postgres when we configure.

core/config: write core ID to postgres

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go
net/raft/state_test.go

Fix a data race in TestEvictMultiple detected by `go test -race`.
There were a few places where we locked stateMu before accessing State
and a few places where we didn't.
The State implementation from database/sinkdb does its own locking,
so this wasn't a real race in Chain Core, only in tests using the
net/raft state implementation.
We could remove the net/raft's mutex altogether if it weren't for two
things:
* the ConfState stored on Service that needs to be updated every time
the raft configuration changes
* the stateCond condition variable used for waiting until applyEntry
changes the state
This change
* adds a mutex to the net/raft test state
* documents that the State interface must be safe for concurrent access
* adds a new confMu mutex for protecting the ConfState
* removes all …

net/raft: refactor locking

---

cmd/corectl/main.go
cmd/cored/main.go
core/config/env.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

For https://github.com/chain/chain/pull/1390, we need to call HomeDirFromEnvironment in the config package so we can identify the raft directory. Moving from core into config to avoid circular imports.

core/config: move HomeDirFromEnvironment from core to config

---

core/config/config.go
core/config/config_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

See https://github.com/chain/chain/issues/1167
In https://github.com/chain/chain/pull/1385 and https://github.com/chain/chain/pull/1387, we write the config coreID to postgres whenever we configure a new cored process. This is to detect stale Raft configs resulting from when you restart a cored process, create a new Postgres db, but do not remove ~/.chaincore, preserving an old Raft config.
This PR checks the coreID stored in Raft against the coreID in Postgres (if any), and panics if there is a mismatch, suggesting that the user clean their Raft directory. Also adds a test to make sure we correctly detect stale configs.

core/config: check for stale Raft config

---

core/config/options.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Use the path package instead of path/filepath for forming sinkdb keys.

core/config: use path for forming sinkdb keys

---

core/config/options.go
core/config/options_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add a ListFunc method to return a closure that returns the current set
of values for a set configuration option. Packages consuming
configuration options can accept closures of type
func() [][]string
without needing to import core/config. Passing around these closures
should also ease unit testing.

core/config: add ListFunc

---

cmd/corectl/main.go
core/api.go
core/authz.go
core/core.go
core/errors.go
core/health.go
core/run.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add support for setting and retrieving incremental configuration
options. There are still no configuration options defined so for now
these commands are useless.
* Add a field to /configure to support modifying incremental
config options.
* Add a /config endpoint for retrieving configuration values.
* Add three subcommands to corectl: get, add and rm for retrieving and
manipulating set configuration options.

core: add incremental config options

---

cmd/corectl/main.go
core/config/options.go
core/config/options_test.go
core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

For set configuration options, equality may be defined on a subset of
the fields of the tuple. Previously, we treated an Add of a tuple with
an existing key as a no-op. This splits the Add method into Add and
AddOrUpdate. Add will error if a tuple's key conflicts with an existing
tuple that is not exactly equal to the new tuple. AddOrUpdate will
replace the conflicting tuple.
This commit also updates corectl to allow providing the `-u` flag to
use the AddOrUpdate behavior.

core/config: introduce AddOrUpdate

---

docker/de/Readme.md
docs/1.2/core/reference/changelog.md
docs/future/core/reference/changelog.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Most of our Docker docs use CLI examples that remove the container
after it has finished running. There doesn't appear to be any
reason for this related to running Chain Core itself, and it is
probably not what most people want when running Docker.

docker/de: remove recommendations to remove container

---

dashboard/src/features/transactions/components/Summary/Summary.jsx
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When observing transactions that contain only external 
accounts, users would see identical "Spend" and "Control" 
amounts regardless of the actual inputs and outputs.
External outputs are now coalesced by control program, 
allowing users to see the amount they expect to see on 
the control-side of the transaction, and the resulting 
`change` outputs.

dashboard: coalesce transaction summaries by control program

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/raft/raft.go
net/raft/raft_test.go

Fixes https://github.com/chain/chain/issues/1345
Add unit test to verify raft snapshot matches node state. Moves `snapCount` and `nSnapCatchupEntries` into `service` so we can trigger snapshots more frequently in tests.

net/raft: add snapshot unit test

---

core/access_tokens.go
core/grants.go
core/grants_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

When deleting an access token, delete all of the associated
grants in a single batch. Previously, we'd delete the grants for
each policy separately.
If _n_ is the number of policies, we'd need to wait for _2n_ raft
consensus rounds to delete all of the grants (1 for a linearizable
read, 1 for the write). Now we wait _n+1_ consensus rounds. Since
grants.Delete is just doing a read-modify-write, we should be able
to do an optimistic stale read so we only have to wait for a
single consensus round.
Since this change returns a sinkdb.Op, it'll also make it easier
to delete access tokens and their grants atomically down the
road.

core: delete access token grants in a batch

---

cmd/cored/main.go
cmd/metricsd/main.go
cmd/testnet-reset/main.go
core/rpc/rpc.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Rename Client.Username to ProcessID. Client uses basic auth when
AccessToken is not empty, but Username is the not the username used
in basic auth. Username is only used for the user agent. Rename it
prevent confusion.

core/rpc: rename Client.Username

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/block.go
protocol/protocol.go

The current snapshot (c.state.snapshot) is protected by the mutex
c.state.cond.L. Previously ApplyValidBlock accessed the snapshot
without acquiring the mutex.
Also, fix a few comments in chain/protocol.

protocol: fix ApplyValidBlock unprotected access

---

dashboard/src/features/shared/components/PageTitle/PageTitle.jsx
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This resolves an issue where site breadcrumbs could link to
`accounts/accounts`. This rendered fine, but was still an
incorrect URL.

dashboard: start breadcrumb links with slash

---

core/api.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authn/authn.go

Provide error details when a request fails to authenticate. If no
credentials were provided, indicate that in the error detail. Otherwise,
provide details on each invalid credential.
Examples:
```
$ CORE_URL=https://mba.local:1999 corectl create-token jackson
RPC error: CH009 Request could not be authenticated
Detail: Invalid credentials: x509: certificate specifies an incompatible key usage
```
```
$ CORE_URL=http://jackattack:almondmilk@mba.local:1999 corectl create-token jackson
RPC error: CH009 Request could not be authenticated
Detail: Invalid credentials: invalid token: "jackattack"
```
```
$ CORE_URL=http://mba.local:1999 corectl create-token jackson
RPC error: CH009 Request could not be authenticated
Detail: No authentication credentials provided.
```

net/http/authn: provide error details

---

core/access_tokens.go
core/grants.go
core/grants_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/authz/store.go

The Delete method does a read-modify-write so the read doesn't need to
be linearizable. If it reads a stale value, the IfNotModified condition
will fail the sinkdb operation.
By avoiding a consensus round on every call to Delete we also bring
down deleteGrantsByAccessToken's # of consensus rounds from _n + 1_
to 1, where _n_ is the number of policies.

net/http/authz: use stale read in Delete

---

core/api.go
core/metrics.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
net/http/httperror/httperror.go
net/http/reqid/reqid.go

Remove the Path and Core ID context annotation from net/http/reqid.
Replace it with additional middleware in chian/core.
Add logging of request user agents.

net/http/reqid: remove path, coreid

---

bin/bundle-dashboard
dashboard/package.json
dashboard/webpack/webpack.app.js
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

This commit adds `license-webpack-plugin` to the dashboard build pipeline. A new file, `3rdpartylicenses.txt`, will be generated in our production webpack bundle. The primary use case for this file is to as the basis for a more accurate NOTICE file in our dashboard source directory, one that only includes licenses for dependencies that we are actually re-distributing.

dashboard: generate licenses during production builds

---

core/fetch/fetch.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
protocol/block.go
protocol/block_test.go
protocol/protocol.go

Previously, we only called CommitAppliedBlock from a single goroutine:
either the core/generator or the core/fetch goroutine. This meant we
could access c.State() and apply new blocks to it without the possiblity
of another goroutine applying newer blocks first.
When we modify Chain to always have an up-to-date state tree regardless
of leader status, the goroutine listening to txdb.ListenBlocks heights
will need to also apply blocks. In preparation for this change, we need
to make committing & applying a block idempotent.

protocol: make block committing idempotent

---

cmd/cored/main.go
core/blocksigner/blocksigner.go
core/blocksigner/enclave.go
core/blocksigner/enclave_test.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Move the Chain Enclave client from main.go into the core/blocksigner
package. Support multiple Chain Enclave URLs in the client to prepare
for retrieving multiple URLs from a core/config configuration option.
A future commit will define a new configuration option and propagate
its ListFunc closure to EnclaveClient.URLs.

core/blocksigner: add EnclaveClient

---

dashboard/src/features/shared/components/PageTitle/PageTitle.jsx
dashboard/src/features/tutorial/reducers.js
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

A bug fix in two parts:
- Dashboard no longer attempts to hide page actions if the tutorial isn't showing
- The default `route` key for tutorials is no longer a page with content

dashboard: prevent default tutorial state from hiding new tx button

---

docker/ci/Dockerfile
docker/ci/install/install-rocksdb
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
vendor/github.com/tecbot/gorocksdb/dynflag.go
wercker.yml

The wercker tests for `database/localdb` failed with a shell segfault. This change installs correct dependencies, including GCC 4.8, to avoid segfaulting on starting up localDB

docker/ci: fix rocksDB and snappy segfault

---

core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

As we move mockhsm into localdb, mockhsm will no longer be consistent across a multi-process raft cluster. This shouldn't be a problem, as we expect the only people running mockhsm with multiple processes to be folks internally doing testing.

core: add warning for using mockhsm with multi-process Chain Core

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
sdk/node/src/api/hsmSigner.js
sdk/node/src/api/transactions.js
sdk/node/src/client.js
sdk/node/src/index.js
sdk/node/test/receivers.js
sdk/node/test/testHelpers.js
sdk/node/test/transactions.js
sdk/node/test/transactionsBatch.js

This moves the HSM signer object underneath the main
`client` object, and adds a placeholder for the `finalize`
call, that passes through the original object, appropriately
wrapped in a batch response as expected.

sdk/node: support CA transaction flow

---

cmd/cored/main.go
core/config.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

core.Config can return raft.ErrUninitialized if the raft cluster is
uninitialized. Like in the config.Load call above, it should be ignored.

cmd/cored: handle uninitialized raft cluster

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
vendor/github.com/beorn7/LICENSE
vendor/github.com/coreos/go-semver/LICENSE
vendor/github.com/coreos/go-systemd/LICENSE
vendor/github.com/coreos/pkg/LICENSE
vendor/github.com/coreos/pkg/NOTICE
vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE
vendor/github.com/matttproud/golang_protobuf_extensions/NOTICE
vendor/github.com/prometheus/client_golang/LICENSE
vendor/github.com/prometheus/client_golang/NOTICE
vendor/github.com/prometheus/client_model/LICENSE
vendor/github.com/prometheus/client_model/NOTICE
vendor/github.com/prometheus/common/LICENSE
vendor/github.com/prometheus/common/NOTICE
vendor/github.com/ugorji/go/LICENSE
vendor/golang.org/x/net/LICENSE
vendor/golang.org/x/net/PATENTS
vendor/golang.org/x/text/LICENSE
vendor/golang.org/x/text/PATENTS

This commit ensures we're complying with open source licenses. For
safe keeping, also include PATENTS and NOTICE (copyright) files.
A subsequent commit will update vendoring instructions to ensure these
files are captured in the future.

vendor: add legalese for vendored go dependencies

---

generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
log/log_test.go

Fix log package test to work with versioned go installations, like
go1.9beta2: https://godoc.org/golang.org/x/build/version/go1.9beta2

log: fix test for verisoned go toolchains

---

cmd/corectl/main.go
docs/future/core/reference/corectl.md
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Remove the hsm-url and hsm-token flags. These flags have been replaced
by a new configuration option that is modified through:
```
corectl add enclave <url> <token>
corectl rm enclave <url> <token>
```

cmd/corectl: remove hsm-url, hsm-token flags

---

core/api.go
core/core.go
core/fetch/fetch.go
core/run.go
core/transact.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Remove package-level globals, encapsulate all state in a Replicator
struct.

core/fetch: encapsulate state

---

core/accesstoken/accesstoken.go
core/transact.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
log/log.go

Move some global vars to global consts. I found these
while auditing the code base for global state that might
prevent us from running multiple core.APIs in the same
process.

all: make unnecessary vars const

---

errors/errors.go
errors/errors_test.go
errors/stack.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb
log/log.go
log/log_test.go
testutil/expect.go

The standard library now provides a more convenient and robust way to get stack frame information, that correctly handles panic frames and non-Go (e.g. cgo) frames. At the same time, we can save some allocations and CPU time while capturing a stack trace by storing just the "callers" slice of PC values as returned by runtime.Callers.

errors: lazily load stack trace info

---

cmd/corectl/main.go
core/config/options.go
core/config/options_test.go
core/core.go
generated/rev/RevId.java
generated/rev/revid.go
generated/rev/revid.js
generated/rev/revid.rb

Add corectl set command.
As-is, GetFunc provides no distinction between values that are not set and values that are set to the empty byte slice. I'm unsure if we have any need for that distinction or how we should expose it if we do.
Also, I stored the tuples in the same format as sets (a ValueSet protobuf), so that all config options can be accessed through List regardless of their type.

core/config: add single-tuple config options

---

docs/1.0/core/get-started/install.partial.html
docs/1.1/core/get-started/install.partial.html
docs/1.2/core/get-started/install.partial.html

We're a small team, focused on making [Sequence](https://seq.com)
a great product over the last few months. We think Sequence is a going
to be a great upgrade path for many Chain Core Developer Edition users.
In the meantime, we're continuing to support Chain Core DE in the
[Community Slack account](https://chain.slack.com/) and elsewhere.
However, we feel we can no longer provide great support specifically for
the Windows installer for Chain Core DE.
This change removes the instructions for using that installer, leaving
Docker as the preferred installation method on Windows.

docs: remove Windows installer

---

core/run.go
docs/1.2/core/reference/cored.md
env/env.go
env/env_test.go

Some applications may want to change the block frequency
based on their traffic patterns.
For example, a value of 250 milliseconds (a factor of four)
improved performance in one application we observed.
This variable can set to any value that can be parsed by
https://golang.org/pkg/time/#ParseDuration such as `250ms`.

core: allow block period to be configured

---

sdk/java/src/main/java/com/chain/common/Utils.java
sdk/java/src/main/java/com/chain/http/Client.java
sdk/java/src/test/java/com/chain/integration/CreateTest.java

It seems that our serializer is not safe to use across threads. This patch removes our global serializer object and adds a serializer instance variable on the Client object. If folks instantiate client objects across threads, then we should be ok here.
Example stack trace from a customer:
```
Caused by: java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
at java.util.ArrayList$Itr.next(ArrayList.java:851)
at com.chain.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96)
at com.chain.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
at com.chain.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRunti …
```

sdk/java: fix gson concurrency bug
